### ISSUE TITLE
FormItem设置labelCol,wrapperCol显示在一行时，窗口宽度小于575会对不齐

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#10591]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p8r4qo49x)

### Steps to reproduce
FormItem设置labelCol,wrapperCol显示在一行时，窗口宽度小于575会对不齐,':'也消失，在在线编辑器没重现出来，我设置了labelCol,wrapperCol，在小窗口情况下不知道为啥没用

### What is expected?
小窗口和大窗口一致对齐有 `:`

### What is actually happening?
小窗口不对齐 缺少 `:`

**Comment by afc163** [comment]
It is by designed.

**Comment by afc163** [comment]
codesandbox 无法重现的话可以尝试提供 github repo 重现。

**Comment by ty-bt** [comment]
那就是说小窗口下， label不能和input在同一行吗？

**Comment by ecgan** [comment]
I am facing this issue as well. I'm designing my app so that it can display well in mobile web view. For my case, the form item's label is a very short string and I'd like the label and input to display in one line. However, it seems that there is a hard-coded width 100% when screen width is 575px or less. See below screenshots. 

![image](https://user-images.githubusercontent.com/417342/68956106-607d4280-0802-11ea-9d8c-6e0d507d1164.png)

![image](https://user-images.githubusercontent.com/417342/68956147-725ee580-0802-11ea-8e43-d0c5702c7263.png)

Can this be fixed please?
