### ISSUE TITLE
Modal context bug

### ISSUE THREAD

**Issue by RaedsLab** [ant-design/ant-design#10656]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n71mmyyly0)

### Steps to reproduce
-0 in page 1
1- open #1 modal -> close it
2- open #2modal -> close it
3-go to page 2
4- bug

### What is expected?
Go to page 2 without error

### What is actually happening?
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by RaedsLab** [comment]
@afc163 any update on this bug ?

**Comment by vitaliymaz** [comment]
I've investigated a little bit the bug and the problem is you are using 
`getContainer={this.getContainer}`
Removing that lines from <Modal>component will help. 

Actually the problem is you manually select a container for your dialog and that container is a part of React app. Why react itself has such behavior, you can read [here](https://github.com/facebook/react/issues/6802).

**Comment by yesmeck** [comment]
Fix in `rc-dialog@7.1.7`
