### ISSUE TITLE
Adding 1 Style by itself when deployed on server

### ISSUE THREAD

**Issue by luthfirrahmanb** [ant-design/ant-design#11025]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.0.3

### Environment
Ubuntu 16.04, React 16.1.1, Chrome 67.0.3396.87

### Reproduction link
[https://ant.design/components/layout/](https://ant.design/components/layout/)

### Steps to reproduce
When on localhost we never adding new style on sidebar with name "ant-layout-sider-dark", but when we deployed on our server it adding by itself on our styling

### What is expected?
ant-layout-sider-dark it never add on our styling

### What is actually happening?
adding it by itself when deployed

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us.

(A good and minimum codpen will save a lot of time 😃)

**Comment by gulian** [comment]
Hi, 

We got the same issue in my team, my colleague has the `ant-layout-sider-dark` class but I haven't. 

It causing trouble when comparing jest snapshot during unit test. We don't know how to provide an example to reproduce it because the code is exactly the same, but the results DOM isn't. 

- We try to remove and reinstall all dependancies and both machine
- We are both using node v8.11.3, on the same operating system (Debian 9)
- Our package.json concerning antd :`"antd": "^3.4.5"`

If you need more details, please ask us, thanks a lot.
