### ISSUE TITLE
Select support readOnly

### ISSUE THREAD

**Issue by finefun55** [ant-design/ant-design#11073]
### What problem does this feature solve?
That is useful when only show user field text，but submit by real value，so we need prevent user manually changes, and only change value by our code.

### What does the proposed API look like?
some as Input component

**Comment by afc163** [comment]
https://codesandbox.io/s/m585xy2x49

You can try controlled mode with onChange.

**Comment by baohouse** [comment]
I think this issue is worth reopening. Right now I have a use case of making State/Province readonly.

For example:
```
<Form.Item label="State">
  {getFieldDecorator('usTerritory', {
    rules: [{ required: true, message: 'Required' }],
  })((
    <Select>
      <Select.Option value="CA">California</Select.Option>
      <Select.Option value="CO">Colorado</Select.Option>
      <Select.Option value="CT">Connecticut</Select.Option>
    </Select>
  ))}
</Form.Item>
```

If it was readonly, then I can call `setFieldsValue({ usTerritory: 'CA' });`, and not allow the user to make changes to its value, and still allow form.validateFields to extract the value for this field.

Right now the workaround is to make this Select component an `<Input readonly />` component, and populate the input with the value of the description, `setFieldsValue({ usTerritory: 'California' });`, and then upon extraction, convert the description to the code value, but this is not optimal if we have a condition where we want to make the Select component normal (not readonly).

**Comment by bgold0** [comment]
I agree, `Input` has readonly this should probably have it too

**Comment by baohouse** [comment]
Ah, found out from some of the other issues that one way to achieve a readonly Select is to pass in a open={false} prop to the Select component to prevent the user from opening the dropdown.

**Comment by Arun-42** [comment]
Hey, why couldn't I find readOnly in Input API at https://ant.design/components/input/#Input

**Comment by shackra** [comment]
@Arun-42 the documentation says that the rest of the props are the same as https://reactjs.org/docs/events.html#supported-events

**Comment by crazyx13th** [comment]
not nice, but I think it works

```
<Select 
	className={props.readOnly ? 'readOnly' : undefined}
	open={props.readOnly ? false : undefined} 
	onChange={!props.readOnly && this.onChange}  
	allowClear={!props.readOnly && props.allowClear} 
	value={value}
>...</Select>
```

```css
.ant-select.readOnly
{
	pointer-events: none;
}
```

**Comment by Mokdasoo** [comment]
it works too

<Select
 (...your props)
 style={readonly ? { pointerEvents: "none" } : {}}
/>

**Comment by ibnumardini** [comment]
Or use this.

```
<Select style={{ pointerEvents: readOnly ? 'none' : 'auto', otherStyle: 'x' }}>
  {children}
</Select>
```
