### ISSUE TITLE
Button 不能作为 link 使用

### ISSUE THREAD

**Issue by wuzhao** [ant-design/ant-design#1108]
伪装成 Button 的链接现在只能通过以下两个方式实现，不优雅：

- `<a className=“ant-btn …”> </a> `
- 通过 Button 的 `onClick` 事件进行转跳。

是不是可以考虑一下 https://github.com/ant-design/ant-design/issues/306 提到的 LinkButton 和 Button 嵌套 a 标签的方式来实现？

**Comment by afc163** [comment]
http://codepen.io/anon/pen/dModmR?editors=001

**Comment by wuzhao** [comment]
![image](https://cloud.githubusercontent.com/assets/712075/13486945/932df616-e150-11e5-8952-65afc551cf20.png)

如果点击在链接外（图中橘黄色区域），没有办法跳转。

**Comment by afc163** [comment]
`<a href="http://www.baidu.com"><Button>link</Button></a>`

**Comment by cdeutsch** [comment]
Nesting a `button` inside an anchor isn't valid HTML according to the HTML spec.

I'd love to have a `LinkButton` component that outputs an anchor with the same styles as a `button`.

**Comment by zhaojinxiang** [comment]
如果 Button 在 link 内，则 button group 会失效

**Comment by lili21** [comment]
@afc163 

`<a href="http://www.baidu.com"><Button>link</Button></a>` 无法在`button group`内使用

**Comment by jonyw4** [comment]
I have this problem too... 
I need to use `Button`,` Button Group` and` Link` *(react-router-dom)* in the same time. But currently I can't do this without lose the effect of `Button.Group`. Example:

```jsx
<Button.Group>
    <Link to="link">
       <Button icon="edit">Edit</Button>
    </Link>
   <Button icon="delete">Remove</Button>
</Button.Group>
```

![captura de tela 2018-09-24 as 13 39 42](https://user-images.githubusercontent.com/14056669/45965653-711b9980-bfff-11e8-9991-3bdee1071d0e.jpg)

I think that it's a good ideia insert a prop that can be called `component` and inject `Link` in`Button` like the example bellow. This is resolve all the problems mentioned above, because you can choose what you wants to put in the component **(Example: a, Link)**:
```jsx
<Button component={Link} to="/link">
  Link
</Button>
```

What do you think guys?

**Comment by cdeutsch** [comment]
I ended up writing my own version of `<Button>` that is similar to @jonyw4's proposal. 

If the `to` prop is present I use a React Router `Link`. If `href` exists I use a regular anchor.

Passing in a `component` prop makes sense so you don't add React Router as a dependency. 👍

**Comment by leonsux** [comment]
今天刚发布完，在Firefox上遇到了这个问题，Link包裹Button是可以的，反过来就不行，哇，好坑啊，emm，也是因为自己忽略了浏览器的兼容问题

**Comment by joshsmith** [comment]
I created a `LinkButton` that has `react-router-dom` as a dependency, and is coupled to classes. It doesn't attempt to exactly recreate how Ant works (see: https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L244) since the way Ant uses children is much more complex than my own needs.

This tries to isolate the dependency for me to a single place, though ideally I would use my own `Button` which accepts a `component` prop instead.

```
import React from 'react';
import { Link } from 'react-router-dom';
// eslint-disable-next-line import/no-extraneous-dependencies
import { arrayOf, node, oneOfType, string } from 'prop-types';

const LinkButton = ({ children, to, type }) => (
  // This is tightly coupled to antd, but tries to anticipate an introduction of a similar component
  <Link className={`ant-btn ant-btn-${type}`} to={to}>
    {children}
  </Link>
);

LinkButton.defaultProps = {
  type: 'default',
};

LinkButton.propTypes = {
  children: oneOfType([arrayOf(node), node]).isRequired,
  to: string.isRequired,
  type: string,
};

export default LinkButton;
```

**Comment by wisetc** [comment]
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    in a (created by Button)

antd-mobile 之 Button 用在 react-router-dom 之 Link 中。
