### ISSUE TITLE
The Transfer's lists style could be controlled respectively

### ISSUE THREAD

**Issue by JackieLs** [ant-design/ant-design#11119]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We have a case like this: after the `onChange` event emit, we will validate the `targetKeys` , if the validation has error, we hope there will be a red border at the outside of the `targetKeys` list, and the error message under the `targetKeys` list, just like the form error style.

### What does the proposed API look like?
Maybe the `listStyle` prop could be an array within two items: [ leftTransferListStyleObject: React.CSSProperties, rightTransferListStyleObject: React.CSSProperties ] or [ leftTransferListClassName: String, rightTransferListClassName: String ]

**Comment by JandersonConstantino** [comment]
Hi,
I'm trying to create a type like as:

```typescript
type ListStyle = {
  leftTransferListStyleObject: React.CSSProperties;
  rightTransferListStyleObject: React.CSSProperties;
}

export interface TransferProps {
  ...
  listStyle?: ListStyle | React.CSSProperties;
  ...
}
```

but when I read the listStyle props happens an error in typescript:

```typescript
  const rightListStyle = listStyle && listStyle.rightTransferListStyleObject
          ? listStyle.rightTransferListStyleObject
          : listStyle
```

![image](https://user-images.githubusercontent.com/15123834/63427078-b0f32880-c3ea-11e9-8285-1d3710680a86.png)

Someone know why this happens?

**Comment by darcien** [comment]
> ![image](https://user-images.githubusercontent.com/15123834/63427078-b0f32880-c3ea-11e9-8285-1d3710680a86.png)
> 
> Someone know why this happens?

The error says it, "Property 'leftTransferListStyleObject' does not exist on type 'CSSProperties'."

Since `listStyle` could be `React.CSSProperties`, and `React.CSSProperties` doesn't have the `leftTransferListStyleObject` property, TS throws an error.

I think you can fix the error by refining the type of `listType` before accessing it's property.
e.g. using `in` instead of accessing the property directly
```ts
const rightListStyle = listStyle && 'rightTransferListStyleObject' in listStyle
    ? listStyle.rightTransferListStyleObject
    : listStyle
```

**Comment by JandersonConstantino** [comment]
@darcien Thank you, this fixes my error.

**Comment by abdih** [comment]
It seems that although #19330 attempts to close this issue by including the phrase 'close #11119' in the PR description, it failed to do so. If this is a correct assessment of the situation, could someone please update this issue's status from 'Open' to 'Closed'. Thank you.

With that being said, since it seems like there are no other issues on the _ant-design_ repo with a 'good first issue' label, I'd appreciate if an experienced contributor could kindly point me towards another such open issue. Thanks in advance.

**Comment by afc163** [comment]
Closed by https://github.com/ant-design/ant-design/pull/19330
