### ISSUE TITLE
DatePicker is calling onFocus/onBlur two times

### ISSUE THREAD

**Issue by fantua** [ant-design/ant-design#11249]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/427yy09wo7)

### Steps to reproduce
1. Open console
2. Open DatePicker
3. Close DatePicker
4. Look at the console output 

### What is expected?
Call onFocus/onBlur one time

### What is actually happening?
DatePicker is calling onFocus/onBlur two times

**Comment by Yangzhedi** [comment]
let me have a try ? @afc163

**Comment by ztplz** [comment]
@Yangzhedi  Sure.

**Comment by Yangzhedi** [comment]
hi guys, I am not sure enough  if my idea is correct.
I think this bug maybe caused by onFocus/onBlur was bind on span tag which wrapped the Pickers, and the onFocus/onBlur function not related to Picker`s open state. so onFocus called the second time when Picker has opened, so do onBlur.
maybe we should use open state to control the onFocus/onBlur?

**Comment by Yangzhedi** [comment]
like this？https://github.com/react-component/calendar/pull/519

**Comment by Kermit-Xuan** [comment]
It's normal in `4.2.3`, https://codesandbox.io/s/427yy09wo7

**Comment by kobewinona** [comment]
Still hasn't been fixed( Also, TimePicker inherits the same issue(
