### ISSUE TITLE
Is the drawer zindex too big? 

### ISSUE THREAD

**Issue by lucasleelz** [ant-design/ant-design#11304]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
react 16.2.0

### Reproduction link
[https://ant.design/components/drawer-cn/](https://ant.design/components/drawer-cn/)

### Steps to reproduce
Click create, owner, DateTime, etc. will not display correctly.

### What is expected?
Other pop-up windows can be used normally

### What is actually happening?
- drawer: z-index: 99999;
- Causes other components with pop-up windows to have problems.

**Comment by afc163** [comment]
Should be same as Modal.

**Comment by yesmeck** [comment]
@kennylbj Could you create a separate issue?

**Comment by kennylbj** [comment]
https://github.com/ant-design/ant-design/issues/11307 @yesmeck

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/ant-design/commit/705e57f7e8f995d550e2290ea7a24b2d7f302b34

**Comment by AndreiBacescu** [comment]
By default, the tooltip is created in body and because the modal is limited to the stacking context of its parent (the parent is nested in body) it will never overlay the tooltip.
More details here: https://coder-coder.com/z-index-isnt-working/

In my opinion, one of the solution for this problem is to use **getTooltipPopupContainer** property from **Slider** component and create a DOM container that is at least, on the same level as **Slider** parent.
