### ISSUE TITLE
Cannot focus Button

### ISSUE THREAD

**Issue by ferdud** [ant-design/ant-design#11309]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
Chromium Version 66.0.3359.181 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jz0yj3roly)

### Steps to reproduce
When I add a ref to Button and then try to focus() this button by ref it tells me that focus is not a function.
Have no problem using it the same way for Input.

Is there a workaround?

### What is expected?
Focus button.

### What is actually happening?
Error, focus is not a function.

**Comment by afc163** [comment]
We don't provide the `ref.focus` function, you should find the dom node and then use `buttonDomNode.focus()`.

**Comment by filipjnc** [comment]
@afc163 I'd reconsider. A good example is setting focus on the notification close button upon opening (so that keyboard users can close use without navigation through the whole app). 

If I try to find the DOM element by id directly after calling notification(), it will not find it since the opening takes a few moments. If the Button component exposed ref.focus, this wouldn't be a problem.
