### ISSUE TITLE
InputNumber 组件的 onBlur 事件不返回数字

### ISSUE THREAD

**Issue by jas0ncn** [ant-design/ant-design#11379]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
antd latest

### Environment
macOS 10.13, Chrome 67

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/pj50174mpx)

### Steps to reproduce
将 `InputNumber` 组件配合 `Form` 组件使用时，如果 `Form.Item` 的 `trigger` 设置为 `onBlur`，将无法正确获取 `InputNumber` 中的数字值。

### What is expected?
正确的在 `onBlur` 事件中获取 `InputNumber` 中的数字

### What is actually happening?
`InputNumber` 在 `onBlur` 事件中无法正常获取数字。

---
详细请查看重现安利中的使用场景。

**Comment by dengyakui** [comment]
我觉得可能因为你在blur事件处理函数中 修改state时 没有进行类型转换e.target.value是字符串类型  导致的报错

**Comment by jas0ncn** [comment]
@dengyakui 你说的我了解。但是可以看一下我附的示例，如果将 `InputNumber· 组件和 `Form` 组件一起用的话（`trigger: 'onBlur'`），无法进行类型转换的，`Form.Item` 是自动代理 `onBlur` 事件的。除此以外，`onBlur` 
是返回事件对象，而 `onChange` 则是直接返回一个数字，这两个的事件回调函数的参数都不一样。如果说 `InputNumber` 和 `Form.Item` 的 `trigger: 'onBlur'` 不兼容，也应该注明一下吧。。。

**Comment by zombieJ** [comment]
`trigger` 属性是收集值的时机，`onBlur` 返回的是原生的 <input />。如果想要做验证的话可以用 `validateTrigger` 属性： https://codesandbox.io/embed/pj50174mpx

api ref: [getFieldDecorator 参数](https://ant.design/components/form-cn/#getFieldDecorator(id,-options)-%E5%8F%82%E6%95%B0)

**Comment by pybuche** [comment]
Hi, I have the same problem

I use `InputNumber` with `redux-form` and the `onBlur` method of the component parses the number into a string. 
I now have a input number that produces strings... To avoid that, I can disable `onBlur` prop but I'd prefer another solution...

Since the thread is in Chinese, can someone please translate what was said before my post? Google Translate doesn't seem to understand either ^^"

**Comment by ztplz** [comment]
@pybuche  They still don't have a clear solution for this problem. Now it's 11.pm in China, if you aren't in a rush, I will work on this tomorrow.

**Comment by zombieJ** [comment]
Hi @ztplz,
I've discuss with @afc163 before. We want to make `rc-form` only record value by `trigger` event and do validate on `validateTrigger` event instead of both record value on `trigger` and `validateTrigger` event.
This can resolve all the component `trigger` not match with `validateTrigger`. But limit time for investigate whether this change will affect current customize component usage. Maybe you can help on this~

**Comment by ztplz** [comment]
@zombieJ  Ok, I am glad to do these things.

**Comment by pybuche** [comment]
Great, thanks! 
No rush @ztplz ;)

**Comment by afc163** [comment]
Closing for it is not a bug in current behavior.
