### ISSUE TITLE
OnSelect for Select form field happens before setting the value

### ISSUE THREAD

**Issue by AlexTemina** [ant-design/ant-design#11453]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
Windows 10, Chrome 67.0.3396.99 (Build oficial) (64 bits), react 16.4.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5yj56pyvx)

### Steps to reproduce
1.- Select and add any options to the Select field with "tags" mode (The only field in the form)
   1.2.- The Select has an 'onSelect' function that forces the value to be "a" no matter what. It also has "onBlur" option to reproduce the same logic but when leaving the field.
2.- Leave the field

### What is expected?
onSelect should force value to be always a.
onBlur works as expected

### What is actually happening?
onSelect doesn't change the value. I guess it's because onSelect happens before the value selected is set, overriding any logic.

---
Maybe I'm using the component wrongly. I want the select multiple with tags to be only one option but allowing the user to set a custom one. So if the user selects a, and then b, only b is set as value. If the user adds "other" the rest of values are also deleted, so it would be like a select single but with custom option.

**Comment by jakejrichards** [comment]
You are correct in saying that the `onSelect` listener is not changing the value of the selection. It simply listens for a change and calls the function passed in. You must manually set the state of your form to have a value and set that value in an `onSelect` function. However, since you are utilizing `Form.create` you will need to tap into the `getValueFromEvent` to allow the value to be correctly set to a (or whatever you need). Hope this helps!

[![Edit n96z8v3754](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n96z8v3754)
