### ISSUE TITLE
Autocomplete is rendering it's menu of options and never remove it from DOM

### ISSUE THREAD

**Issue by AMTourky** [ant-design/ant-design#12501]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
macOS 10.13.6, chrome 69.0.3497.92, react-js 16.3.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6v37r7rjvr)

### Steps to reproduce
Just render multiple Autocomplete components which has dataSource or rendering options somehow

### What is expected?
After blur (or focus on other elements) of selecting an option the options div should be removed from DOM

### What is actually happening?
options div (which contains all options) remains in the DOM and are updated later if user tries to use it again

---
Is it a bug or it's designed to do so? if yes, why?

**Comment by zombieJ** [comment]
It's by design. Every popup component in antd use [`rc-trigger`](https://www.npmjs.com/package/rc-trigger) to management the portal element status. `rc-trigger` by default keep the hidden element in the view, but if the wrapper removed (such as AutoComplete remove), the popup will also be removed.

This design is assume that in most case, popup is not necessary until user use it. But if user used, it may use not only one time. To avoid repeat create and destroy popup to affect the perf (some case, a dropdown list has over 100+ items). Keep them hidden in the document is a good way. And even if user only use it once, when the wrapper component removed, popup element also will be removed.
