### ISSUE TITLE
Form Modal example console error Uncaught (in promise)

### ISSUE THREAD

**Issue by AWR14** [ant-design/ant-design#12679]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Create react app latest, chrome, Mac Book pro

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
In the modal example make a field show an error message and you get  Uncaught (in promise)

### What is expected?
Not to have a console error

### What is actually happening?
A console error

---
I've used this example in my own project and get the same error

**Comment by ilanus** [comment]
I can see ```Uncaught (in promise)``` in console on every form I try to submit on https://ant.design/components/form/ which has validation errors, I assume It's due to this change: https://github.com/yiminghe/async-validator/commit/c9356039b006a97bf98aa55afc47aba5542b1840 making validate a promise which If rejected will log the errors, not sure If this behaviour is correct for production..... @afc163 suggestions?

**Comment by AWR14** [comment]
@ilanus whats the official fix for this as its not 100% clear from https://github.com/ant-design/ant-design/issues/12649

**Comment by zombieJ** [comment]
Merge the issue.
ref: #12649
