### ISSUE TITLE
AutoComplete filters on value, not text

### ISSUE THREAD

**Issue by pybuche** [ant-design/ant-design#13171]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
Mac OS 10.13, Chrome 69

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/24ov6y629j)

### Steps to reproduce
Type "z" in the AutoComplete text box. Nothing is filtered.

### What is expected?
"Zidane" element should be filtered.

### What is actually happening?
The actual behavior is that, no matter your configuration, if you don't write your custom `filterOption` you cannot filter on the text displayed and save the object's value on select.
It's quite weird for users if when they type things on the search box, the non-displayed element data is filtered... 
So if you type "id", all three elements are still available, but if you type "id1", this way, "Zidane" only is available.

For now, I'll work my own filtering function, but I'm a bit surprised this isn't handled natively... Is there an easy way to do it? Thanks!

---
Besides that, great library! Something I was looking for for a long time :)
I'll be glad to take part in enhancing this library in the future!

**Comment by spideeee** [comment]
Add the below props in your auto complete.

```
<AutoComplete
    dataSource={dataSource}
    style={{ width: 200 }}
    filterOption={true}
    optionFilterProp={"children"}
/>
```

The `AutoComplete` component uses the `Select` component which itself uses `rc-select` component.
Since you have used array of objects as your options props. So the `Options` for the select list contains the value of `text` property of your options array. Now the `rc-select` component has a prop `optionFilterProp` (default: `value`), which indicates on which prop of the `Option` child of the `Select` to match for filters. In your case, you are passing it as `text` but that is passed to `rc-select` options as a child, so we need to tell the component to filter based on your `children`.

Another option is that you pass the options as an `array` of `strings`.

**Comment by pybuche** [comment]
Great thanks ! Should be great to have it in the `AutoComplete` documentation though :)

Besides that, I noticed that if you want to use `backfill` with this method, when your circle through filtered values, the actual `value` is backfilled in the input text box.

To reproduce it:
https://codesandbox.io/s/24ov6y629j
Just go with arrow down through the three option, you'll see `idX` in the text box.

**Comment by spideeee** [comment]
We should avoid using the `[{value, text},...]` map as the backfill issue is due to `rc-menu`.

The hierarchy is as follows: AutoComplete -> Select -> rc-select -> rc-menu. So it cannot be fixed here.

This is good to close now, I guess.

**Comment by pybuche** [comment]
Ok I see, so what should I do to have a proper backfill?

**Comment by yutingzhao1991** [comment]
Filter with text is expected, maybe you can custom `filterOption` for your require.
