### ISSUE TITLE
Table: switch rowSelection between object and undefined the selectedRowKeys is keep in table's state

### ISSUE THREAD

**Issue by zheng-chuang** [ant-design/ant-design#13368]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
macOS, chrome  70.0.3538.110, node 10.8.0,  npm 6.2.0, yarn 1.9.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qx3mlkjyqj)

### Steps to reproduce
first: click the button 
second: select some row
then you click the button to switch you can see the problem

### What is expected?
after set the rowSelection to undefined, table should clear all selectedRowKeys in it's state

### What is actually happening?
after set the rowSelection to undefined, the selectedRowKeys is keep in table's state

**Comment by hileix** [comment]
In your case, you set the rowSelection to empty object, `selectedRowKeys` property is not set in rowSelect object.

So it uncontrolled, and the selected state is maintained within the component.So that's what's going to happen.

You can make `rowSelection` controlled by setting the `selectKeys` property of `rowSelection`.

Like [this](https://codesandbox.io/s/ov5l6z9zyq).

[controlled-vs-uncontrolled-components](https://reactjs.org/docs/glossary.html#controlled-vs-uncontrolled-components).

**Comment by zheng-chuang** [comment]
> In your case, you set the rowSelection to empty object, `selectedRowKeys` property is not set in rowSelect object.
> 
> So it uncontrolled, and the selected state is maintained within the component.So that's what's going to happen.
> 
> You can make `rowSelection` controlled by setting the `selectKeys` property of `rowSelection`.
> 
> Like [this](https://codesandbox.io/s/ov5l6z9zyq).
> 
> [controlled-vs-uncontrolled-components](https://reactjs.org/docs/glossary.html#controlled-vs-uncontrolled-components).

thx
