### ISSUE TITLE
Table columns are rendered differently on Chrome and Firefox if fixed width is used.

### ISSUE THREAD

**Issue by Cadabrum** [ant-design/ant-design#13624]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
OS Windows 10, FF 63.0.3 64-bit, Chrome 71.0.3578.98 64-bit, Full HD monitor resolution

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1w5yxry77)

### Steps to reproduce
See example

### What is expected?
Uniform word wrap in the first column for Chrome and FF.

### What is actually happening?
New line after each letter when the table is rendered in Chrome.

**Comment by ztplz** [comment]
Because `word-break` doesn't work on Firefox. Here is [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break).
![image](https://user-images.githubusercontent.com/17755202/49966447-e6419f80-ff5a-11e8-92bf-6f03e083cedc.png)
@afc163 What kind of behavior should we follow? Left picture is Chrome and right is Firefox.

**Comment by ilanus** [comment]
@ztplz In my opinion, the screen on the right make more sense

**Comment by ztplz** [comment]
@ilanus I agree. Sometimes `break work` is not a good choice.

**Comment by afc163** [comment]
Let't remove `word-break`.

**Comment by helloliduofu** [comment]
@afc163 https://developer.mozilla.org/zh-CN/docs/Mozilla/Firefox/Releases/67 fireFox已经支持了对于break-word的支持，暂时只有开发版本有更新，稳定版应该也会尽快增加
