### ISSUE TITLE
请也为春节加上彩蛋！我很喜欢ant design，感谢你们！

### ISSUE THREAD

**Issue by shenguotao2015** [ant-design/ant-design#13847]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
更加人性化的 antd

### What does the proposed API look like?
在配置文件中可以进行配置是否开启

**Comment by yangfan0095** [comment]
![image](https://user-images.githubusercontent.com/21197847/50411743-8c37b880-083d-11e9-826e-b1aecc706e53.png)
😂😅

**Comment by yutingzhao1991** [comment]
+1

> 彩蛋的本意是好的，我觉得把彩蛋弄成主动配置的，加上春节这些更丰富的元素供选择，我想这未尝不可~

**Comment by wang007** [comment]
surprise!!!

**Comment by AkiyamaMinami** [comment]
对的，要是彩蛋能主动配置还是不错的，开发者改都不能改太蠢了...

**Comment by afc163** [comment]
#13848

**Comment by vianvio** [comment]
下回还是放console吧，这样更有彩蛋的感觉，彩蛋是要让人找的，所有人都看到就不算了

**Comment by huang-shi** [comment]
> surprise!!!

surprise mother fxxker!

**Comment by fwh1990** [comment]
希望搞些彩蛋在开发环境。节日主题之类的，因为我在家随时都会写代码，即使是过年。

**Comment by razeencheng** [comment]
吃瓜

![image](https://user-images.githubusercontent.com/16044915/50415513-4fc48680-0856-11e9-8b0c-a80ddb2800a8.png)

**Comment by zhegexiaohuozi** [comment]
挺好的呀，哈哈！

**Comment by rockallite** [comment]
> In computer software and media, an Easter egg is an intentional **inside** joke, **hidden message or image**, or **secret feature** of a work. It is usually found in a computer program, video game, or DVD/Blu-ray Disc menu screen.

Reference: [Wikipedia](https://en.wikipedia.org/wiki/Easter_egg_(media))

Publicly exposed UI elements are a part of a **theme**, not an Easter egg. And a theme should be totally configurable by developers. It shouldn't be secretly uncontrollably activated by the library itself.

However, ant-design is an MIT thing anyway. Legally I can blame library authors for nothing. Instead, **I** should be responsible for the messy things happend on Christmas day, because **I** am the one who chose to embed a specific open-source library in my own projects.

But that doesn't stop me from losing trust in the ant-design project.

**Comment by rockallite** [comment]
Ant-design developers, please read this blog post carefully:
https://blogs.msdn.microsoft.com/larryosterman/2005/10/21/why-no-easter-eggs/

There is nothing new under the sun.
