### ISSUE TITLE
Inconsistent Menu Collapse

### ISSUE THREAD

**Issue by itzsaga** [ant-design/ant-design#14007]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/73m3pqln0q)

### Steps to reproduce
Change `Menu.Item` string from "One" to "Home"

### What is expected?
The Menu stays as it is.

### What is actually happening?
The Menu collapses.

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | MacOS |
| Browser | Firefox 65.0b6 |

---
I was trying to figure out how to keep the menu from not collapsing with 3 or more Menu Items. I noticed in the example in the Menu documentation it didn't collapse https://ant.design/components/menu/ with 3 so I copied it and started editing it to see what happened.

**Comment by itzsaga** [comment]
Debugging with a co-worker and we discovered this is only an issue on Firefox. This does not happen on Chrome.

**Comment by ztplz** [comment]
It seems to only happen on online demo websites, e.g(codesandbox, codepen).
`codepen`
![image](https://user-images.githubusercontent.com/17755202/50542688-72f88880-0bfe-11e9-8769-8f74830d8a94.png)
`local`
![image](https://user-images.githubusercontent.com/17755202/50542694-86a3ef00-0bfe-11e9-9b71-e6c6ffe2d016.png)

**Comment by ztplz** [comment]
@itzsaga  Does this happen when you run locally?

**Comment by ztplz** [comment]
@itzsaga  The reason is that the floating point calculation is wrong in `firefox`. Relate to https://bugs.chromium.org/p/chromium/issues/detail?id=360889. 
https://github.com/react-component/menu/blob/eb9a313905fbdee8da6a0be2d07fcdc4b546d8dc/src/util.js#L115  
`getBoundingClientRect` return the full precision value in `firefox`.
![image](https://user-images.githubusercontent.com/17755202/50544886-ace97f00-0c3e-11e9-9e98-bfefb9726762.png)
But in `chrome`
![image](https://user-images.githubusercontent.com/17755202/50544889-bd99f500-0c3e-11e9-9a88-04b48e21d02c.png)
https://github.com/react-component/menu/blob/eb9a313905fbdee8da6a0be2d07fcdc4b546d8dc/src/DOMWrap.jsx#L173

**Comment by itzsaga** [comment]
Yes, this happens locally but I think you've discovered why already. Thanks for the fix @ztplz 😃.
