### ISSUE TITLE
can't set ref to Drawer component

### ISSUE THREAD

**Issue by IndProgo** [ant-design/ant-design#14259]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r740k8w2oo)

### Steps to reproduce
add ref to Drawer component. View console. Warning: Function components cannot be given refs. Attempts to access this ref will fail.

### What is expected?
Drawer with ref like any react component

### What is actually happening?
ref can not be set to Drawer component

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7.0 |
| System | windows |
| Browser | any |

---
because Drawer exports with withConfigConsumer function, which doesn't forward refs

**Comment by ztplz** [comment]
Why do you want its ref?

**Comment by IndProgo** [comment]
For example, to .close() programmatically

**Comment by afc163** [comment]
You should use `visible` to control it. Don't use React ref.

**Comment by zygimantas-gylys** [comment]
I need gat drawer width after any Drawer component changes. So i can do it with ref in other components/elements. How can i get current drawer width without jquery selector?

**Comment by jwmann** [comment]
I'm also having this issue.
I need to get the container node for persisting scrolling, while disabling body scrolling.
https://github.com/willmcpo/body-scroll-lock#reactes6-with-refs

**Comment by jmtimko5** [comment]
How would one detect a click within the drawer, isn't that a prime use case for refs?

**Comment by ArtDev616** [comment]
For further visitors, here.
We can still wrap DrawerComponent inside `div`
And then pass ref to wrapped div.

Successfully implemented in that way.

**Comment by jbirch8865** [comment]
I may be missing something but the Affix component mentions pointing to a target reference if the scroll window isn't the default window.  In my case my drawer scrolls through a long list and I'd love to persist buttons while scrolling.  Not sure how I can accomplish this due to not getting the ref of the Drawer to make it the target of the Affix.

**Comment by IndProgo** [comment]
Get ref of inside container 
https://codesandbox.io/s/basic-antd484-forked-xvnm5

**Comment by CesarDav** [comment]
in my case I need to detect when scrolling inside the component

**Comment by monolithed** [comment]
@afc163 I'm using this component in the mobile version where the panel should cover the entire screen space. To achieve this, I have to subscribe to screen resize events. The event that does this is quite inaccurate, and I'd like to use ResizeObserver, but I cannot apply it because there's no 'ref' property.
