### ISSUE TITLE
Daparated Mention integration with draft.js

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#14542]
Add some warning messages when developers use `ContentState` instance from draft.js, being prepared for completely removing draft.js and immuatable.js in future.

**Comment by zombieJ** [comment]
`onChange` & `value` is already require `ContentState` converter. It's not easy to tread as string since user may use ContentState internal function like getting group.
We need to consider use new function name like `onContentChange` & `contentValue`. Or just use new component name like `Mentions`.

**Comment by afc163** [comment]
https://github.com/signavio/react-mentions `Mentions` is a good idea.

**Comment by afc163** [comment]
@kimochg Can't agree more, we are eager to remove this component in future.

**Comment by kimochg** [comment]
@afc163 IMO, Mention is essential, the problem is implementation. It could be so nice if we can refactoring with an native way to achieve the Mention's functionality. 

https://github.com/signavio/react-mentions is a good candidate. 

This one(https://github.com/youzan/zent/blob/master/packages/zent/src/mention/Mention.js) worth a try as well.

The core parts of mention is to extract the trigger(normally @), and get the caret position (for popover). Both can be implemented by a idiomatical React way. I am looking forward next version of Mention, and test it in our product!

**Comment by afc163** [comment]
closed by #16532
