### ISSUE TITLE
Menu in Header has wrong height

### ISSUE THREAD

**Issue by Kamahl19** [ant-design/ant-design#14731]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l24p5vq4jq)

### Steps to reproduce
Use `<Menu />` in `<Layout.Header />` component to create basic header navbar

### What is expected?
Ant components that are commonly used together should be working together nicely out of the box

### What is actually happening?
When you use `<Menu />` in `<Layout.Header />`, it does't work out of the box. Menu has lower height that Header thus its not vertically aligned

| Environment | Info |
|---|---|
| antd | 3.13.1 |
| React | 16.7 |
| System | MacOS |
| Browser | Chrome |

---
Easiest solution would be to write custom menu styles in the layout styles. However from what I have seen, you dont mix styles between components like this.

**Comment by ztplz** [comment]
IMO adjusting components with `style` is a very common thing. The ability of the user to handle some special case is one of the reasons we expose the `style`.

**Comment by Kamahl19** [comment]
I agree, as you said, for *special cases* there is a `style` prop. However this is one of the most common cases, to use `Menu` in the `Header`. It's even one of the examples of using the `Layout.Header`

**Comment by Kamahl19** [comment]
Usually, UI kits have their components working together out of the box. At least when it comes to basic ones. E.g. you are already doing this for the `Dropdown` and `Menu`. `Menu` gets customized classname `.ant-dropdown-menu-item` that sets `line-height` properly for the dropdown. This could be happening for the Header as well.

**Comment by ztplz** [comment]
In fact, `dropdown` is not a menu. I am worried that the force of a line-height will lead to a lower degree of customization. Because there is not only a menu in the header, you can actually put anything inside. You can think of the header as a container, and you can adjust the properties based on what you put inside.

**Comment by Kamahl19** [comment]
Dropdown is not a menu, but Menu component has custom styles to look good used in the Dropdown (customised line-height of Menu from 46px to 20px). Thats what you guys already do. And thats what I am asking for the Header component as well. Lets customize the line-height of Menu in Header from 46px to 64px to match the header.

I am not asking for changing the Header styles, only the Menu in the Header. That way, anything else in the Header will be affected, no Logo, nothing. It will only make the Menu fit in the Header out of the box.

**Comment by ztplz** [comment]
I see. Since you don't want to set the `style` in the `Header`, you can set the `style` in `menu.item`.
![image](https://user-images.githubusercontent.com/17755202/52426839-b5847d80-2b39-11e9-8af9-b3cfb92cff1a.png)

**Comment by ztplz** [comment]
Close it for now, if you have any better suggestions, feel free to reopen.

**Comment by Duder-onomy** [comment]
This should be fixed.  It is a terrible 'first experience' for this framework. 
One of the first things I do when building a website is put together the header and nav. 
Putting a `<Menu ` in the `<Layout.Header` is one of the very first things most people will do (IMO). 

When it does not work correctly, the first time, people will think the whole framework is busted and nothing works well together.  It will sour their opinion of how this framework was built.  God forbid they actually find this github issue and think that adding a `style={{ lineHeight` into their code is a good idea at all.  In fact, I believe people using AntD are trying NOT to customize and put hard coded styling into their application at all.  This will decouple the 'header' from the theme, which removes any ability to easily change the header height later. Changing this `@layout-header-height` will no longer properly change the header height. 

Look at this issue here: https://github.com/ant-design/ant-design/issues/15744
^ The person abandoned the framework after realizing they could not even put a NavBar together without customizing styles directly on the component level. 

I think AntD should:
* Fix this issue how @Kamahl19 suggests.  Ensure the menu assumes the line-height from the `@layout-header-height` variable when rendered within a `Layout.Header`. 
OR
* Add a legitimate `NavBar` component to the library so people can get around this issue.
