### ISSUE TITLE
RangePicker: A month is added to the end date when it is on the same month as the start date

### ISSUE THREAD

**Issue by Maktel** [ant-design/ant-design#15353]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/713pv80zqx)

### Steps to reproduce
1. Open RangePicker
2. Highlight date **text input** at the top of the popup and enter any date (eg. 2019-03-12)
3. Navigate with tab to the second field
4. Enter end date that's on the same month as start date (eg. 2019-03-25)
5. Close picker by pressing Enter

### What is expected?
The date range should be 2019-03-12 to 2019-**03-25**

### What is actually happening?
A month is added to the end date, so the resulting range is 2019-03-12 to 2019-**04-25**. The day of the month changes correctly, the month number is invalid.
![screenshot with result](https://i.imgur.com/VHExMHD.png)

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.4 |
| System | Linux, but irrelevant |
| Browser | irrelevant, tested on Chromium 72 and FF 65 |

---
I couldn't pinpoint the line that causes the issue – it can be very well because of some flawed logic in underlying `rc-calendar/RangeCalendar`. The cause seems to be one too many `end.clone().add(1, 'month')`, like there is in the [getShowDateFromValue](https://github.com/ant-design/ant-design/blob/master/components/date-picker/RangePicker.tsx#L30).

Also since choosing the date with mouse on a single picker pane works correctly, I suspect it has to do with combining the dates from 2 different `CalendarPart` components.

---

### More information:
If you disable date range in the reproduction to disallow picking 2019-04-25, you will not be able to close the picker and select date by pressing Enter when in the second input. You can however input the date, navigate back to the first text input and then close it.
```jsx
// try setting the range to 2019-03-07 to 2019-03-12 and closing the picker with Enter
<DatePicker.RangePicker
	defaultValue={[moment().subtract(5, "day"), moment(5, "day").subtract(5, "day")]}
	disabledDate={currentDate => currentDate.isAfter(moment())}
/>
```

If you close the popup by clicking outside of it with mouse, the end date is correctly set, as if it was not validated (?) and modified.

**Comment by afc163** [comment]
#16215
#16449
#16948

just for ref

**Comment by nocarroll** [comment]
Any update on this issue?

**Comment by nocarroll** [comment]
If anyone ends up here and is looking for a workaround, I managed to hack a solution together for our application. Explanation and code below.

### Detecting the issue
1. The bug happens when the same date is typed in both inputs in the range. It doesn't happen via click.

2. When the bug occurs, the difference between the two dates passed to the on change is *exactly* one month. The hours, minutes, seconds, milliseconds etc. are the same. Conversely, when the user intends to input a range of exactly 1 month by typing, there will be different values for hours, mins, secs, etc. when we compare the two `moment()` in the range

### Hacking the workaround
We can exploit the points above and wrap the `onChange` handler of the component to force a single day range when we detect the bug.

### 2 helper methods
```javascript
// compare the moment.toObject() and diff each value
function diff(a = {}, b = {}) {
    return Object.keys(a).reduce((result, key) => {
        if (a[key] !== b[key]) {
            result[key] = {
                a: a[key],
                b: b[key],
                // default to null for falsy / NaN etc
                diff: b[key] - a[key] || null
            };
        }
        return result;
    }, {});
}

// 
function isExactMonth(diff = {}) {
    const keys = Object.keys(diff);
    if (keys.length === 1 && keys[0] === 'months') {
        return diff['months'].diff === 1;
    } else {
        return false;
    }
}
```

### onChange wrapper fn
```javascript
function wrapOnChange([start, end], onChange) {
    const dateDiff = diff(start && start.toObject(), end && end.toObject());
	// the element the user is focused in
    const element = document.activeElement;
    const isTyping =
        element.nodeName === 'INPUT' && element.classList.contains('ant-calendar-input');
    const hasBug = isTyping && isExactMonth(dateDiff);

    // call the provided onChange handler, but pass the start date as the end date if the known bug is detected
    onChange([start, hasBug ? start : end]);
}
```

### Usage
```jsx
	<RangePicker
		onChange={dates => wrapOnChange(dates, onChange)}
	 	// ... etc
    />
```

I hope that helps!

**Comment by bruno-sartori** [comment]
Any update on this?

**Comment by lukzerom** [comment]
If this will be helpful - i noticed that this issue is caused because of differences in UNIX and local time. (in. ex we used unix timestamp in app but somehow, datepicker understood it as local. Passing a props to DatePicker component: 

` onChange={date => onChange(date?.utc(**true**.)unix())}`

👆 Fixed my issue :) 

Best regards 

Łukasz

**Comment by Madhavi96** [comment]
Any update on this? Still experiencing a month getting added to the end date.
Would appreciate a simple fix

**Comment by zombieJ** [comment]
Close since v3 is not longer in maintained.
