### ISSUE TITLE
Ordering not working when using columns and dataSource from state

### ISSUE THREAD

**Issue by italoborges** [ant-design/ant-design#15937]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0ql90nry1n)

### Steps to reproduce
- Initialize state columns and dataSource with an empty array
- Load external data containing columns and dataSource
- Add a custom sort to the first column
- Set column and dataSource to state
- Update table

### What is expected?
To show the first column with the default sort order and ordered.

### What is actually happening?
It's not ordering and also it's not activating the default sort order. You have to interact with it to apply the ordering.

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.4.1 |
| System | macOS Mojave 10.14.3 |
| Browser | Google Chrome Version 73.0.3683.86 |

**Comment by zombieJ** [comment]
It's caused that `defaultSortOrder` only works on the first time Table render. `componentDidMount` is already rended once. If you want to use async sort order. Use `sortOrder` instead.

**Comment by serdaryesilmurat** [comment]
Is `defaultSortOrder` not supposed to be kept as the active sort order after `componentDidMount` until user clicks on the sort button.

As I understand, in this case, `defaultSortOrder` does not work at all. Using `sortOrder` makes the column component controlled which is not the desired behavior here. Also, is there any callback for the sort action to be able to set the sortOrder field with the new direction afterwards, because when sortOrder is used, user action on sort button does not have any effect.

**Comment by Andrew213** [comment]
still issue
