### ISSUE TITLE
(Table)How to choose the order of the row selection column.

### ISSUE THREAD

**Issue by 1998MaxChykalo** [ant-design/ant-design#16636]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I have an ID or Index Column in table I want to see it as a first column to identify row. So it would be great to be able to configure rowSelection column order.

### What does the proposed API look like?
Adding a param for the RowSelection.
`rowSelection = {
order: 2(default 1)
}`

**Comment by zombieJ** [comment]
Not get the point. Could you help to draw some view about this requirement?

**Comment by zombieJ** [comment]
Thanks for response. It's not a common requirement. You can use css to hide the first checkbox column and add additional column with checkbox to handle that.

**Comment by mojavad** [comment]
With all due respect, I think that being able to choose the position of the rowSelection is important (potentially not for an exact column position) specifically when a user wants to choose if the selection is at the beginning of the columns or at the end...

**Comment by leviante** [comment]
+1, bringing this up.

It should be possible to choose the column index for rowSelection just like how it is done for expandIcon. Shouldn't be that hard since they are similar in a way that they are both just simple event triggers for rows.

I'll give you an example. Right now I'm using expandable prop and nesting another table for specific rows. For UX purposes, I want to show that this is a nested table by adding a "tree indicator" column.

<img width="440" alt="Screen Shot 2020-09-16 at 9 58 35 AM" src="https://user-images.githubusercontent.com/49535404/93302959-6b7a7800-f803-11ea-8281-dc62b212aa28.png">

To do this I wanted to increase the selection column's index, make it appear as second column and put the indicator column to the beginning by pushing to columns array.
But right now I have to map divs before the table to make them appear like a column, it's not as elegant as the first solution.

Is it a blocker? Not at all.
Is it a convenience? Absolutely.

**Comment by PabloAlice** [comment]
Hi everyone! +1 providing an order option for the row selection.

If any of you still have the issue where you want to move the checkbox column to the right (in other words, at the end of the table). I came up with a pretty good approach.
You have to add the following attribute to the table node.
`direction: rtl;`
Doing so, columns will get reversed leaving the checkbox column at the end.

You can go 1 step further and create a Table component on top of the Antd one and provide a property to specify that you want checkboxes at the end, and when it's true, you have to reverse the "columns" and "children" props to support both columns options.

 @zombieJ If you are interested in providing this option I'm willing to submit a PR.
Hope this helps to anyone with this requirement. This approach will *ONLY* allow moving checkboxes to the end. You cannot use this workaround to have the checkbox column next to any column you want.
[Here](https://stackoverflow.com/questions/37911165/display-table-cell-order-change-css/37911232) says you should also add direction: 'ltr' to the table cells to get it aligned properly, however I didn't need it

**Comment by Basia2B** [comment]
Still hoping for this feature in 2021, would be great to pick the column position for the checbox column.

**Comment by eschizo** [comment]
Also hoping for this feature.

**Comment by ckissane** [comment]
Lets make a  new Issue

**Comment by rashmimh** [comment]
+1

**Comment by AhmedKhalilDeveloper** [comment]
+1

**Comment by bachtdx** [comment]
+1

**Comment by sheriff0613** [comment]
+1

**Comment by Yogen-Pokhrel** [comment]
Is this issue resolved?

**Comment by rahulbansal16** [comment]
+1 
Is there any way to do this?

**Comment by elarens** [comment]
There's certainly a need for that

**Comment by mathmarqq** [comment]
Maybe this helps:

![image](https://user-images.githubusercontent.com/50305866/155197637-dc5314bc-628d-48e8-8a16-574a2c97e781.png)

https://ant.design/components/table/#components-table-demo-expand

**Comment by elarens** [comment]
I saw it too a couple of days ago (I think it was added just recently), and it's exactly what I need. Kudos to the dev team for doing such a great job! And thank you Matheus for sharing it here. Perfect solution!
