### ISSUE TITLE
CheckboxGroup 里报错

### ISSUE THREAD

**Issue by chenjingwei4518** [ant-design/ant-design#1680]
![_jm vt2 0 7c14 qji4yt04](https://cloud.githubusercontent.com/assets/14237552/15236711/f4522512-18f9-11e6-8c7a-6e1a8fb71e2f.png)
说group的key是个object，看源码发现，是直接拿的option做的key.

**Comment by yifanyou** [comment]
http://ant.design/#/components/checkbox

import { Checkbox } from 'antd';
const CheckboxGroup = Checkbox.Group;

function onChange(checkedValues) {
console.log('checked = ', checkedValues);
}

const options = [
{ label: '苹果', value: 'Apple' },
{ label: '梨', value: 'Pear' },
{ label: '橘', value: 'Orange' },
];

ReactDOM.render(
<div>
<CheckboxGroup options={options} defaultValue={['Pear']} onChange={onChange} />
</div>
, mountNode);

报错
2invariant.js:39 Uncaught Invariant Violation: findComponentRoot(..., .0.0.2.0.1.0.0.$[object Object]): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a when using tables, nesting tags like

,
, or , or using non-SVG elements in an parent. Try inspecting the child nodes of the element with React ID ``.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1645

应该是使用版本和所参考文档版本不一致的问题。
