### ISSUE TITLE
Customize modal component when programmatically invoked

### ISSUE THREAD

**Issue by byzyk** [ant-design/ant-design#17001]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In our application, we've created a couple of custom components as a wrapper on top of the `Modal`, with different styles and slightly enhanced API. We're facing a scenario where we need to programmatically invoke different types of Modals (like `Modal.error()`). Unfortunately, the is no convenient way to specify a custom component which we've created earlier.

### What does the proposed API look like?
The way I see it is that a new option can be added to `#Modal.method()` config, something like `Modal.error({ component: MyCustomErrorModal })`. Make this flag optional or even add a new method, something like `Modal.custom()`.

**Comment by zombieJ** [comment]
It's not a good place to set customize component with Modal.xxx. It's a simple function an will not provide much customize component support. You can make your own Modal static function instead.

**Comment by byzyk** [comment]
> You can make your own Modal static function instead.

Yes this is how I initially wanted to approach it, but looking at the source code I've noticed that static function doesn't re-use code of Modal's component, so making my own static function is not very trivia unless I just copy/paste `antd` source code.

That's why I thought it'd be a nice opportunity to refactor modal component a bit, make it more `DRY` and easier to customize eventually.

Perhaps I'm missing something, but is there a way to wrap programmatically invoked Modal with my own custom component?

**Comment by zombieJ** [comment]
Modal.xxx internal wrap a `ConfirmDialog` component. It contains the mainly logic and pass some computed props to sub Dialog component. It's coupling. It will get more concern about component usage instead of getting benefit. 
And for design side, Modal.xxx is aim on providing antd style modal and not wish user to much flexible about Modal component. Provides `component` is what we don't want.

In this case, yes, you may to code your static function own. You can copy full of the code or part of it or realize with own logic.

**Comment by byzyk** [comment]
Ok, thanks for getting back to me and your clarifications
