### ISSUE TITLE
Too much logic in PageHeader breadcrumb

### ISSUE THREAD

**Issue by florian-bd** [ant-design/ant-design#17046]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rwt3e)

### Steps to reproduce
Page Header with breadcrumb of length 1

### What is expected?
Breadcrumb should be shown even though there is only one level there

### What is actually happening?
Breadcrumb is automatically hidden

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.9.0 |
| System | windows |
| Browser | Chrome |

---
In the page header I feel like you don't wanna show the current level in the breadcrumb because it's the title of the PageHeader.
And for the sake of consistency I want the breadcrumb to show even if there is one level.
At least it's what I would like to do. 

Too bad I can't because it's a little bit too opinionated :)

https://github.com/ant-design/ant-design/blob/ac815621b135b4ca53ab620dab42bbb2fb0ce64b/components/page-header/index.tsx#L62

**Comment by zombieJ** [comment]
Should we reconsider this? If a beadcrumb with one route but having dropdown, it will be hidden. Maybe this display logic can provide to user to control.

cc @afc163 @chenshuai2144

**Comment by Code-Crash** [comment]
Hi @florian-bd 

When we use breadcrumbs `routes` in `PageHeader`, we are seeing a link with `#` prefixed, is that supposed to happen?, because of that it's not going on actual routes, instead it's creating a `#/<routes-path>` and not working as expected.

Do you have any solution or workaround for the same?

For Example: 

In  your [sandbox](https://codesandbox.io/s/rwt3e), if you hover on `first level` breadcrumb, you will see in left-bottom, it's showing URL with prefix `#`

Please find the attached image for the same.

![Breadcrum_issue](https://user-images.githubusercontent.com/5871757/122249688-afabbd80-cee6-11eb-8e92-aaeb77340981.png)

Thanks.
