### ISSUE TITLE
AutoComplete loading property not working

### ISSUE THREAD

**Issue by pavolgolias** [ant-design/ant-design#17432]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pavolgolias/pen/ewKOQG](https://codepen.io/pavolgolias/pen/ewKOQG)

### Steps to reproduce
1. Set AutoComplete loading property to true

### What is expected?
Loading animation should be visible.

### What is actually happening?
Nothing happens. 
Description of loading property is also missing in docs of AutoComplete component. But, there is loading property in typings, because `AutoCompleteProps` extends `AbstractSelectProps` which has `loading?: boolean;` property.

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | win 10 |
| Browser | chrome 75.0.3770.100 |

**Comment by afc163** [comment]
Your codepen is empty.

**Comment by pavolgolias** [comment]
> Your codepen is empty.

Sorry, I updated the link.

**Comment by afc163** [comment]
AutoComplete don't have `loading` prop: https://ant.design/components/auto-complete-cn/

**Comment by pavolgolias** [comment]
@afc163 Is there a possibility to add this prop to AutoComplete? I think it is a common use case when you type something into autocomplete input and possibilities are fetched from the server, so it would be nice to show users that loading is in progress.

**Comment by afc163** [comment]
```js
<AutoComplete notFoundContent={<Spin />}>
```

**Comment by pavolgolias** [comment]
Ok, thanks for the advice.

**Comment by acidoxee** [comment]
I second @pavolgolias's proposal to add a loading state to AutoComplete.

This component is especially useful when fetching data from the server based on the search value, and displaying a loading indicator to the right of the input would greatly improve UX.

With the `notFoundContent={<Spin />}` hack, it is not clear to the user whether the result of his search is still being fetched, or if there are just no matching results.

Of course the `notFoundContent` can be customized to improve UX. For instance, to either display a spinner or, when the search has completed and no results came back, display an `<Empty />` component, but it requires manual optimization for each use.

Other components such as Button and Switch already have loading indicators which are great to provide simple feedback. I think AutoComplete deserves the same treatment, all the more since, to my taste, it is much likely to wait for fetched data than Switch would be.

**Comment by jannikbuschke** [comment]
+1
Can this be reopened as a feature request? @afc163

**Comment by ammurdoch** [comment]
This makes the `notFoundContent` workaround a bit better:
```
notFoundContent={autoCompleteLoading ? <Spin /> : 'No matches'}
```

**Comment by SaburovBabur** [comment]
Might be useful:

```tsx
options: isLoading
							? [
									{
										value: 'NULL',
										disabled: true,
										label: (
											<div className='flex items-center justify-center w-full h-[100px]'>
												<Spin size='large' />
											</div>
										),
									},
							  ]
							: options,
```

**Comment by Adhav712** [comment]
> Might

This works well with debouncing
