### ISSUE TITLE
The Z-index of Modal and Dropdown is not Reasonable

### ISSUE THREAD

**Issue by litcb** [ant-design/ant-design#17484]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/antd-reproduction-template-3kbsr](https://codesandbox.io/s/antd-reproduction-template-3kbsr)

### Steps to reproduce
My Header's position is fixed ，then，I have a Dropdown（Select or DatePicker or others ），Click the Dropdown， a List shown，then，scroll the browser ,make the Dropdown List touch the Header.See,the Dropdown List will cover on the Header.Then, I find the Dropdown's z-index is 1050,So, I make the Header’s z-index 1051,The problem is resolved,But,when I open a Modal, another problem appear,the Modal's shade is coverd by the Header，the Modal's z-index is 1000 ,this is not Reasonable

### What is expected?
I think, the Main view, is covered by the Modal's shade, and , the Dropdown need under the Modal's shade too,And the Dropdown in the Modal also cover the Modal.

### What is actually happening?
see above

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | React |
| System | Mac |
| Browser | Chrome |

---
the Dropdown 's  z-index need under the Modal's ,and the Modal's Dropdown need create in de Modal's stacking context.X

**Comment by zombieJ** [comment]
Reproduce link can not open.

**Comment by litcb** [comment]
链接已经提交

**Comment by zombieJ** [comment]
Popup in antd is default append to `body` and its `z-index` higher than Layout.Header is by design. Cause html select element also at the top of it:
<img width="537" alt="屏幕快照 2019-07-08 下午8 45 17" src="https://user-images.githubusercontent.com/5378891/60811182-521e7a80-a1c1-11e9-957e-c73486b8edec.png">

You can use `getPopupContainer` to set popup container node which `z-index` under the Header if you don't want to cover the Header.

**Comment by YuvalPeretz** [comment]
Any update on that? maybe adding a `zIndex` property will do the trick
