### ISSUE TITLE
Pagination for inifinite page

### ISSUE THREAD

**Issue by rico345100** [ant-design/ant-design#17772]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Current behavior of Pagination is only works with page with total count. However, in some cases, like getting total count takes too much time because of the huge data, Paginator is not suitable.

I think this could be easily solve by removing the dots and last page, for instance:
[1] [2] [3] [4] [5] ... [31]

Removing ... and [31] will be the easiest and clear solution for me. Paginator already have quick jumper, which is jump to specified page number so this is the only thing that I needed, and this could be useful for other people, I'm sure.

### What does the proposed API look like?
<Paginator showLastPage={false} {...} />

**Comment by rico345100** [comment]
Oh, I forgot to mention, there is a one more thing that could be improve with infinite page supports. Currently when I use quick jumper, let say total page is 200, the number I input in quick jumper can't bigger than total page. So if Pagination is "infinite page" mode, allow to set any number in quick jumper(of course bigger than 0).

**Comment by zombieJ** [comment]
Hi @rico345100 , thanks for advice. But we still thinking infinite page should also provides total count since it can be calculated as cache. It's not common requirement with Pagination which may not change on current Pagination component.

But you can still use css to hide `…` & `last page button` with css of `.ant-pagination-jump-next` & `.ant-pagination-jump-next .ant-pagination-item`.
