### ISSUE TITLE
RangePicker中禁用的日期可以被预设时间范围快捷选择

### ISSUE THREAD

**Issue by xc2f** [ant-design/ant-design#18765]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-1fwjw)

### Steps to reproduce
目前有两个问题
- 禁用的日期可以被预设区间快速选择
- 比如今天是被禁用的日期，且在预设区间内，快速选择后今天将不再被禁用

### What is expected?
禁用的日期无法被选择，与手动选择日期区间的表现一致

### What is actually happening?
禁用的日期被选择

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | latest |
| System | Mojove 10.14.3 |
| Browser | chrome 74 |

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
