### ISSUE TITLE
Exception: Cannot set property matchMedia of [object Object] which has only a getter

### ISSUE THREAD

**Issue by drush** [ant-design/ant-design#18774]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gist.github.com/drush/22bbd7134f4a54d96b811b170de72d9e](https://gist.github.com/drush/22bbd7134f4a54d96b811b170de72d9e)

### Steps to reproduce
Have not been able to reproduce, although can see this exception thrown in FE crash reports across several different browsers over several weeks of app operation in production.

### What is expected?
An exception should not be thrown.

Simple tests in console make it appear that window.matchMedia is settable, but have not been able to identify if there are lockdown browser features or an extension that might be overriding this.

### What is actually happening?
`window.matchMedia = window.matchMedia || matchMediaPolyfill;`

throws an exception.  We see this in production across Chrome and Edge - all on Windows so far.  Affecting at least 10 different versions of Chrome (60-76) and 2 versions of Edge.

`Cannot set property matchMedia of [object Object] which has only a getter`

This same code appears in:
Sider, Carousel and responsiveObserve 
https://github.com/ant-design/ant-design/search?q=%22window.matchMedia %3D%22&unscoped_q=%22window.matchMedia %3D%22

It seems that in some cases, the window.matchMedia attribute cannot be set.  This may be some additional enterprise security setting, or other locked-down feature in the browser that some users have turned on.

SUGGESTED REMEDY:
- Store the matchMedia attribute or polyfill in a local variable, or a new non-reserved attribute on window, ie `window.xxMatchMedia`

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.8.4 |
| System | Windows |
| Browser | Chrome/Edge |

---
This earlier case reports the same issue but did not provide repro details: https://github.com/ant-design/ant-design/issues/15289

**Comment by drush** [comment]
@Chidi3b3r3 Please add any comments you have on this issue as I believe you have seen it as well.

**Comment by ztplz** [comment]
The properties of `window` in the browser can be changed, it is not read-only. 
![image](https://user-images.githubusercontent.com/17755202/64842625-55a50680-d635-11e9-9a81-3e79639a6e42.png)

But the `window` in your project may become read-only due to some code or configuration reasons.
e.g.   When we re-exported something
in `typescript`
![image](https://user-images.githubusercontent.com/17755202/64843000-7a4dae00-d636-11e9-8cac-1132de59ffeb.png)
transform to `javascript` via `babel`
![image](https://user-images.githubusercontent.com/17755202/64843080-b123c400-d636-11e9-8355-a077db0b99ba.png)
Test in Chrome
![image](https://user-images.githubusercontent.com/17755202/64842835-fb587580-d635-11e9-84f6-3c878efc165a.png)

The reason we have to re-assign `matchMedia` is because we need to use `polyfill` compatible with ie9.
https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia
![image](https://user-images.githubusercontent.com/17755202/64843906-e7624300-d638-11e9-8b84-c786cfc0f53f.png)
So these codes can work because it will only be reassigned in ie9

But `antd 4.0` will no longer support `ie9` and `ie10`, this hack will not be necessary.

We can force assignment by `defineProperty`.
 ``````
// when ie9
if(!window.matchMedia) {
    Object.defineProperty(window, 'matchMedia', {
     enumerable: true,
     configurable: true,
     writable: true,
    value: matchMediaPolyfill
  });
``````
