### ISSUE TITLE
multi-level drawers with different placement should not trasnform parent drawer

### ISSUE THREAD

**Issue by AncoraYhls** [ant-design/ant-design#18781]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
multi-level drawers with different placement, when child drawer opens, parent drawer won't be translated by default.

### What does the proposed API look like?
Maybe add a configuration field is possible

**Comment by afc163** [comment]
> multi-level drawers with different placement, when child drawer opens, parent drawer won't be translated by default.

Reproduce needed.

**Comment by AncoraYhls** [comment]
[sample here](https://codesandbox.io/s/antd-reproduction-template-dqfuw)

when the child drawer opens, the parent drawer is translated in the vertical direction. It looks like the disorder style.

**Comment by theoomoregbee** [comment]
@AncoraYhls fixed this by adding a `transform` style when the drawer is visible to override the auto added `transform` when a drawer on the same level is triggered. 


it was caused by this line from antdesign: ant-design/ant-design:components/drawer/index.tsx@78b7cf2#L144

they don't really support same level viewport drawer (just nested drawer) and auto add transform to any drawer on the viewport which causes the distortion. 

**Luckily** style props is added after the transform update here: ant-design/ant-design:components/drawer/index.tsx@78b7cf2#L145

which means we can override their auto generated styling.

```js
 const getDrawerStyle = () => {
    const style: React.CSSProperties = { position: 'absolute' };
    if (isDrawerVisible) {
      style.transform = undefined; // set to undefined here
    }
    return style;
  };

 ....
  <Drawer
     ...
     style={getDrawerStyle()}
 />
```

**Comment by AncoraYhls** [comment]
@theoomoregbee Thanks very much.

**Comment by darkengine** [comment]
> 

This solution is not working for ant.design 5.x.x.   :(

**Comment by zukatahara** [comment]
@darkengine thanks.

**Comment by LeraMovsesian** [comment]
@darkengine thank you!
