### ISSUE TITLE
Modal.confirm 中的按钮移除空格不生效

### ISSUE THREAD

**Issue by crazyurus** [ant-design/ant-design#18959]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/Crazy_Urus/pen/mdbvbPo](https://codepen.io/Crazy_Urus/pen/mdbvbPo)

### Steps to reproduce
点击打开按钮，出现Modal.confirm

### What is expected?
Modal.confirm中的按钮应该无空格

### What is actually happening?
Modal.confirm中的按钮有空格

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9 |
| System | Mac OS X |
| Browser | Chrome 77 |

**Comment by shaodahong** [comment]
这是因为 `ConfigProvider` 只作用到 `App` 组件中，而 `Modal` 是 insert 到 body 下面的

**Comment by crazyurus** [comment]
> 这是因为 `ConfigProvider` 只作用到 `App` 组件中，而 `Modal` 是 insert 到 body 下面的
> 
> 用开发者工具可以看到
> 
> ![image](https://user-images.githubusercontent.com/14831261/65491156-1605d680-dee1-11e9-9ff0-2cbff89ced93.png)
> 
> 使用组件形式是这样的
> 
> ![image](https://user-images.githubusercontent.com/14831261/65491245-42215780-dee1-11e9-9d23-c8b8aa324658.png)

Thanks, 有好的解决办法吗？

**Comment by shaodahong** [comment]
目前我能想到的就是换成组件




            
            
                
                    
                            
                                
                            
                            
                                Daho.Shaw
                            
                    
                        
                            
                                    邮箱：darryshaw@gmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2019年09月24日 18:27，Crazy Urus 写道： 
这是因为 ConfigProvider 只作用到 App 组件中，而 Modal 是 insert 到 body 下面的
用开发者工具可以看到

使用组件形式是这样的


Thanks, 有好的解决办法吗？

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ant-design/ant-design/issues/18959?email_source=notifications\u0026email_token=ADRE5HLURSA5SYBIAIVB4Z3QLHTR5A5CNFSM4IZKH22KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7N4ETA#issuecomment-534495820",
"url": "https://github.com/ant-design/ant-design/issues/18959?email_source=notifications\u0026email_token=ADRE5HLURSA5SYBIAIVB4Z3QLHTR5A5CNFSM4IZKH22KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7N4ETA#issuecomment-534495820",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bcyunbi** [comment]
` okText:'刪除 ',`
在自定義文字後面加上一個空白格，用奇怪的方式達成了😂
（還是不建議使用這個方式啦 > < ～～～
