### ISSUE TITLE
data-testid is not working upload component[React-Testing-Library]

### ISSUE THREAD

**Issue by Enigma10** [ant-design/ant-design#19084]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-haze-8vi94)

### Steps to reproduce
upload component doesn't support `data-test-id`. 

### What is expected?
data-testid should be supported on all components. so testing can be done easily

### What is actually happening?
I am getting the error when trying to get upload using data-testid.

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.9 |
| System | ubuntu 18.04 |
| Browser | Google Chrome 74.0.3729.131  |

**Comment by Enigma10** [comment]
@yubozhao I just want to add reproduction link is not working right now. But I know this issue bug exists on upload

**Comment by SamKirkland** [comment]
To add to this all `data-` and `aria-` attributes should be passed through (not just testid)
React has a similar pattern as of v16
https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

**Comment by SamKirkland** [comment]
Here is a short list of one's I've noticed, I'd like to do a full audit on all ant components:

[TreeSelect](https://codesandbox.io/s/mystifying-germain-jybpf) - no input exists so it would likely be best to spread this on the outside div
[TimePicker](https://codesandbox.io/s/tender-mclean-txgmw)

**Comment by stonecrafter** [comment]
This is also happening with [Drawer](https://ant.design/components/drawer/).

**Comment by DylanVann** [comment]
Attempt at fixing this for notifications is here: https://github.com/react-component/notification/pull/54

**Comment by SamKirkland** [comment]
> Attempt at fixing this for notifications is here: [react-component/notification#54](https://github.com/react-component/notification/pull/54)

If this PR gets accepted i'll pull that function out into a share spot and make a PR for Upload, Drawer, TreeSelect, and TimePicker

**Comment by afc163** [comment]
Could you try antd@next ?

**Comment by SamKirkland** [comment]
@afc163 It's still a problem on v4 (next)

**Comment by HugoLiconV** [comment]
You should be allowed to pass any data attribute to any component, I don't know why it's not the default behavior :thinking:

**Comment by defusioner** [comment]
I wonder why such important stuff is still not merged

**Comment by afc163** [comment]
@HugoLiconV @defusioner PR is welcome~

**Comment by C-Hess** [comment]
Hello everyone! I was going to work on these until I realized that almost all of the components mentioned in this issue now have data-testids passed down. That includes Drawer (@stonecrafter), TreeSelect, and TimePicker. This only leaves Notification (which has an open PR already) and the Upload component.

I'm going to open a PR to pass down the data-/aria- attributes from the Upload component. Unfortunately, I don't think I will be copying the `dataOrAriaAttributeProps` function in react-component/notification#54 to use for the Upload component because it would require changing a another repo (https://github.com/react-component/util) and is also not consistent with Ant Design's existing pattern of just using the spread operator to pass all unknown props down to the DOM.
