### ISSUE TITLE
Cannot read property 'isSelectOptGroup' of undefined

### ISSUE THREAD

**Issue by avifatal** [ant-design/ant-design#19098]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate. someone posted something but it was closed.

### Reproduction link
[http://www.I-cant-reproduce-it.com](http://www.I-cant-reproduce-it.com)

### Steps to reproduce
I am using react functional components. and I cant reproduce it with codesandbox
When I loop an array and place the `<Option` the error appears: `Cannot read property 'isSelectOptGroup' of undefined`

```
const arr  =['a','b'];
return <Select >
                  {arr.map((x) =>
                         <Option key={x} value={x}>{x}</Option>
                   )}; 
             </Select>
```
This code is working fine:
```
    return <Select>
    <Option value="a">a</Option>
    <Option value="b">b</Option>
    </Select>
```
this is how I import:

```
import { Select } from 'antd';
const Option = Select.Option;
```

### What is expected?
Render the arr in the combo

### What is actually happening?
the error from the subject is thrown

This is my package.json: https://gist.github.com/avifatal/538b91e1ed467e03fdd3dbbc8c3e9f41

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.10.1 |
| System | windows 10 pro |
| Browser | chrome latest |

**Comment by leomotta121** [comment]
I have the same problem

**Comment by haroonabbasi** [comment]
just to help out others this issue usually happens when the JSX of **Options** has issues, either having **undefined** as option

`undefined[object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object]`

or maybe having string as JSX.

**Comment by anwargul0x** [comment]
# Remove the semi-colon 
change this  
```
return <Select >
                  {arr.map((x) =>
                         <Option key={x} value={x}>{x}</Option>
                   )};  // <=== this semi-colon is the cause of this error.
             </Select>
```
in to
return <Select >
                  {arr.map((x) =>
                         <Option key={x} value={x}>{x}</Option>
                   )}
             </Select>
```

**Comment by Ito-formula** [comment]
### change the single quote ' to double quote "

the error occurs here:

`<Select defaultValue='lucy' style={{width:120}}>
                      <Option value='jack'>jack</Option>
                      <Option value='lucy'>lucy</Option>
                      <Option value='Yiminghe'>yiminghe</Option>
                  </Select>`

I solve the issue by changing the single quote to double quote:

` <Select defaultValue="lucy" style={{ width: 120 }}>
                            <Option value="jack">Jack</Option>
                            <Option value="lucy">Lucy</Option>
                            <Option value="Yiminghe">yiminghe</Option>
                        </Select>`

**Comment by flamingoodev** [comment]
Another comment, Hope this helps if you are using an older version.
Do NOT use
`const { Option } = Select.Option;`
Pls use the following:
`const Option = Select.Option;`
