### ISSUE TITLE
Integrating JSS with Ant Design to generate CSS instead of style and inline-style

### ISSUE THREAD

**Issue by amerllica** [ant-design/ant-design#19181]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Actually the Ant Design library doesn't have a good solution to generate styles. using `style` prop to set inline style is not a good path to generating styles. instead of using `style` prop I integrate JSS with Ant Design and use JSS classes for generating CSS. it is very powerful, fast and flexible to use all pseudo-classes and pseudo-elements CSS selection.

### What does the proposed API look like?
If the main maintainers approve my solution, I send a PR to integrate JSS with Ant Design and leave `Less` technology and `inline-style.`

**Comment by kavience** [comment]
I think it maybe not a good idea, why we need to write styles in js ? I think we need to focus on js when we write js or jsx file, and put style in less or sass file, through we can write style in react and ant design, we still as possible as write style in js file.

**Comment by yoyo837** [comment]
There are other projects that sync the style files from here. etc. https://github.com/NG-ZORRO/ng-zorro-antd

**Comment by amerllica** [comment]
Dear @kavience, using `scss` or `less` is a way to create styles. but not only one. Creating styles by JS that the developers call it `CSS-in-JS` or `JSS` is a trend and common way.

Actually I like to use `scss` or `less` is a project that runtime cost and SEO is so important for a business like an e-commerce store website but think about it. About all frontend developers use `Material-UI` or `Ant Design` or etc just for pannels! it means the cost of style generating and SEO is not important at all.

So why we don't use an aggregated way to create our ReactJS components? just like `Material-UI` components. why you don't like below component:

    import React from 'react';
    import PropTypes from 'prop-types';
    import withStyles from 'react-jss';
    import cs from 'classnames';
  
    const Title = ({ children, classes, className, ...rest }) => (
      <div
        className={cs(classes.root, className)}
        {...rest}
      >
        {children}
      </div>
    );
  
    Title.propTypes = {
      children: PropTypes.oneOfType([
        PropTypes.arrayOf(PropTypes.node),
        PropTypes.node,
      ]).isRequired,
      className: PropTypes.string,
      classes: PropTypes.object.isRequired,
    };
  
    Title.defaultProps = {
      className: undefined,
    };
  
    const styles = ({ typography, palette }) => ({
      root: {
        color: palette.grey[900],
        fontFamily: typography.fontFamily,
        fontVariant: 'normal',
        fontWeight: typography.fontWeightMedium,
        lineHeight: 1.4,
      },
    });
  
    export default withStyles(styles)(Title);

This is pure beauty, you have just one file and it contains _login_, _html_, _css_. What is better that it? even you can have dynamic actions on your styles.

Also, there are some issues with using `less` file. in the less file of form and some `ant design` components, it is used some special CSS selectors with high order priority and for binding new CSS, the developer should use **important** flag. By using **JSS** this issue will completely disappear.

**And Also** 🤦‍♂ `ant design` shows a way to set new styles on its components, it is terrible, see below:

     import { RangePicker } from 'antd';
    ~~
    <RangePicker style={{ color: 'red' }} />

What's your idea? using inline-style? is it a good way? 🤦‍♂

**Comment by amerllica** [comment]
Dear @yoyo837, Your link is about `Ant Design` for Angular and it is not related to my topic. thanks for your effort.

**Comment by kavience** [comment]
@amerllica You are right, I agree with you in some points, but not all, I know css in js, and I don't like  this way as following reason:
1. different write way with css or less or sass, Camel-Case have no tips in code software, and it's difficult in sometime.
2. in a js file, we write js, style, html in same js file, and make some variable in style, it's hard way to clear, maintainable code.
but it's obvious that there is many advantages such as you said , so you can make a PR when ant-design owner agree,  and I will support your work ! Thank you )))

**Comment by amerllica** [comment]
Dear @kavience, Just like you said, the `and design` owners should agree to change the style way. so after their agreement, I will make a PR. really thanks for your kind words 💘 ❤️  But dear @yesmeck didn't show reaction yet.

Also for having nice conversation I just note. there is some toolbox for writing `kebab-case` CSS in form of `camelCase`. for example, in **VSCode** and **Atom** editor, there is a simple and nice [plugin](https://github.com/ansumanshah/css-in-js) to help developers make styles easier.
And I remember my memories, I thought just like you dude,

> in a js file, we write js, style, HTML in the same js file, and make some variable in style, it's a hard way to clear, maintainable code.

Believe me, we are `ReactJS` developers, so we write codes like each other. we have the unwritten conventions for coding. so we can read each other codes easily.

**Comment by kavience** [comment]
@amerllica have a nice day!

**Comment by amerllica** [comment]
Dear @yoyo837, thanks for your attention and assigning new contributor 🌹 And dear @afc163 Please read my idea exactly. **JSS** can make ant-design more powerful. Thanks all.

**Comment by vabatta** [comment]
It would be great, this approach to self-enclosed components is similar to `.vue` components, and potentially allows complete customization and override of styles directly within a single file. This potentially remove the need to create high specificity `css selectors` to achieve customization of antd.

**Comment by flucivja** [comment]
@kavience 

against your reasons there are simple arguments :):
- you can write styles in normal way, no need to use camelCase, see e.g. https://cssinjs.org/jss-plugin-template?v=v10.0.0. There can be even written webpack plugin which can transfer css files into JSS  and it will be up to developer choose what style of writing css project will have
- there is no need to write everything in single file. You can still have separated styles from JS and HTML. JSS is just like Less (JS runtime), you can have there variables, functions whatever you want and I don't think that it will create unmaintainable code. 

btw. in my project I use JSS alongside with ant-design and I am trying to build dark theme which would change all components immediately without loading next resources. It's really painful because I am basically overriding all ant styles which defines colors in JSS manually and I am really thinking to migrate to material-ui because there is such support out of the box.

Also if there is performance concern, these days the JSS implementations can do export of static styles to static CSS resources and only dynamic styles are kept in JS runtime.

**Comment by amerllica** [comment]
I'm completely ready to make a big PR for this migration to **`JSS`** but should some moderators like @afc163 or @yesmeck or etc tell me that it will be mergeable.

I'm worried about working time. I have several experiences about closing PRs with a large amount of working time.

**Comment by tomgao365** [comment]
`JSS` is a better way to support more custom themes.
But, I don't think @afc163 will like it

**Comment by amerllica** [comment]
Dear @afc163, Please answer my question. The scale of changes is very large and I should know about `Ant Design` developers and maintainers sight about CSS generating. Do you or other maintainers have an idea about migrating to JSS?

If it's OK, I'm pretty ready to make this PR and send it.

**Comment by tomgao365** [comment]
#16911

**Comment by tnargib** [comment]
I like the way css-in-js works. I used it the first time with material-ui and it is in my opinion, really convenient. Unfamiliar and maybe an aberration for some. But convenient.
I especially like the way you can define theme providers and fully dynamic components.

Recently in my team we had a problem where we had to be able to change the theme at runtime, and even if there are some packages out there that do the job with antd less, it quickly became a pain. Feasible but not convenient obviously.

I however understand the febrility behind such a migration. This is no trivial work. Some people also just don't need css-in-js in the first place. Moreover, I still have trouble finding precise tests/benchmarks when styling components with js. It's obvious that it will bring a performance overhead. CSS can't be calculated at runtime without a cost but is it SO heavy ? I'm still divided on this.

I guess the best solution would be to do the migration and do some measurement on different devices before merging (low computer, phones etc) but again. This is not trivial. If the migration is done but not merged why not make it a fork ? Could be valuable for a lot of people I guess haha !

**Comment by hc-codersatlas** [comment]
Better to go with emotion or styled components than jss.

**Comment by amerllica** [comment]
@hc-codersatlas, it is just your opinion, integrating with JSS causes easy migration to other ReacJS UI components like `Material UI`. Also, it has some useful advantage on testing.

**Comment by PejmanNik** [comment]
I just want to mention that the react team use JSS for the new Facebook. and I think I'll help in style customization. make it more Reacty.

https://youtu.be/9JZHodNR184?t=222

**Comment by amerllica** [comment]
@PejmanNik, Thanks for sharing this awesome video, we have critical changes on web future.

**Comment by MarcusCemes** [comment]
Hi, I wanted to add my own opinion to this thread after seeing some confusion and lack of awareness around JSS in general.

## Context

> Comparing JSS and CSS is like comparing JSX and HTML.

JSS is a way of writing CSS in such a way that it is valid Javascript and therefore *embeddable* and *manipulable* within the Javascript bundle. In other words, styles are bundled *alongside* the component.

A small runtime is required to handle the conversion back into CSS and the mounting/unmounting of these styles to the document head at runtime. This usually has very little overhead, it's like comparing React to pure HTML.

## Motivation

Most people think that the goal of JSS it to avoid CSS, because "coders are coders". This is not true.
The aim is to provide the same level of control over CSS as React provides over HTML. Scope, flexibility, uniqueness (no global pollution), better selector specificity (doesn't depend on the CSS import order) and the ability to be **dynamic** 🎉.

Indeed one of the best properties of JSS is **theming**. JSS styles can be made into functions (think pure functional components)! And because it is part of the React ecosystem, you can use nested `<Provider>`s with different theme objects. The JSS framework efficiently handles the style changes.

## Personal note

I came here because of my problems trying to theme Ant Design. I tried to modify the less variables in my gatsby build, but the less loader (or the gatsby plugin) causes a V8 Out of Memory heap error, which is pretty serious. I don't want that in my build, and I don't even want to think about compiling styles in the browser for dynamic light/dark themes (I did actually try, I had to force close the tab)...

On another note, this is captured using the Devtools on the Ant Design website using the little theme colour chooser at the bottom of the page:

![image](https://user-images.githubusercontent.com/20288819/75691975-29de1180-5ca5-11ea-840b-b5a55abc1537.png)

2000ms to change the theme! And it's COMPLETELY blocking, 0 fps. That's on a 2nd-gen Ryzen 7, my laptop took 6 seconds. Suffice to say, LESS is heavy, and wasn't designed for complete browser recompilation.

There are various JSS solutions, there's a good recap [here](https://2019.stateofcss.com/technologies/css-in-js/). styled-components is very popular and trusted by some pretty major companies, it uses pure css syntax inside template literals, and VS Code plugins exist to bring real CSS highlighting. Others use a completely unique syntax. Another advantage is, no style imports for the end-user! Just import the component. The rest is automatic, and use providers to override the theme!

Personally, I prefer CSS Modules (and CSS variables to account for themes when I can afford the [lower adoption](https://caniuse.com/#feat=css-variables)) over JSS. Unfortunately, this requires a loader during the build process (that most builds tools do now support).

JSS conversion would be a fairly big project. Completely unrelated, in the meantime, why not use CSS variables to configure the theme? It's as simple as adding another line of code, and they offer [fallbacks](https://vgpena.github.io/winning-with-css-variables/) for older browsers.

**Comment by iloveip** [comment]
Hi @MarcusCemes!

How did you manage to theme Ant Design in a Gatsby project? Do you have an example I could have a look at? I'm trying to do the same. I would like to use Emotion, but haven't figured out how to do that yet.

**Comment by MarcusCemes** [comment]
@iloveip I wasn't able to get Ant Design working with a different theme, in the end, I used Ant Design alongside a lot of custom UI components. Your best bet is compiling the less files yourself (with gulp or some other build tool), overriding ant-designs classes or making your own versions of the components.

Also, take a look at TailwindCSS, it's a pleasure to work with.

**Comment by tomgao365** [comment]
It will be a big change

**Comment by amerllica** [comment]
Dear @tomgao365. the `ant design` is a library. you can use your own CSS build system in your project. any technologies. so yes, it could be used alongside Less, JSS, SCSS ane etc.

**Comment by amerllica** [comment]
@yesmeck @afc163, I see this issue not gonna be resolved, I close it now and open another issue, with some different description.

**Comment by iloveip** [comment]
Hi @MarcusCemes,

Thank you for your reply. I decided to try CSS Modules with LESS. But I can't override ant design classes inside a module. If I simply nest them inside a top level classname, they also get localized by CSS Modules and are not effected by my css. Here is a full explanation of this problem https://github.com/css-modules/css-modules/issues/336#issue-569486369.

Do you any idea how I can fix that?

**Comment by MarcusCemes** [comment]
@iloveip I replied to the topic that you mentioned. Short answer, you need the `:global(...)` selector to leave the class name as it is, as Ant Design classes are not scoped/unique.

**Comment by veeramarni** [comment]
So any movement towards JSS direction?

**Comment by Ethorsen** [comment]
Its unfortunate that ant-design theming cannot be easily integrated in JSS.  I was looking forward to experiment with this library on a smaller and personal project. But after all these years, I don't want to go back to sass.

**Comment by abenhamdine** [comment]
css in js is planned in ant-design 5 and work is currently in progress (see PR merged in next branch last few weeks)
see  https://github.com/ant-design/ant-design/issues/33862 for the announcement
the task list is here : https://github.com/ant-design/ant-design/issues/34087  

their jss library is here : https://github.com/ant-design/cssinjs
