### ISSUE TITLE
Dynamic Form Items Delete Bug

### ISSUE THREAD

**Issue by deepansh946** [ant-design/ant-design#19355]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-varahamihira-22ynj)

### Steps to reproduce
* Add two or three records
* Add data for each record separately (drop-down selection)
* Delete any non-last data
* the one will want to delete is still there

### What is expected?
The list should delete the desired element.

### What is actually happening?
The other items of the list are affecting

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.8.6 |
| System | Ubuntu |
| Browser | Google Chrome Version 77.0.3865.120 (Official Build) (64-bit) |

---
This is mentioned in one of the Stack Overflow questions but no correct answer is given. The accepted answer to the question is also wrong. Stack Overflow Link: https://stackoverflow.com/questions/51578026/dynamic-form-additions-and-deletions-data-with-new-ui-is-not-new-of-antd-with

**Comment by ahmadster** [comment]
This is painful. After much time invested building on AntD's Form now I have to completely abandon because of this bug. Is there any hope this can be looked at or should I move on?

**Comment by zombieJ** [comment]
v3 do not support to operate list directly. Please use key for mapping instead.

https://3x.ant.design/components/form/#components-form-demo-dynamic-form-item

**Comment by filev-svt** [comment]
The bug is still present in 4.6.4, the issue should definitely be reopened. For me, this happens when the underlying Form.List items are nested inside a component and the remove method is sent as a prop - the problem is, however, the same, deleting a non-last item will cause the bug and the other items won't get deleted. 

At least the official documentation should have some kind of a warning and a recommended approach.
