### ISSUE TITLE
No error catch in component Upload transformFile method

### ISSUE THREAD

**Issue by fengma1992** [ant-design/ant-design#19372]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/fengma1992/pen/abbJwyo?editors=0011](https://codepen.io/fengma1992/pen/abbJwyo?editors=0011)

### Steps to reproduce
just select a file to upload

### What is expected?
catch the error that transformFile function throw

### What is actually happening?
no error catch

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.8.6 |
| System | Mac OS X 10.15 |
| Browser | Chrome Version 77.0.3865.120 (Official Build) (64-bit) |

---
ridiculous bug

**Comment by hahmadia** [comment]
Seems that in any function you try to do a `throw new Error('You can\'t catch me')`, it will not catch it unless you do a 
```
    try {
      throw new Error('You can\'t catch me');
    } 
    catch (e){
      console.error(e.name + ': ' + e.message);
    }
```
It doesn't seem specific to `transformFile`. I'm not sure if I have misunderstood your problem because when I do a catch, it seems to be working. Is there anywhere in the AntD library that is catching the error like you expect it too?
