### ISSUE TITLE
Tooltip 组件隐藏后，希望能删除 DOM 节点

### ISSUE THREAD

**Issue by hudidit** [ant-design/ant-design#19536]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

## 现状
Tooltip 展示时会向 DOM 中插入一个 div 节点，以及一些子节点。但是隐藏时并没有删除这个节点。当页面中有很多个 Tooltip 实例时，每展示一个就会向 DOM 中插入一组节点，越来越多。
如图所示：
![](https://user-images.githubusercontent.com/2347723/68082976-3de04680-fe5e-11e9-9448-2a78379b66ef.png)

## 预期
希望 Tooltip 在隐藏后，能够删除对应的 DOM 节点。或者，提供一个配置项，支持用户选择是否要清理 DOM 节点。
好处：
1. 页面 DOM 结构更干净。
2. 尽管多数时候可能影响不大，但是回收 DOM 节点，减少内存占用，是一种比较常见的最佳实践。

### What does the proposed API look like?
参考 Ant Modal 组件的 `destroyOnClose`，可以增加一个 `destroyOnHide` 参数。
e.g. 
```jsx
<Tooltip title="hover text" destroyOnHide>text</Tooltip>
```

**Comment by afc163** [comment]
有一个 `destroyTooltipOnHide`

https://github.com/react-component/tooltip

**Comment by Arthur-Conan-Dog** [comment]
> 有一个 `destroyTooltipOnHide`
> 
> https://github.com/react-component/tooltip

Hi there,

I think `destroyTooltipOnHide` does not quite solve @hudidit 's problem, since only the tooltip div inside will be removed after mouse leave. eg:

Hovering: 
```html
<div style="position: absolute; top: 0px; left: 0px; width: 100%;">
  <div>
    <div
      class="rc-tooltip rc-tooltip-placement-right "
      style="left: 737px; top: 28px;"
    >
      <div class="rc-tooltip-content">
        <div class="rc-tooltip-arrow" />
        <div class="rc-tooltip-inner" role="tooltip">
          <span>powered by rc-tooltip</span>
        </div>
      </div>
    </div>
  </div>
</div>
```

Mouse leave:
```html
<div style="position: absolute; top: 0px; left: 0px; width: 100%;">
  <div></div>
</div>
```

This strange div container stays.

After a little deep dive, I found that this behavior is caused by the usage of `rc-trigger`, which gives a default div container for Portal component.

Check this: https://github.com/react-component/trigger/blob/2.2.2/src/index.js#L585
and https://github.com/react-component/trigger/blob/2.2.2/src/index.js#L394

Also checked the lastest working on version `4.x.x-alpha` of `rc-trigger`, [this problem still exists](https://github.com/react-component/trigger/blob/master/src/index.tsx#L506).

It's better if we could also clean up the appended child, say during `componentWillUnmount`.

**Comment by yoyo837** [comment]
I think you are right.

**Comment by shaodahong** [comment]
thanks, PortalWrapper has `autoDestroy` prop, but we didn't use it, maybe we can add `autoDestroy` prop

https://github.com/react-component/util/blob/fb03ea5db96a7c6ef58387f0df9c181ecc0fcc05/src/PortalWrapper.js#L128

**Comment by Kermit-Xuan** [comment]
[#178](https://github.com/react-component/trigger/pull/178) 给`trigger`添加了`autoDestroy`属性。

**Comment by Kermit-Xuan** [comment]
@afc163 看看tooltip的那个pr，没问题就可以合了。

**Comment by zombieJ** [comment]
感觉应该改进 `destroyTooltipOnHide`，而不是添加一个  `autoDestroy`。

**Comment by Kermit-Xuan** [comment]
这样可以的，主要加是为了做兼容，你说的这种方法更好。

**Comment by zombieJ** [comment]
可以加到 minor version 里

**Comment by Kermit-Xuan** [comment]
@hudidit 最终没有增加`autoDestroy`, 而是在原来的`destroyTooltipOnHide` 增加了`{ keepParent?: boolean }`类型，同时兼容原来的`boolean`类型，只有当`keepParent`等于`false`才会删除父元素，后期没有问题后会可能会直接取消兼容直接删除父元素。

**Comment by afc163** [comment]
antd 还要升级一下。

**Comment by yoyo837** [comment]
需要reopen吗？
