### ISSUE TITLE
Get Initial Value

### ISSUE THREAD

**Issue by tushariscoolster** [ant-design/ant-design#19680]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to check if the form value has changed or not. It will be good if there is a method which gives all initial value and then I can diff to check form value has changed or not.

### What does the proposed API look like?
this.props.form.getInitialValue()

**Comment by keithort** [comment]
This can be accomplished with existing APIs. Each input type also has an `onChange` event as well. 
```
const initialValues = {
 firstName: "Keith"
};

const MyForm = props => {
 const { getFieldDecorator } = props.form;
 return (
  <Form> 
   <Form.Item label="First Name">
     {getFieldDecorator("firstName", {initialValue: initialValues.firstName})(<Input />)}
   </Form.Item>
  </Form>
 )
};

const WrappedHorizontalLoginForm = Form.create({
 onValuesChange: (props, changedFields, allFields) => {
   let fieldName = Object.keys(changedFields)[0];
   if (initialValues[fieldName] !== changedFields[fieldName]) {
    console.log('Value changed from default ', fieldName, changedFields[fieldName]);
   } else {
     console.log('Value not changed from default', fieldName)
   }
 }
})(MyForm);
```

**Comment by afc163** [comment]
intialValue is something you already know when you give it to antd's Form.

**Comment by 0x00000001A** [comment]
`initialValue` is something I already know - that's true.
But in the same time, if I already know `initialValue` - I can manage the state (using the `value` and `onChange` props) by myself. But the one of the reasons, why we use the antd forms - it easy to use - just pass the initialValue and you don't need to manage the state by yourself, just specify the names and thats all.

Based on above, I have to say - you're not right at all.
And here is our usecase for you:

We need to validate the input value for uniqueness using our api. 
Let's say, the initial value was the "test'.
If I change the value to "test" - the request will be send, because the field is changed.
But in the same time, if I'll change the value  back to test - request will be send again and it's not the right behaviour.
To solve this problem, I need to know the initialValue and compare it to the actual value.
If you don't wont to provide us a way to access the field initial value, then you have to provide some way to disable validation triggering for specific field, if field value was not changed or was changed back to it's original value.
