### ISSUE TITLE
[4.0] Table expland padding style

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#19895]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/table-cn/#components-table-demo-expand](https://next.ant.design/components/table-cn/#components-table-demo-expand)

### 4.0
![image](https://user-images.githubusercontent.com/14831261/69430492-b0af5400-0d70-11ea-923e-1d0121da3f8e.png)

### 3.0
![image](https://user-images.githubusercontent.com/14831261/69430503-b73dcb80-0d70-11ea-90fe-31e67b9d14f3.png)

### What is expected?
has padding

### What is actually happening?
no padding

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.9 |
| React | 16.3 |
| System | windows 10 |
| Browser | chrome 75.0.3770.100  |

**Comment by shaodahong** [comment]
and with scroll weird

![4](https://user-images.githubusercontent.com/14831261/69431355-8a8ab380-0d72-11ea-8a9f-0dad899a54a2.gif)

**Comment by zombieJ** [comment]
It's by design. Expanded Row will always 100% with table and not follow fixed:

![图片](https://user-images.githubusercontent.com/5378891/71545282-68650080-29c4-11ea-9cd0-0893d20acaf6.gif)
![Kapture 2019-10-24 at 11 33 51](https://user-images.githubusercontent.com/5378891/71545283-68fd9700-29c4-11ea-9ae9-04647b81ac8a.gif)
![Kapture 2019-10-24 at 11 35 56](https://user-images.githubusercontent.com/5378891/71545284-68fd9700-29c4-11ea-8709-1ece85c35fd9.gif)
