### ISSUE TITLE
"Minimum" prop in Form.List

### ISSUE THREAD

**Issue by piyushk96** [ant-design/ant-design#20497]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`Minimum` prop will specify minimum number of fields in `Form.List`(antd 4) that will be automatically added and you can't remove children fields beyond that limit

### What does the proposed API look like?
```
<Form.List name="test" min={2}>
  {(fields, {add, remove}) => (
    <Input type="text />
    <Button onClick={add}> </Button>
    <Button onClick={remove}>-</Button>
  )}
</Form.List>
```
This will show minimum two input fields with an option to add more. But you can't remove fields beyond 2

**Comment by zombieJ** [comment]
Re-considered. This can be controlled by hiding `remove` button in user side. Which is not must have in List.

**Comment by piyushk96** [comment]
> Re-considered. This can be controlled by hiding `remove` button in user side. Which is not must have in List.
True, we can hide delete button from user side but how can we initially add fields in list so that 2 input fields (in above case) will show on render

**Comment by zombieJ** [comment]
<Form initialValue={...} />

**Comment by dobrynin** [comment]
+1 would really appreciate this! Personally I think that having the "minimum" prop as an API would be nicer than having to prepare your initialValues (this would have to be done imperatively and separate from the UI which it controls, rather than declaratively in React)

Secondly, we have the use case of nested Lists. Yes we could say 
`initialValues = {list1: [{list2: []}]}` But what about if a user dynamically creates another item in list1? How then can we initialize the second list2 (inside of the second item in list1) w/ an initial length of one? It would be easy if there was a minimum prop.

Please let me know if there is some other way that I have not considered.

**Comment by piyushk96** [comment]
@dobrynin I also had the same use case of nested lists. I solved it by using a hack by just pushing an empty object(or object with default values of sublist) into list1 on every call of `add()` of list1 using `formRef.setFieldsValue`.

**Comment by piyushk96** [comment]
But it would be great if `minimum` prop is supported in API

**Comment by dobrynin** [comment]
I thought of doing the same thing @piyushk96, but ended up doing a different hack.

```
const customFirstKeyHack = { name: 0, key: 999, fieldKey: 999 };

{(fields, { add, remove }) => (
            <>
              {fields.length === 0 ? (
                <div key={customFirstKeyHack.key}>
                  ...
                </div>
              ) : (
                fields.map((field, index) => (
                  <div key={field.key}>
                    ...
                  </div>
                ))
              )}
            </>
          )}
```

**Comment by dobrynin** [comment]
@zombieJ would you be able to comment if this is something that can be considered? Thank you!

**Comment by zombieJ** [comment]
Maybe we can add `rules` for length only on Form.List. But List component do not have self style. Need still dig in. Please feel free to comment more thought about this.

**Comment by dobrynin** [comment]
Hi @zombieJ, would like to bring attention back to this. I see that rc-field-form has added support for `rules` w/ `List`. I still think that the solution proposed above is superior so that we can initialize lists w/ the proper length rather than only being able to validate when the user is submitting data.

We have been using this patch which has been working (recently broke while updating to newest antd, will have to investigate)

```js
  React.useEffect(() => {
    if (minimum && !context.getFieldValue(prefixName || [])) {
      context.setFields([{name: prefixName, value: new Array(minimum).fill({})}])
    }
  }, [])
```

**Comment by zombieJ** [comment]
@dobrynin , could you help to create a new issue for this?

**Comment by dharanidhanapalan** [comment]
it would be grateful if we have min prop on form list? or any other solution to add length to form list?

**Comment by McCloudA** [comment]
Would be really awesome to have this API `min={2}` or something. I'd love to have this!

**Comment by rockro7** [comment]
Form.List has prop initialValue. With that you can solve even @dobrynin 's problem
