### ISSUE TITLE
When Popover has a title prop of Input with autoFocus property, the page will scroll to the top  when first time Popover's title render

### ISSUE THREAD

**Issue by masonzz** [ant-design/ant-design#20575]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-dirac-efrqs?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Click the button at the bottom of the page
2. The page will scroll to the top

### What is expected?
The page won't sroll to the top

### What is actually happening?
The page scroll to the top

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 16.12.0 |
| System | MacOS 10.14.3 |
| Browser | Chrome 78.0.3904.108 |

**Comment by zombieJ** [comment]
When the first popup created, the popup box position is at the top of window since we can not get popup size before created. But browser will scroll to view when element focused.

So you can set popup style to `position: fixed` let popover component always in the screen to avoid shaking: https://codesandbox.io/s/popover-he-input-with-autofocus-shiyichanggundong-8lohn

**Comment by pkyeck** [comment]
The `position: fixed` hack only removes the jump to the top of the page but if you start scrolling after the popover is open, it is "fixed" to that position. So not really a solution :(

**Comment by yzwxk** [comment]
Set `position: fixed` after first time render, the Input can't autofocus.
Set focus manually works for me!
More ref to: 
Set focus manually https://github.com/react-bootstrap/react-bootstrap/issues/2614
position fixed in Safari: https://github.com/mui/material-ui/issues/16740
