### ISSUE TITLE
Card Component is not mobile reponsive?

### ISSUE THREAD

**Issue by roeljohn** [ant-design/ant-design#20613]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/8347743/71674842-506ff100-2db7-11ea-9f99-25510725dcc1.png)

### What problem does this feature solve?
mobile friendly? is there a way I can responsive/break-point the card?

### What does the proposed API look like?
      <Col span={16, 8}> // not sure lol
        <Card title="Card title" bordered={false}>
          Card content
        </Card>
      </Col>

**Comment by zachguo** [comment]
Please check the documentation. Responsiveness is handled by [`Grid`](https://ant.design/components/grid/).

**Comment by roeljohn** [comment]
thanks @zachguo

**Comment by dwwoelfel** [comment]
@zachguo How should one handle responsiveness in [Card.Grid](https://ant.design/components/card/#components-card-demo-grid-card)?

Seems like it should have a `column` property similar to the `Descriptions` component https://ant.design/components/descriptions/#components-descriptions-demo-responsive

**Comment by zachguo** [comment]
Not `Card.Grid` but [`Grid`](https://ant.design/components/grid/), namely `Row` and `Col`.

**Comment by zachguo** [comment]
```
<Row>
  <Col>
    <Card>
      <Row>
        <Col>
        ...
        </Col>
      </Row>
    </Card>
  </Col>
</Row>
```

**Comment by dwwoelfel** [comment]
@zachguo 

How do you handle responsiveness in `Card.Grid`, though?

Here's a codesandbox that illustrates the problem: https://codesandbox.io/s/antdesign-dpmk6

If the window gets too small, the items shrink instead of wrapping to a new column:

![image](https://user-images.githubusercontent.com/476818/76133416-ea793300-5fcc-11ea-9868-ebab9b0693cb.png)

If you set a min-width on the items, then you get odd whitespace ln the items.

![image](https://user-images.githubusercontent.com/476818/76133435-0250b700-5fcd-11ea-8f37-eb9966f05eba.png)

**Comment by zachguo** [comment]
Sorry, I never used `Card.Grid`.

**Comment by Alexhia47** [comment]
como puedo hacerla responsive para que vaya de 4 cards en horizontal a una sola?
