### ISSUE TITLE
Typography Title does not support the h5 and h6

### ISSUE THREAD

**Issue by YourBoB** [ant-design/ant-design#20710]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Make the Typography Title support h5 and h6

### What does the proposed API look like?
Make the Typography Title support h5 and h6

**Comment by zombieJ** [comment]
That's by design. ref: https://github.com/ant-design/ant-design/pull/14250

**Comment by keithort** [comment]
@zombieJ Can you link to the specific comment where the decision was made? It seems arbitrary to only support H1, H2, H3, and H4 but not H5 and H6.

**Comment by dmossie** [comment]
> It seems arbitrary to only support H1, H2, H3, and H4 but not H5 and H6.

I agree. Why would h5 and h6 not be supported?

**Comment by manquer** [comment]
@zombieJ The documentation at https://ant.design/components/typography/ still mentions h5 . This could be updated.

**Comment by zombieJ** [comment]
h5 is new added to sync design with [yuque](https://www.yuque.com/) implement.

**Comment by monolithed** [comment]
@zombieJ, What is the reason for not supporting the standard h6 heading? Already, for half of the components, I have to create wrappers, but for the title, where h6 exists not only in other design systems but also in the [HTML specification](https://html.spec.whatwg.org/#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements). If, for personal reasons, you don't want to add this property, please extend the API so that we can add this attribute through theming, so that people don't create another wrapper around your library.
