### ISSUE TITLE
Module not found: Can't resolve '@ant-design/compatible'

### ISSUE THREAD

**Issue by mayinghan** [ant-design/ant-design#20833]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ufcsa/airpick-new/tree/antdv4](https://github.com/ufcsa/airpick-new/tree/antdv4)

### Steps to reproduce
Clone the repo and run npm start

### What is expected?
The app should start in localhost:3000

### What is actually happening?
Failed to compile. Module not found: Can't resolve '@ant-design/compatible' in '/Users/yinghanma/projects/ufcsa/airpick-new/client/component/Forms'

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | React 16.12 |
| System | Mac os |
| Browser | Chrome latest |

---
I just updated to 4.0 and used the v3 to v4 upgrade scaffold provided officially. But when I update to antd 4.0, i dont have @ant-desigb.compatible directory under my node_modules

**Comment by andriyklym** [comment]
How you fixed it?

**Comment by doantientai** [comment]
@mayinghan I am facing the same problem. How did you fix it?

**Comment by doantientai** [comment]
Ok, so I found it. The ant-design/compatible doesn't go with antd4, we need to install it independently.
`yarn add @ant-design/compatible
`

**Comment by VigneshPT** [comment]
> Ok, so I found it. The ant-design/compatible doesn't go with antd4, we need to install it independently.
> `yarn add @ant-design/compatible `

This should have been mentioned in the [Migration guide](https://ant.design/docs/react/migration-v4).

**Comment by sandy-74** [comment]
hi , I got this err after i use the yarn add @ant-design/compatible

PS D:\Video-Chat-main> yarn add @ant-design/icons@4.0.0
yarn add v1.17.3
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning react-scripts > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning react-scripts > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+.
Upgrade to chokidar 3 with 15x less dependencies.
warning react-scripts > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi@15.1.1: Switch to 'npm install joi'
warning react-scripts > workbox-webpack-plugin > workbox-build > rollup-plugin-babel@4.4.0: This
package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
warning react-scripts > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning react-scripts > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-scripts > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/bourne@1.3.2:
This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning react-scripts > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-scripts > workbox-webpack-plugin > workbox-build > strip-comments > babel-plugin-transform-object-rest-spread > babel-runtime > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning react-scripts > jest-circus > jest-runner > jest-config > jest-environment-jsdom > jsdom
> request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > jest-circus > jest-runner > jest-config > jest-environment-jsdom > jsdom
> request > har-validator@5.1.5: this library is no longer supported
warning react-scripts > jest-circus > jest-runner > jest-config > jest-environment-jsdom > jsdom
> request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/date-fns/-/date-fns-2.21.1.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "D:\\Video-Chat-main\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
PS D:\Video-Chat-main>

**Comment by sandy-74** [comment]
is there have any extensions for automatically install the packages and dependencies in my clone app?

**Comment by sandy-74** [comment]
> > Ok, so I found it. The ant-design/compatible doesn't go with antd4, we need to install it independently.
> > `yarn add @ant-design/compatible `
> 
> This should have been mentioned in the [Migration guide](https://ant.design/docs/react/migration-v4).

![image](https://user-images.githubusercontent.com/54904486/116538562-50c5c100-a905-11eb-8564-dec496d9f60a.png)
