### ISSUE TITLE
InputNumber formater issue

### ISSUE THREAD

**Issue by stanlaktionov** [ant-design/ant-design#21126]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e6ux?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
I need to use InputNumber for ability to display/edit currency based on user locale. 
1. Default value is empty
2. Add parser property, that updates value, based on user locale 

### What is expected?
User edit integer part, when typing digits into input
OR
formater is applied onBlur instead of onChange

### What is actually happening?
Caret jumps to the end of string, user edits only fractional part

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | react 16.9.0 |
| System | Windows 10 |
| Browser | any |

**Comment by zombieJ** [comment]
InputNumber internal has the logic of selection record and restore. We can not know the accurate logic of selection cursor should use since the formatted string do not provides new cursor position should place. We met lots of format requirement like:
`3,000` & `3.000` & `3'000` & `3:000` & `3#0000` & `三千整`

Something selection cursor should place before the symbol and sometime after. There have not a unique rule for the format.

You can handle selection self with `onChange` event if current logic not match your requirement.

ref: https://github.com/react-component/input-number/blob/89fd773bbf7bd300c21b9cf3d5fa997e5176bcd0/src/index.js#L474
