### ISSUE TITLE
Media Steps

### ISSUE THREAD

**Issue by TannerHolladay** [ant-design/ant-design#21294]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-9h47t?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Shrink the screen size and the step size changes to vertical

### What is expected?
Steps should stay horizontal when assigned horizontal

### What is actually happening?
Step direction changes to vertical when the screen size shrinks

| Environment | Info |
|---|---|
| antd | 3.26.9 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome 80 |

**Comment by afc163** [comment]
It is by designed.

**Comment by jasan-s** [comment]
Is there no way to force it to remain horizontal direction?

**Comment by techwizard-prasad** [comment]
Facing the same issue. Can someone suggest a workaround at least?

**Comment by wemiced** [comment]
Hi @techwizard-prasad 

I found a workaround to override vertical direction. You can edit style of the Steps component with addind a className with `flex-direction: row` like this : 
https://codesandbox.io/s/antd-reproduction-template-forked-mkqg2  

It worked for me

**Comment by peerjuettner** [comment]
While I appreciate the comment @wemiced, your solution leaves the line in the vertical state:
![image](https://user-images.githubusercontent.com/18301629/101168998-9626e080-363c-11eb-9c15-c40826fab57b.png)
Not sure why the change to vertical is "by design". I would get it changing if the `direction` prop isn't passed, but still forcing the change even with the prop is annoying. Please consider changing this @afc163

**Comment by mienaikoe** [comment]
I understand that the switch is by design. There's no practical way to render all that content in such a small space. 

However, the switch to vertical is not elegant or graceful, as you can see in the attached screenshot. The class is still ant-steps-horizontal, so the padding is all over the place.

![Screen Shot 2021-02-20 at 6 56 33 PM](https://user-images.githubusercontent.com/3875239/108611549-76869500-73ad-11eb-9775-ddaaa42e9814.png)

**Comment by StringMatcher** [comment]
As long as the direction property is not set, it is totally fine to leave the decision how to render to the antd algorithm, but if the component-API user decides to set the direction **explicitly** to "horizontal" and the component still renders "vertically" it actually makes it impossible to ever render horizontally on small devices without hacks.

Suggestion:

- **no direction specified:** antd decides on the direction depending on the device size
- **vertical direction specified:** antd respects the vertical direction and renders accordingly
- **horizontal direction specified:** antd respects the horizontal direction and renders accordingly

**Comment by CSD3V** [comment]
any news about this?

**Comment by HassnaaAyman** [comment]
I have found a solution as a workaround :
add to this class 
.ant-steps-vertical > .ant-steps-item:not(:last-child) > .ant-steps-item-container > .ant-steps-item-tail

these styles 
    transform: rotate(90deg) scaleX(-1);
    top: -30px;
    left: 44px;

**Comment by EddyPBR** [comment]
Now we can pass the following property:

`<Steps responsive={false} />`

[Check here](https://ant.design/components/steps/#API)

**Comment by sdannyzaidi** [comment]
As @EddyPBR said to make the steps to not change the orientation we can set the responsive property in steps to false.
`<Steps responsive={false} />`
Doing so just makes sure that the element does not change its orientation as the screen size changes, however it does not make it responsive, as in it does not change its width as the screen size shrinks. In order to make the element responsive in actual sense you can overwrite the following ANTD class as I have done using tailwind css.
`.ant-steps .ant-steps-item {
	@apply max-xs:!w-[6rem] max-sm:!w-[6.5rem];
}`
