### ISSUE TITLE
DateRange: Picker panel for the end date should automatically switch to the date later then start date

### ISSUE THREAD

**Issue by omniteq** [ant-design/ant-design#21787]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reverent-jepsen-2ucf6)

### Steps to reproduce
Select a later date like 2022. The picker panel gets back to the default date so you have to manually navigate to ​2022 for the end date.

### What is expected?
The picker panel for the end date should automatically switch to the same month as the ​start date.

### What is actually happening?
The end date picker panel gets back to the default month.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12 |
| System | MacOS 10.13.6 (17G7024) |
| Browser | Version 80.0.3987.122 |

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
