### ISSUE TITLE
Multiple repeated renders when one update is trigger on customized form component(4.0)

### ISSUE THREAD

**Issue by xuzhaogit** [ant-design/ant-design#21850]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-customized-form-controls](https://ant.design/components/form/#components-form-demo-customized-form-controls)

### Steps to reproduce
1.使用4.0版本的自定义表单控件时，每次修改表单会导致自定义组件重复渲染3次（使用官网提供的demo），而3.x版本只会渲染一次

### What is expected?
rendered once 

### What is actually happening?
rendered three times

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | react 16.13.0 |
| System | macOs 10.14.6 |
| Browser |  chrome 80.0.3987.122 |

**Comment by xuzhaogit** [comment]
https://codesandbox.io/s/antd-reproduction-template-flm4o

**Comment by zombieJ** [comment]
It's not a bug. New Form support renderProps which provides the `meta` info contains `validating`. So it render with different status:

1. value: newValue, validating: false
2. value: newValue, validating: true
3. value: newValue, validating: false

It's safe since re-render only affect related field.
