### ISSUE TITLE
RangePicker Unexpected onCalendarChange

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#22351]
### Reproduce Link

https://codesandbox.io/s/range-picker-ant-design-demo-wi0ks

### Steps to reproduce

1. Open RangePicker
2. Select start date
3. Blur in outside

### Expected Behavior

console output:

```
onOpenChange true
onCalendarChange [Moment, null]
onOpenChange false
onCalendarChange [null, null]
```

or

```
onOpenChange true
onCalendarChange [Moment, null]
onOpenChange false
onCalendarChange null
```

### Actual Behavior

console output:

```
onOpenChange true
onCalendarChange [Moment, null]
onOpenChange false
onCalendarChange [Moment, null]
```

**Comment by afc163** [comment]
- [ ] 另外，demo 中点开 Picker 后直接 blur 没做任何变化也会触发 `onCalendarChange`。

**Comment by afc163** [comment]
ref #22349

**Comment by afc163** [comment]
@zombieJ

**Comment by daud9** [comment]
Will filesystem cache work here

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
