### ISSUE TITLE
RangePicker do not jump to specified calendar when switch pickers

### ISSUE THREAD

**Issue by morenyang** [ant-design/ant-design#22471]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/#components-date-picker-demo-range-picker](https://ant.design/components/date-picker/#components-date-picker-demo-range-picker)

### Steps to reproduce
1. select two dates
2. select the first picker and jump to several months before
3. click the second picker, the calendar does not change

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15653996/77232486-338bd280-6bdc-11ea-8671-59aa9cc1509b.gif)

### What is expected?
The calendar should be the month in the second picker

### What is actually happening?
The calendar does not change

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by henriquezolini** [comment]
Same problem here.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
