### ISSUE TITLE
Table CSS is applied to Descriptions when inside expanded row

### ISSUE THREAD

**Issue by FoxxMD** [ant-design/ant-design#22577]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/expandable-row-ant-design-demo-exy6h)

### Steps to reproduce
Render a `<Descriptions>` component (and children) inside the expanded row of a table

### What is expected?
Descriptions and Descriptions.Item only have their own CSS applied, as in any other scenario

### What is actually happening?
`<Table/>` component CSS for padding, borders, etc. is applied

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by keithort** [comment]
This is how CSS works. Any table and td elements within the Table component will inherit those styles. I think in the migration to 4, the team got a little carried away with removing some of the classnames.

The issue is that the styles don't have an 'ant' class to target. They start off `.ant-table table`. The styles should be reworked a little. The top level should be `.ant-table-container` and `.ant-table` should be applied to the `table` element itself. Then the direct children of `.ant-table` can be styled. 
```css
.ant-table > thead > tr > th {}
.ant-table > tbody > tr > td {}
```

I think those fixes would remedy your issue.
