### ISSUE TITLE
Menu.Item support icon

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#23392]
```jsx
<Menu>
  <Menu.Item icon={<HomeOutlined />}>menu</Menu.Item>
  <Menu.Item icon={<HomeOutlined />}>menu</Menu.Item>
  <Menu.Item icon={<HomeOutlined />}>menu</Menu.Item>
</Menu>
```

**Comment by MengZhaoFly** [comment]
Hi,
if without the icon props, we want the feature，code may be as：
```js
<Menu.Item key="key">
   <HomeOutlined />
   Navigation One
</Menu.Item>
```
i see Menu.Item is based on react-component/menu, and it [support itemIcon props](https://github.com/react-component/menu/blob/master/src/MenuItem.tsx#L243).
so, in order to achieve this:
- i need pass icon to itemIcon ？
- or ignore itemIcon props, put icon in front of [item](https://github.com/MengZhaoFly/ant-design/blob/master/components/menu/MenuItem.tsx#L69)

**Comment by afc163** [comment]
> ignore itemIcon props, put icon in front of item

rc-menu's `itemIcon` is designed for submenu arrow icon.

**Comment by afc163** [comment]
@MengZhaoFly 可以帮忙继续把 Layout 里的演示代码改改。

**Comment by MengZhaoFly** [comment]
好的 晚上提 pr
