### ISSUE TITLE
DatePicker的onChange事件触发不对

### ISSUE THREAD

**Issue by ArleneShine** [ant-design/ant-design#23475]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-v55j9c?file=%2Fpackage.json%3A6%2C17)

### Steps to reproduce
选择DatePicker组件的日期，并没有触发onChange事件，必须点击确定按钮才会触发。

### What is expected?
选择DatePicker组件的日期，就会触发onChange事件

### What is actually happening?
选择DatePicker组件的日期，并没有触发onChange事件，必须点击确定按钮才会触发。

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.0 |
| System | win10 |
| Browser | Chrome 75.0.3770.80 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-fpfky?file=/index.js

是触发的，另外 `<DatePicker />` 没有确定按钮。

**Comment by XiaoMing6** [comment]
@afc163  漏了配置项, 设置showTime参数为true之后才会有描述的情况

**Comment by afc163** [comment]
这是预期的，有了确定按钮时界面选择不会触发选择行为，onChange 只有点击 ok 时才会触发。

这里缺少一个类似 RangePicker 的 `onCalendarChange` 来收集界面选择变化的行为：https://codesandbox.io/s/antd-reproduction-template-ulv6n

cc @zombieJ

**Comment by chongckw1996** [comment]
@afc163  onCalendarChange也是必须点击Ok时才会触发 ?  
我使用的是  `<RangePicker showTime />`

**Comment by LxxHub** [comment]
解决了吗

**Comment by danlong090902** [comment]
为什么在有了onOk确定按钮的时候就不触发onChange，这两个字面意思都应该不是一个方法，而且如果想要屏蔽确定按钮应该怎么做呢，确定按钮只是提供在确认时间提交一个数据并且关闭弹窗，而onChange是在切换面板时间的时候获取到实时的时间，这两个应该不是同一功能，在此建议恢复3.x版本功能

**Comment by danlong090902** [comment]
> https://codesandbox.io/s/antd-reproduction-template-fpfky?file=/index.js
> 
> 是触发的，另外`<DatePicker />`没有确定按钮。

为什么在有了onOk确定按钮的时候就不触发onChange，这两个字面意思都应该不是一个方法，而且如果想要屏蔽确定按钮应该怎么做呢，确定按钮只是提供在确认时间提交一个数据并且关闭弹窗，而onChange是在切换面板时间的时候获取到实时的时间，这两个应该不是同一功能，在此建议恢复3.x版本功能

**Comment by NijatInHIT** [comment]
> 这是预期的，有了确定按钮时界面选择不会触发选择行为，onChange 只有点击 ok 时才会触发。
> 
> 这里缺少一个类似 RangePicker 的 `onCalendarChange` 来收集界面选择变化的行为：https://codesandbox.io/s/antd-reproduction-template-ulv6n
> 
> cc @zombieJ

所以用了showtime就必须要用户点ok才生效？不好吧

**Comment by guido-visser** [comment]
The way it should be in my mind: 
`onChange`: Always trigger a change when the user clicks a date/time that is different from the current without having to click on Ok.
`onOk`: Trigger when the user clicks on Ok.

The API is very confusing at this moment. `onChange` isn't consistent. It should always trigger if you change a date or time regardless of the existence of the Ok button. The Ok button has its own API namely: `onOk`. Could this be fixed in a future version? It's a very annoying bug.

**Comment by linqian02** [comment]
遇到一样的问题，DatePicker 设置showTime=true时点击年月日时分秒均无法出发onChange事件，只有点击OK才能出发。
希望作为bug修复 @afc163

**Comment by Bravo123** [comment]
onChange -> onSelect

**Comment by theojia** [comment]
这个问题不管了吗😭

**Comment by lxdmw** [comment]
我也想说 这个问题解决不了了吗

**Comment by huali-dong** [comment]
这个问题还解决吗

**Comment by Tankliu6** [comment]
請修正這個問題，
目前使用上方留言的 onSelect 能解決 onChange 的問題，
但還是請官方正視這個問題。

**Comment by OscarKoo** [comment]
一点要点击"确定", 就是个很别扭的设定, 试想正常的用户, 选择了时间, 而且在输入框里也看到了新选择的时间, 这个时候鼠标很容易去点下一步操作了, 然后发现时间没了! 非要他点击确定才行, 好脑残的设定!

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
