### ISSUE TITLE
Select 控件为什么会把 null 当做有 value 而不显示 placeholder ，必须要为 undefined 才可以？

### ISSUE THREAD

**Issue by abbish** [ant-design/ant-design#2367]
Select 控件为什么会把 null 当做有 value 而不显示 placeholder ，必须要为 undefined 才可以？
有什么讲究么？

**Comment by afc163** [comment]
```jsx
<Select>
  <Option value={null}>未选择</Option>
  <Option value="male">男</Option>
  <Option value="female">女</Option>
</Select>
```

我想是 null 是个有意义的值吧。

**Comment by benjycui** [comment]
语言就是这么设计的。。。

See: http://www.ecma-international.org/ecma-262/5.1/#sec-4.3.9

**Comment by benjycui** [comment]
**undefined value** primitive value used when a variable has not been assigned a value

**null value** primitive value that represents the intentional absence of any object value

**Comment by abbish** [comment]
作为控件来说从业务含义上是否需要按照语言级别区分 null 和 undefined 呢？
比如 lodash 中的 _.isEmpty 从业务角度覆盖了多种语言层面上可以表示空的情况

**Comment by abbish** [comment]
多谢各位

**Comment by yansuan** [comment]
如果这样的的话，是不是可以判断一下<Option>里有没有null,如果没有，就把null当作无值处理？

实在不行就只能再封装一层组件了

**Comment by fwtcumt** [comment]
这是正常的吧，所有的表单控件表示空的都是 undefined ，千万别乱七八糟的兼容其他的“空值”。

**Comment by chenxingshuang** [comment]
没有讨论 出最后的结果啊， 官方能够提供下最后的设计初衷吗

**Comment by yoyo837** [comment]
和js为什么存在`null`和 `undefined` 两个东西的初衷一样的，`null`代表赋值为空，`undefined`代表未赋值。

**Comment by ryantbrown** [comment]
Is there an update to this? `null` is universally used by backends (and frontends) as no value. `undefined` is a JavaScript only type. We would expect the placeholder to show when the current value is `null`.

**Comment by ryantbrown** [comment]
@fwtcumt > This is normal. All form controls are undefined when they are empty. Don't mess with other "null values". 

This is simply not true, no other JS library does this. `null` is the universal type and is what all backends will return and will expect. In order to accomplish basic functionality, the select values need to mapped and converted to `undefined` and then converted back to `null` prior to sending a request.

**At the very least there should be a global option** that lets the user define what should be used: `null`, `''`, `undefined`, etc.

**Comment by 07akioni** [comment]
> @fwtcumt > This is normal. All form controls are undefined when they are empty. Don't mess with other "null values".
> 
> This is simply not true, no other JS library does this. `null` is the universal type and is what all backends will return and will expect. In order to accomplish basic functionality, the select values need to mapped and converted to `undefined` and then converted back to `null` prior to sending a request.
> 
> **At the very least there should be a global option** that lets the user define what should be used: `null`, `''`, `undefined`, etc.

Personally I agree with you. But what you said requires many codes to implement (and has no evident gains), which may not valuable for now (and there's no way to convince everyone).

**Comment by yogithesymbian** [comment]
so how to fix it ? i have just open all link of above didnt find solution , many tabs my chrome opened, it just telling why didnt show or didnt work cause ' ' or undefined or null . hmm 
should i use conditional in value ? 
```
                  value={
                    this.state.newDtAllPost.kategori_name_kategori === ""
                      ? "asd"
                      : "123"
                  }
```
so we not use placeholder , just use like it ? more simple solution please and dont spam link on above make confusion for new player , thanks in advance :dagger:

**Comment by ArealRJ** [comment]
设置options时,value值时一个数组,select框里回显的是value里的值,而不是label,有什么解决办法吗

**Comment by xingda** [comment]
我觉得这个话题有必要重新讨论一下，其实很简单，ant design应该至少保持内部的设计理念的统一。
如果其他控件像input等，null值可以显示placeholder，认为是等同于undefined，那么select控件应该和整体设计理念保持一致。
否则ant design自己就违反了设计一致性的原则，让使用者有错误的预期。
I think this topic need to be discussed more. and simply say, ant design should keep the design theory or principle consistent inside or all over components.
if other components like input see null as undefined, and show placehodler when the value is null, select should be same.
otherwise, users may got unexpected result when using different component in ant design, that is a bad design behavior.

**Comment by shamseer-ahammed** [comment]
+1 for this

**Comment by GitHub-hsq** [comment]
最近也遇到这个问题，往下翻官方文档才发现：
placeholder 只有在 value = undefined 才会显示，对于其它的 null、0、'' 等等对于 JS 语言都是有意义的值。

**Comment by armomu** [comment]
做一套组件库，无非就是把语言的一些特性通过二次封装起来变得好用，null、0、'' 等等对于 JS 语言都是有意义的值，对他是有意义的但是这个意义对于我们封装这个组件好用与否没有任何冲突，如果value = ''显示是90%的人认为好用的 我认为这样设计就是对的

**Comment by rizkyhaksono** [comment]
我尝试将其设为未定义和空值，但占位符仍不会显示。

**Comment by ZhangHaiyangYang** [comment]
我在使用#tagRender的时候 点击我插槽的元素 不会打开 下拉面板  我看文档列子 是可以的 我定位不到为什么 我该怎么定位？
