### ISSUE TITLE
[Form] Errors is not hiding when Form input changed

### ISSUE THREAD

**Issue by misterx** [ant-design/ant-design#24599]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-u6qhd?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Press Submit for empty form, then you will see error for the "Client validation" field.
2. Start typing into "Client validation" field. You wiil see that error is disappear
3. Type more than 3 chars into "Client validation" and press Submit.
4. You will see error for the "Server validation" field.
5. Start typing into "Server validation". You will see that error is still showing.

### What is expected?
Error should be hidden when field is changed

### What is actually happening?
Error is still shown

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | Windows 7 x64 |
| Browser | Chrome 81.0.4044.138 |

**Comment by zombieJ** [comment]
You should add `rules` on `server` field. When you use `setFields` to set error on a field which do not config `rules`. `errors` will be controlled by your code logic instead.

**Comment by misterx** [comment]
@zombieJ but i need validation on server side, how i can clear validation error using forms API when user changed field?

**Comment by zombieJ** [comment]
`rules.validator` support return promise. You should just use `rules` instead of manually update `errors`.

**Comment by misterx** [comment]
@zombieJ I can't use rules, because i need to validate whole form regarding business logic and return errors if has. Rules can be used only for field, not for form as far as i know.

**Comment by zombieJ** [comment]
Field error is only belong to field. What you need is just change `validateTrigger` to let it be submit only. If your server side validate is like give different errors to different fields. Just wrapper validate function:
```jsx
async function formValidator(values, fieldName) {
  // Some validate logic to get errors
  const fieldsErrors = { field1: ['23333'], field5: ['6666'] };
  const errors = fieldsErrors[fieldName];
  return errors ? Promise.reject(errors) : Promise.resolve();
}

<Form.Item
  rules={[{ validator: () => formValidator(form.getFieldsValue(), 'field5')  }]}
  {...rest}
/>
```

PS: You can add additional logic to reduce `formValidator` ajax call for server side.

**Comment by misterx** [comment]
@zombieJ Thank you, but my flow little bit different, i need to show errors when something happened on submit process, in other words i need to show error if submit fails according to server response. Snippet that you wrote can be applied only for pre submit validation, that's i'm using already. But I need to show error after submit.

**Comment by hahaliu005** [comment]
Same issue, After server return validation error, I need to set validation error manually.  Something like below : 
```
        <Form.Item name="name" validateStatus="error" help="error message">
          <Input />
        </Form.Item>
```
But after that , I don't know how to clear error message and status when you type in input field, just like origin behaviour, Anybody can help !

**Comment by zombieJ** [comment]
@hahaliu005 add `onChange` event on Input to listen for value change.

**Comment by hahaliu005** [comment]
@zombieJ Based on your advise , I write an example : 
```
import React, { useEffect } from "react";
import "./styles.css";
import { Form, Input } from "antd";
import "antd/dist/antd.css";
import { useForm } from "antd/lib/form/Form";

export default function App() {
  const [form] = useForm();
  useEffect(() => {
    form.setFields([
      {
        name: "name",
        value: "user name",
        errors: ["error message"]
      },
      {
        name: "pass",
        value: "The pass",
        errors: ["pass error message"]
      }
    ]);
  }, [form]);

  const onValuesChange = values => {
    Object.keys(values).forEach(field => {
      const error = form.getFieldError(field);
      if (!error.length) {
        return;
      }
      // Clear error message of field
      form.setFields([
        {
          name: field,
          errors: []
        }
      ]);
    });
  };

  return (
    <div className="App">
      <Form onValuesChange={onValuesChange} form={form} initialValues={{}}>
        <Form.Item name="name">
          <Input />
        </Form.Item>
        <Form.Item name="pass">
          <Input />
        </Form.Item>
      </Form>
    </div>
  );
}
```
Any better solution are appreciate .

**Comment by momesana** [comment]
> const onValuesChange = values => {
>     Object.keys(values).forEach(field => {
>       const error = form.getFieldError(field);
>       if (!error.length) {
>         return;
>       }
>       // Clear error message of field
>       form.setFields([
>         {
>           name: field,
>           errors: []
>         }
>       ]);
>     });
>   };

@hahaliu005, I have  a similar use-case though I need to reset all errors upon a change in a form as certain fields are dependent on other fields. Anyways, instead of repeatedly invoking the setFields method with an array containing a single object, you can collect all the fields and then call setFields with all updated fields at once. My code (albeit a bit different from yours as I need to consider/reset all fields) looks like this:
```js  
function onValuesChange (_changedValues, allValues) {
    const updatedValues = Object.keys(allValues)
        .filter(name => form.getFieldError(name).length)
        .map(name => ({ name, errors: [] }));
    form.setFields(updatedValues);
};
```

**Comment by rohitsahu4** [comment]
clearing error with setField in the onValuesChanged event handler has a issue. if there is rules/validator on Form.Item, setFields will clear the validation error also, SO rules/validation will not work. this happend to me when i was using Form with useForm. but when i use this with Ref it does not happens.

One fix i found was to have a fake rule.

`import React from 'react'
import { Form } from 'antd'

const FormItem = ({ rules, ...props }) => {
  const fakeRule = { validator: () =>  Promise.resolve() }
  const _rules = [fakeRule, ...(rules || [])]
  return <Form.Item {...props} rules={_rules} />
}
export default FormItem
`

I found out that if there is error applied using setFields. And if Form.Item has a validation rule. The error will clear because the new value has been passed through those validation and they have resolved.  So if there is a fake rule that resolves on every change the error will also be cleared.
