### ISSUE TITLE
RangePicker with Select component in renderExtraFooter trigger onOpenChange from RangePicker

### ISSUE THREAD

**Issue by andonimihai** [ant-design/ant-design#24696]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/still-wave-jct3r?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
* Open datepicker
* In datepicker, try to select some option from the Select

### What is expected?
Date picker should not close after the select value is selected

### What is actually happening?
Datepicker is closing

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | latest |
| System | Ubuntu 18.04 |
| Browser | Chrome  80.0.3987.163 (Official Build) (64-bit) |

---
This working on 3.x version, but after migration it doesn't work anymore

**Comment by DimaGavrushko** [comment]
What is the status of this bug? Very annoying issue, no luck with trying to avoid it.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
