### ISSUE TITLE
Skeleton.Button loading prop does not work

### ISSUE THREAD

**Issue by varundey** [ant-design/ant-design#25039]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-leaf-815wb)

### Steps to reproduce
Import Skeleton and use any Skeleton component (Avatar, Button, Input etc.) add prop `loading={false}` to it

```javascript
<Skeleton.Avatar loading={false} />
```

### What is expected?
Skeleton should not load

### What is actually happening?
Skeleton is loading

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome 83, FF 77 |

---
This bug only exists for other Skeleton components. It works for normal Skeleton
```javascript
<Skeleton loading={false} />
```

**Comment by kirill3333** [comment]
@varundey as far as I see from implementation for Avatar component, for example, it  doesn't have    loading property  https://github.com/ant-design/ant-design/blob/master/components/skeleton/Avatar.tsx

**Comment by fireairforce** [comment]
@Rustin-Liu It seems look like you lost this props?

**Comment by fireairforce** [comment]
@afc163 Should we add the this props to Skeleton Component like Avatar and Button etc..

**Comment by Rustin-Liu** [comment]
I don't think we need this props, if we add this props the api look like:
```jsx
<Skeleton.Button><Button></Button></Skeleton.Button>
```
It's wired.

You can use Skeleton.Button like:
```jsx
loading?<Skeleton.Button/>:<Button/>
```

This is my opinion, what do you think?

**Comment by RickMeasham** [comment]
Having a `loading` prop would make the Button Skeleton work like the paragraph skeleton. It just changes the shape of the skeleton to be button-like rather than paragraph-like. 

Per @Rustin-Liu's comment, the API for paragraph skeletons is already:

    <Skeleton><p></p></Skeleton>

so while the presented solution works for buttons, it also works for paragraphs. Having a consistent API should be key.

I'd like to request that this be reopened and implemented -- including for `Skeleton.Avatar` and other Skeletons

**Comment by Rustin-Liu** [comment]
I still think it is weird.   @afc163 @zombieJ @fireairforce    What do you think?
