### ISSUE TITLE
时间控件DatePicker设置allowClear点击清除已选时间后再次选择不会更新到当前的时分秒

### ISSUE THREAD

**Issue by YuShengSenior** [ant-design/ant-design#25081]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决二次选择时间不会更新到当前时间的问题

### What does the proposed API look like?
allowClear之后希望有一个回调或者更新底层代码解决标题所阐述的问题

**Comment by YuShengSenior** [comment]
demo https://codesandbox.io/s/antd-reproduction-template-5074o?file=/index.js

**Comment by zgoby** [comment]
1

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
