### ISSUE TITLE
即使0分0秒已被禁用，选中小时仍会默认选中0分0秒

### ISSUE THREAD

**Issue by Xumengxiang** [ant-design/ant-design#25143]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/xumengxiang/pen/rNxyrWW](https://codepen.io/xumengxiang/pen/rNxyrWW)

### Steps to reproduce
日期：时间:小时选中最近的小时，直接点击确定

### What is expected?
被disable的时间无法被选中

### What is actually happening?
被disable的0分0秒可以被选中

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.8.6 |
| System | macOS 10.14.6 |
| Browser | chrome |

**Comment by fireairforce** [comment]
能提供一个codesandbox在线的复现链接吗？你提供的这个页面点进去没登录重定向主页了，最好不要提供像这样的case。

**Comment by Xumengxiang** [comment]
登录手机号：15833333333，验证码随便填一个


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zoomdong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 中午11:40
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"徐孟祥"<1203433230@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 即使0分0秒已被禁用，选中小时仍会默认选中0分0秒 (#25143)





 
能提供一个codesandbox在线的复现链接吗？你提供的这个页面点进去没登录重定向主页了，最好不要提供像这样的case。

**Comment by fireairforce** [comment]
提供在线的吧。

**Comment by Xumengxiang** [comment]
https://codepen.io/xumengxiang/pen/rNxyrWW

**Comment by zgoby** [comment]
fixing...

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
