### ISSUE TITLE
[Form.List]: add() at index operation

### ISSUE THREAD

**Issue by PaulPCIO** [ant-design/ant-design#25357]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Adding an index to the `add()` operation will allow placing a new field at a given index instead adding it to the end of the form fields

```typescript
FormList.d.ts
interface Operation {
  add: (defaultValue?: StoreValue) => void;
  remove: (index: number) => void;
  move: (from: number, to: number) => void;
}
```

### What does the proposed API look like?
```javascript
add: (index: number) => void;
```

### Example Usage
![image](https://user-images.githubusercontent.com/39598117/86237507-2b104400-bb9c-11ea-8bdc-723dfea41666.png)

**Comment by windlany** [comment]
you can try add(), then try move(), for example:
`	<span
														className="add-icon"
														onClick={() => {
															add()
															// from: last to: current index + 1
															move(fields.length, fieldsIndex + 1)
														}}
													>
														<AddIcon />
													</span>`

**Comment by N00nDay** [comment]
Or use setFields and place it at the index you want. Instead of `add` create your own function called `addRow` for instance. Then in that function get the value of the `Form.List` you are attempting to update, add a blank `{}` or add properties if you prefer to the index you want the new line added, then use `form.setFieldsValues()` to update the `Form.List`. I have used this in a past component but difficult to know if this solves your current situation with out seeing your code. Can you provide a reproduce?

**Comment by PaulPCIO** [comment]
I don't really need the advice on how to get the same result by creating my own method, that's quite easy, the reason for this post is to extend the api that already exists, instead of adding something custom. Thanks anyways.

**Comment by N00nDay** [comment]
> I don't really need the advice on how to get the same result by creating my own method, that's quite easy, the reason for this post is to extend the api that already exists, instead of adding something custom. Thanks anyways.

Didn’t realize at first this was a feature request and not a bug. Makes sense.

**Comment by zombieJ** [comment]
merge into #26012
