### ISSUE TITLE
Input addonBefore 与 validate 状态重叠

### ISSUE THREAD

**Issue by yeatszhang** [ant-design/ant-design#25551]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eloquent-nobel-h96f6?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/eloquent-nobel-h96f6?file=/index.js

### What is expected?
与antd v3相同，校验啊状态不与addonAfter重叠

### What is actually happening?
Input addonBefore 与 validate 状态重叠
![image](https://user-images.githubusercontent.com/6488747/87042199-ecc2f680-c225-11ea-89ae-b4c96e4ddcef.png)

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.8.3 |
| System | macos 10.14.3 |
| Browser |  72.0.3626.109 |

**Comment by 07akioni** [comment]
It's a bug since v3. https://codesandbox.io/s/thirsty-bartik-xhjdj?file=/index.js

but I think it may not be trivial to fix, since it should get the width of `addonAfter` to set the position. even if it is handled, there are still `clearIcon`, `suffix` to deal with.

Currently you can manually set the position of the validation status indicator.

**Comment by afc163** [comment]
这种设计很难满足，带 addonAfter 的控件建议不要开启 feedback。
