### ISSUE TITLE
Modal.method() 所有的cancel失效

### ISSUE THREAD

**Issue by Lmangoxx** [ant-design/ant-design#25659]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/stupefied-lake-vyrri?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
打开重现链接点击info按钮弹窗

### What is expected?
取消按钮可以正常显示操作

### What is actually happening?
取消按钮不显示

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.13.1 |
| System | macOS High Sierra 10.13.6 |
| Browser | Chrome 83.0.4103.116（正式版本） （64 位） |

**Comment by afc163** [comment]
It is by designed, `Modal.info` don't have cancel button.

**Comment by ericzon** [comment]
First of all, thanks for this great component library.

IMHO this should be highlighted in the documentation (I wasted several hours with this). Could you consider add the same behaviour in Modal.<method> that in static version (<Modal...)?

Questions around this:
- which are the list of settings that are not available by design in Modal.<method>? is there any place in the docs explaining this?
- If cancel is not available, how can be simulate a similar behaviour?
