### ISSUE TITLE
dropdown onVisibleChange in not called if a menuItem in overlay is clicked.

### ISSUE THREAD

**Issue by Rnb1189** [ant-design/ant-design#26104]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-v3wju?file=/index.js:224-228)

### Steps to reproduce
1- click button to show dropdown overlay
2- click one of the items to hide overlay (not outside of overlay)

### What is expected?
It is expected that onVisibleChange is called when ever it is closing

### What is actually happening?
onVisibleChange is not called on hidding when you click a menuItem. it is only called when you click outside of overlay

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.11.0 |
| System | win 10 64bit |
| Browser | chrome 84 |

**Comment by willamesoares** [comment]
Hi, I have some input on this. The Dropdown component relies on [rc-dropdown](https://github.com/react-component/dropdown) which accepts a prop called`onOverlayClick`, which is called when you click on an item on the menu (thus in the overlay).
Since the props that are passed in to the `Dropdown` component are simply passed down to the `RcDropdown` component, you can just use `onOverlayClick` to achieve what you want.

I believe this isn't a bug since the docs don't state that `onVisibleChange` should be called when you pick a menu item. Also, it seems you can achieve what you want using other props so not sure there's anything to be done for this.

**Comment by afc163** [comment]
see #4994
