### ISSUE TITLE
Table: Customized filter panel example doesn't auto select search text

### ISSUE THREAD

**Issue by hfknight** [ant-design/ant-design#26144]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-custom-filter-panel](https://ant.design/components/table/#components-table-demo-custom-filter-panel)

### Steps to reproduce
see the codes in "Customized filter panel". The search text in Input is auto-selected in v3 after opening the filter dropdown, it doesn't do it in v4.

### What is expected?
previous search text entered should be selected after opening the filter 

### What is actually happening?
text in filter Input box isn't selected.

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.10.1 |
| System | macOS Catalina |
| Browser | Google Chrome |

**Comment by jperelli** [comment]
Hi @afc163 do we have any explanation or alternative solution for this? I tried using useLayoutEffect but it didn't work either.

- Is antd replacing the input after rendering?
- Does this happen because we need to wait for an animation to happen?
- Or maybe this has to do with a 'portal' being used in the Popup element?

I tried debugging it to find the root cause but couldn't find it

**Comment by afc163** [comment]
I don't know why either, this bug didn't happen in Firefox but only Chrome.
