### ISSUE TITLE
Consider removing moment.js dependence as it's now considered as a legacy project

### ISSUE THREAD

**Issue by Fcmam5** [ant-design/ant-design#26759]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I believe that this has been reported many times, but now as Moment.js is considered as a legacy project in maintenance mode (see: https://momentjs.com/docs/#/-project-status/), in addition to the problems that we may face when working with it (bundle size, mutable APIs..)

### What does the proposed API look like?
Switch to any date library.

**Comment by xiaoxiangmoe** [comment]
ng-zorro-antd use date-fns

**Comment by zazzaz** [comment]
I recommend [Day.js](https://github.com/iamkun/dayjs) with [antd-dayjs-webpack-plugin](https://ant.design/docs/react/replace-moment#antd-dayjs-webpack-plugin).

It's super easy to use and replace Moment.js is just one second. Every syntax and APIs are just exacetlly the same with nothing else to learn.

According to Moment.js's recommandation on their website: 

> Day.js is designed to be a minimalist replacement for Moment.js, using a similar API. It is not a drop-in replacement, but if you are used to using Moment's API and want to get moving quickly, consider using Day.js.

**Comment by breeswish** [comment]
Day.js can be the first-class citizen in Antd, replacing all momentjs occurrence natively, instead of just being available as a plugin mentioned in https://github.com/ant-design/ant-design/issues/26759#issuecomment-693787987 . This also resolves issues like https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/23

**Comment by int64ago** [comment]
It's a break change, maybe antd v5 ?

**Comment by zombieJ** [comment]
Yes. We have notice this. Since this will be a breaking change, we may not do action immediately in current version.

**Comment by xiaoxiangmoe** [comment]
`dayjs` and `moment` have the same API. They are both mutable APIs, which are easy to misuse. 

Why not change to a new library in this breaking change?

**Comment by zazzaz** [comment]
@xiaoxiangmoe Day.js is 2kB size and __immutable__, that's the main difference from moment.js.

**Comment by 0408jiahuicao** [comment]
> Day.js is designed to be a minimalist replacement for Moment.js, using a similar API. It is not a drop-in replacement, but if you are used to using Moment's API and want to get moving quickly, consider using Day.js.

**Comment by sgb-io** [comment]
Any information about what would not be backwards compatible using dayjs?

**Comment by jeferson-sb** [comment]
any news on this one?

**Comment by masbaehr** [comment]
I was searching for a UI library, found ant-design, checked bundlephobia, and was shocked ;-)
Moment.js really should be replaced its a whopping 23% of the bundle size.
https://bundlephobia.com/result?p=antd@4.10.3

**Comment by glebdv** [comment]
> `dayjs` and `moment` have the same API. They both have mutable API, which are easy to misuse.
> 
> Why not change to a new immutable library in this breaking change?

dayjs is immutable

**Comment by glebdv** [comment]
+1

**Comment by adisrael** [comment]
[Luxon](https://github.com/moment/luxon) looks like the natural replacement of moment: 
- It is authored by Isaac Cambron, a long-time contributor to Moment. 
- It is the first recommendation in [https://momentjs.com/docs/#/-project-status/](https://momentjs.com/docs/#/-project-status/).

**Comment by glebdv** [comment]
@adisrael 
Most alternatives are all looking pretty good, so it will take a small proof of concept to figure out which one is better.
Luxon is less popular, then date-fns, then dayjs in github stars (aka community love)
date-fns has most downloads, then it's dayjs then luxon
luxon also has less open issues (but smaller community, so who knows)
dayjs is the smallest in size and customizable to your needs
under the hood differences, etc

So there are definitely things to consider before making a choice. So far Ive used date-fns and dayjs with multiple lang support and perso I prefer dayjs, but yeah, that's my flavor because I tend to like smaller packages (queue explicit joke).

**Comment by afc163** [comment]
moment.js is replaced by dayjs in https://github.com/ant-design/ant-design/pull/34057
