### ISSUE TITLE
RangePicker 面板上的值与value不一致

### ISSUE THREAD

**Issue by XiaoJiuDYS** [ant-design/ant-design#26840]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-star-5uz2g)

### Steps to reproduce
将open设置为true，先选择一个范围，然后手动set RangePicker的 value

### What is expected?
Input框与弹出面板上的值也被改掉

### What is actually happening?
手动设置的value未生效，显示的仍是原先选择的范围

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | MacOs |
| Browser |  chrome 85.0 |

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
