### ISSUE TITLE
Dropdown flickering glitch

### ISSUE THREAD

**Issue by sinahamzezade** [ant-design/ant-design#26979]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Just add a bunch of submenu inside a dropdown

### What is expected?
To not have a flicker glitch when hovering on the submenu

### What is actually happening?
https://streamable.com/ss5ydr

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | Mac, Windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Seems I can not access to `https://streamable.com/ss5ydr`. Could you help to provide a codesandbox link instead?

**Comment by afc163** [comment]
Menu.SubMenu has some problem.

**Comment by sinahamzezade** [comment]
Hi, Sorry for the delay, 
Yes it seems something wrong with the Submenu.

**Comment by afc163** [comment]
![2020-11-08 13-47-46 2020-11-08 13_48_13](https://user-images.githubusercontent.com/507615/98458211-2b16f500-21c9-11eb-9e9d-918c3f1bb942.gif)

**Comment by kerm1it** [comment]
这个没问题？

**Comment by afc163** [comment]
这个 gif 帧率不够，不明显。

**Comment by zombieJ** [comment]
This is caused by `rc-menu` animation re-played. `rc-menu` use `rc-trigger` for popup support and use `rc-motion` for animation support (which not use `rc-trigger` motion). Which cause the issue:

#### Frame 1
* Popup `rc-trigger` set to `visible`
  1. PopupSubMenu rendered trigger CSSMotion to `visible`
* Menu Panel render which trigge CSSMotion status to `appear` (or `enter`)

#### Frame 2
* Popup `rc-trigger` go to `measure` status in next frame (current: `stable`)
* Menu Panel animation start

#### Frame 3
* Popup `rc-trigger` go to `align` status in next frame (current: `measure`)
* Menu Panel animation play 1 frame

#### Frame 4
* Popup `rc-trigger` status to `align` trigger `rc-align` force align
  * 💥 Force align makes browser reflow - Animation reset
    * Menu Panel animation restart by browser

### Timing Snapshot

![截屏2020-11-09 下午4 35 01](https://user-images.githubusercontent.com/5378891/98517845-86b8af80-22a9-11eb-8b1f-c53004c05451.png)

#### Frame 1
![截屏2020-11-09 下午4 48 47](https://user-images.githubusercontent.com/5378891/98519365-a355e700-22ab-11eb-8dde-b2a5a336d941.png)

#### Frame 2 (Started)
![截屏2020-11-09 下午4 49 03](https://user-images.githubusercontent.com/5378891/98519385-abae2200-22ab-11eb-9796-5c477affc134.png)

#### Frame 3 (Animation pass 1 frame)
![截屏2020-11-09 下午4 49 12](https://user-images.githubusercontent.com/5378891/98519388-acdf4f00-22ab-11eb-956b-7f8b1b64948a.png)

#### Frame 4 (Restarted)
![截屏2020-11-09 下午4 49 29](https://user-images.githubusercontent.com/5378891/98519394-ae107c00-22ab-11eb-9585-83e51a9c144b.png)

#### Frame 5
![截屏2020-11-09 下午4 49 37](https://user-images.githubusercontent.com/5378891/98519396-aea91280-22ab-11eb-985e-ae88377cf010.png)

**Comment by zombieJ** [comment]
We need move `rc-menu` CSSMotion to use `rc-trigger` motion config directly.
