### ISSUE TITLE
[Calendar component] when switch to not current month  current date would be selected

### ISSUE THREAD

**Issue by HTw-ss** [ant-design/ant-design#27109]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/calendar-cn/#components-calendar-demo-card](https://ant.design/components/calendar-cn/#components-calendar-demo-card)

### Steps to reproduce
Octorber 12 today, switch to September, September 12 would be selected

### What is expected?
when I switch to a different month, except for current month, none of date would be selected

### What is actually happening?
no matter which month I switch into, the date of current month would be selected. For example , today is 2020-10-12, when I switch to September, the date 2020-09-12 would be selected, which I thought is a bug.

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | 10.14.6 |
| Browser | chrome 85.0.4183.121 |

**Comment by dcgudeman** [comment]
I have this issue too. @HTw-ss did you find a work around?

**Comment by jakub-chatrny** [comment]
Yep, this behavior is probably caused by https://github.com/ant-design/ant-design/commit/22fdd41732f495188bc8b33473a3541f8012ea8e#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2R131 
Should be posibble to work around with custom `disabledDate` implementation. Since in [rc-picker](https://react-component.github.io/picker/?selectedKind=rc-picker&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fsource%2Fpanel) this works fine.

I'll try create PR with fix

**Comment by dan-lee** [comment]
@jakub-chatrny How would I work around that with `disabledDate`? Could you get to the PR yet?

**Comment by hans-lizihan** [comment]
I think this is a bug indeed. After some dig, it seems like some change in rc-picker need to be done. 

https://github.com/react-component/picker/blob/master/src/PickerPanel.tsx#L202

there is this `viewDate` state in RC-picker. However, this is not exposed as a controlled field so antd can't really utilize that internal state.

**Comment by SourceCipher** [comment]
This bug is been there from the v3 and still is in v4...

**Comment by zombieJ** [comment]
Sorry for delay.

Calendar component is design as always trade date in current panel. Which means the year or month select change is the select operation.
