### ISSUE TITLE
<Search> is not vertically aligned in <Layout.Header> but <Input> is.

### ISSUE THREAD

**Issue by evanandrewrose** [ant-design/ant-design#27293]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8mn1c)

### Steps to reproduce
Create a <Search> within a <Layout.Header>.

### What is expected?
Search component should be vertically centered, as is the case with the Input component.

### What is actually happening?
Search is top-aligned.

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 17.0.0 |
| System | Ubuntu 20.04 |
| Browser | Firefox |

**Comment by evanandrewrose** [comment]
It looks like even just adding an `addonAfter` property to an `Input` causes the `Input` to be top-aligned instead of middle-aligned.

https://codesandbox.io/s/antd-reproduction-template-forked-1uh25

**Comment by afc163** [comment]
It is hard to resolve cause different layout of Search and Input, please use css solution such as flex: https://codesandbox.io/s/antd-reproduction-template-forked-271r0?file=/index.js

**Comment by filev-svt** [comment]
Same problem in Chrome after antd update, unfortunately can't say which version broke the component.

The flex solution does not work when nesting the `<Layout.Header />` child components inside a `<Space />`, I guess that's why we can see it as an unused import in the codesandbox above. 
![image](https://user-images.githubusercontent.com/43383483/119002740-6c186f00-b98d-11eb-9710-053668735f46.png)

**Comment by filev-svt** [comment]
For those who look for a dirty and working solution: `<Space><Input.Search style={{ display: "block" }}></Input.Search></Space>` should work just fine when using a `Space` wrapper.
