### ISSUE TITLE
Date Picker and Time Picker required attribute

### ISSUE THREAD

**Issue by danieldukic** [ant-design/ant-design#27616]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently it is not possible to pass `required` attribute to the input representing Date Picker or Time Picker and because of that HTML5 validation won't trigger if a user didn't choose a value. Maybe it would also be okay to be able to pass multiple attributes to the input (data attributes, etc.)

### What does the proposed API look like?
```javascript
<TimePicker id="foo" required />
```
which would render
```html
<div class="ant-picker">
  ...
  <input id="foo" title="" size="10" autocomplete="off" value="" required>
  ...
</div>
```

or 

```javascript
<TimePicker inputAttributes={{ required: true, "data-foo": "foo" }} />
```
which would render
```html
<div class="ant-picker">
  ...
  <input id="foo" title="" size="10" autocomplete="off" value="" required data-foo="foo">
  ...
</div>
```

**Comment by Diae-Louali** [comment]
is this possible as of today ?

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
