### ISSUE TITLE
Setting modes programatically not working properly anymore

### ISSUE THREAD

**Issue by asg452** [ant-design/ant-design#27680]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/heyaj/pen/eYzPxxR?editors=0010](https://codepen.io/heyaj/pen/eYzPxxR?editors=0010)

### Steps to reproduce
Click date picker, select date, select time from a different panel

### What is expected?
The date picker  panel opens. After selecting date  the date picker panel closes and  the time picker opens up and you can select the time and press ok.

### What is actually happening?
The date picker opens, the time picker opens but you cannot select the time

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16 |
| System | Mac |
| Browser | Chrome Version 86.0.4240.111  |

---
On picking a date, it opens the panel for selecting time but you cannot press ok or pick the time.   You can add  showTime={{open:false,
          disabledSeconds:this.disabledSeconds,
          hideDisabledOptions:true,
          minuteStep:15 }} in the datepicker component and its still not working.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
