### ISSUE TITLE
DateRange picker doesn't support locale specific time format "LT" and "LTS"

### ISSUE THREAD

**Issue by urrri** [ant-design/ant-design#27777]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/range-picker-antd482-locale-format-problem-kz26w)

### Steps to reproduce
Use automatic locale specific time format

```<RangePicker showTime={{ format: "LT" }} /> // or "LTS"```

instead of hardcoded format

```<RangePicker showTime={{ format: "HH:mm" }} /> // or "HH:mm:ss```

### What is expected?
Appropriated time selector columns to appear when dropdown part is visible

### What is actually happening?
time part is not visible, time selector columns doesn't appear at all, like if time format is wrong. But time above columns is formatted correctly.

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.12 |
| System | windows 10 |
| Browser | chrome 86 |

**Comment by Harukisatoh** [comment]
It appears that TimePicker component has the same problem

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
