### ISSUE TITLE
RangePicker 选择日期问题

### ISSUE THREAD

**Issue by lwenchun** [ant-design/ant-design#27898]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost](http://localhost)

### Steps to reproduce
1、选择范围日期 如：2019-01-01 ~ 2019-01-02
2、再次选择开始日期：2020-11-20 ，结束时间清空，选择时间窗还是旧的面板，应跳转到2020-11-20后可选择日期

### What is expected?
结束时间选择框直接切到可选日期

### What is actually happening?
结束时间不可选，需要切换日期到2020-11-20后才能选择

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.9.56 |
| System | windows 7 |
| Browser | Google Chrome 86.0.4240.75 |

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
