### ISSUE TITLE
Week range is not highlighted in WeekRangePicker.

### ISSUE THREAD

**Issue by obokhonko** [ant-design/ant-design#27984]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/#components-date-picker-demo-range-picker](https://ant.design/components/date-picker/#components-date-picker-demo-range-picker)

### Steps to reproduce
1. Enter the link and find the date type WeekRangePicker
2. Select Start week and End week with a difference of # two weeks
3. Then click on the input that was just filled

![Reporoduction scenario](https://i.ibb.co/xSMsxZb/week-range-picker.gif)    

### What is expected?
Range is highlighted

### What is actually happening?
Only one week from the range is highlighted.

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | ^16.14.0 |
| System | Win 10 Enterprise ver.1909 build 18363.1198 |
| Browser | Google Chrome Version 87.0.4280.66 (Official Build) (64-bit) |

---
We expect week range picker to highlight the selected range the same way as date range picker does.

**Comment by AlanCutFlim** [comment]
There is a related issue https://github.com/ant-design/ant-design/issues/26823#issuecomment-697308711
I may not translate very well. The reply said that this is by design, have range highlighted will make the component bloated.

One of the reasons why we love antd is because every component follow a same design pattern. I personally think it's better to have range highlighted because the other range pickers all have range highlighted, it may make users(like me) confused when WeekRangePicker's interaction differ from other range pickers.

**Comment by Frontmaster** [comment]
@AlanCutFlim , my first thought was that the way week picker range highlighted is by design. On the other hand, the fact that it is very inconsistent with a range pattern introduced for other range picker variants makes it impossible to except by our UX designers.

**Comment by zombieJ** [comment]
As https://github.com/ant-design/ant-design/issues/26823#issuecomment-697308711 mentioned. Currently may not have good solution to keep the design align with other picker since it may to heavy  for the colored area. Welcome for your advice if have better suggestion.

**Comment by zombieJ** [comment]
Close since realized in latest version
