### ISSUE TITLE
AntD numbers in datepicker and pagination are not localized

### ISSUE THREAD

**Issue by Mohamed-Ghanem** [ant-design/ant-design#28022]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bx8jd)

### Steps to reproduce
Click on عربي

### What is expected?
Datepicker numbers (days) and pagination number should be in arabic.

### What is actually happening?
Datepicker numbers (days) and pagination number is not changed with localization.

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome Version 86.0.4240.198 (Official Build) (64-bit) |

**Comment by liZHI912** [comment]
怎么禁止日期选择框手动输入

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
