### ISSUE TITLE
RangePicker的format设置为YYYY-MM-DD HH:mm:ss.SSS时只改变毫秒值无法触发onChange事件

### ISSUE THREAD

**Issue by wanderxyx** [ant-design/ant-design#28075]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6mvdv?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
format设置为YYYY-MM-DD HH:mm:ss.SSS

### What is expected?
毫秒值改变时触发onChange事件

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.13.1 |
| System | macOS |
| Browser | chrome_86 |

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
