### ISSUE TITLE
[RangePicker] 切换开始和结束面板会导致年份被禁用

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#28083]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker](https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker)

### Steps to reproduce
- 在 2020 年内选取一个开始日期，然后在 2021 年内选取一个结束日期
- 点击 start date 进入它的年份面板，接着点击 end date 切换到它的年份面板
- 如果没有复现，请按照 GIF 中的步骤再操作一遍
![Kapture 2020-11-30 at 13 08 58](https://user-images.githubusercontent.com/50612752/100587338-6372a480-332b-11eb-9a77-f2f3083c386e.gif)

### What is expected?
2020 年未被禁用

### What is actually happening?
2020 年被禁用了

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by zombieJ** [comment]
By Design. v5 里准备去掉这个限制。

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
