### ISSUE TITLE
menu 建议添加显示消失延迟时间

### ISSUE THREAD

**Issue by Syzmex** [ant-design/ant-design#2837]
顶部的主菜单，个人感觉有个延迟时间会比较好
现在的情况是：**鼠标抖一下菜单就收了**

现在对菜单样式做修改
比如菜单下拉的部分加宽并且横向放多列菜单，没有延迟就很不好用了

**Comment by afc163** [comment]
https://github.com/react-component/menu/issues/24

**Comment by yeliex** [comment]
建议更新下文档 现在文档很多属性还是缺失的

**Comment by benjycui** [comment]
@yeliex 文档类建议可以直接 PR。。

**Comment by benjycui** [comment]
6.0.0

**Comment by KaiVolland** [comment]
I can't read this... :disappointed:

**Comment by afc163** [comment]
@KaiVolland Try google translate

**Comment by KaiVolland** [comment]
As this is an opensource project it would be really helpful if all issues, comments etc. were written in english. Otherwise you exclude a huge part of the community. But this might not be the right place to discuss this…

BTW: google translate is not really an option as comments regarding code have to be precise some times.

**Comment by afc163** [comment]
We like that: https://github.com/ant-design/ant-design/issues/4897 In fact, we made a bot to [suggest people using English](https://github.com/ant-design/ant-design/issues/6723#issuecomment-312855174). But it is hard to force every one follow it.
