### ISSUE TITLE
setFieldsValue does not re-render form value

### ISSUE THREAD

**Issue by huyhoangsz** [ant-design/ant-design#28405]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-montalcini-wlt61?file=/src/App.js)

### Steps to reproduce
Bug reproduce:
Step 1: Click on button 

### What is expected?
Age is changed to 25, gender is changed to Boy

### What is actually happening?
 Age is changed to 25, gender is not changed

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.0 |
| System | Mac os |
| Browser | Chrome Version 87.0.4280.88 (Official Build) (x86_64) |

---
setFieldsValue does not re-render form items. This is a silly example. Let's say I have 2 items in the form (gender and age). If age > 18 then gender should be boy else gender should be girl. 

If I change the age by inputting new value to the number input, everything works as expected. However, if I change the age by clicking on the button, my app does not work.

**Comment by huyhoangsz** [comment]
Interesting answer from stackoverflow. This does not answer the question but it's good to know that it works when the dependencies is empty array. Not sure why and what is the right way to update the form.

https://stackoverflow.com/questions/65342114/setfieldsvalue-does-not-re-render-form-value/65342938#65342938

**Comment by tanqiyuan** [comment]
Form.Item add shouldUpdate props : <Form.Item noStyle dependencies={["age"]} shouldUpdate>

**Comment by yoyo837** [comment]
https://codesandbox.io/s/relaxed-glitter-7st7b?file=/src/App.js

**Comment by alanwei0** [comment]
I also encountered this issue. According to @yoyo837 's answer, I have to use `shouldUpdate` instead of `dependencies`. 

It can work indeed, but still be confusing. Because at the very beginning, my form only needed to use `dependencies`, it's enough, but recently, there's a new requirement which needs to update some fields value outside, so I called `setFieldsValue`. As a result, many of my `dependencies` stop working, now I have to change them to `shouldUpdate`. I think it's an extra effort.

Why those dependent form items(in this case, the **gender** field) cannot be updated if I set the value of **age** by `setFieldsValue`?

**Comment by kongshu612** [comment]
> https://codesandbox.io/s/relaxed-glitter-7st7b?file=/src/App.js

Hi, there. Even though, we can use **shouldUpdate** to bypass the **setFieldsValue**, I wonder if it is reasonable, to support re-render when only using **dependencies**?

From [AntD](https://ant.design/components/form/#shouldUpdate), **dependecies** is aimed for triggering validation if upstream fields changes. while, **shouldUpdate** is aimed for re-render if condition match. 
If that is the case, this is not a bug, it is by design.  Otherwise, we had better support this. how do you think?

**Comment by brhanegiday** [comment]
In Antd v4, you only required to call the **setFieldsValue** in **useEffect** function. 

        const [form] = Form.useForm()
        
         useEffect(() => {
          //companyInfo -> dynamic obj fetched from API
         form.setFieldsValue(companyInfo);
         }, [companyInfo, form]);

Then in **Form** use the **form** prop as follow: 

         <Form
         //passing form prop 
          form={form}
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 14 }}
          onFinish={onFinish}
          labelAlign="left"
          colon={false}
        >

**Comment by KishanKumarNR** [comment]
what is the solution ?

**Comment by silveiralsv** [comment]
Is there any solution? I've added the shouldUpdate props but doesn't work. 

A ugly way I've found to bypass this is declare an boolean state and perfom an setState(!state) after form.setFieldsValue().

**Comment by chillyistkult** [comment]
You can call `form.resetFields()` after calling `form.setFieldsValue(values)` which will re-render all form items, but has other undesired side effects.
