### ISSUE TITLE
Url within a table in a Carousel can't be clicked

### ISSUE THREAD

**Issue by sturlath** [ant-design/ant-design#28406]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/prod-microservice-hm62g?file=/pages/index.js)

### Steps to reproduce
Add two components inside a Carousel with one that has <Link/> (or just ahref) in its data. Try to click the link.. it doesn't function as a normal URL. 

BUT if you remove the other component you get to click the links.

### What is expected?
You should be able to click the link in a table within a Carousel.

### What is actually happening?
Can't click a link in a table within a component within a Carousel IF there are two components in that Carousel. 

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | nextjs vs 9.5.3 |
| System | Windows |
| Browser | Microsft Edge |

---
I tried to make sure that there was nothing in my code causing this but without the codesandbox.io working.

**Comment by afc163** [comment]
<img width="712" alt="图片" src="https://user-images.githubusercontent.com/507615/102499098-bd0df980-40b5-11eb-9112-5998ace45bee.png">

It cannot work.

**Comment by sturlath** [comment]
I don't know what happened there but here is a [new sandbox](https://codesandbox.io/s/strange-mountain-5zypk?file=/pages/index.js) 

But like you see I can't add the <Second /> component into the Carousel to reproduce the "can't click the link" error.

Can you work with this?

**Comment by DrMuda** [comment]
When dotPosition: "top", the height of dots is too high, so the url within a table is blocked
**How to solve** 
1.Set dotPosition to bottom/left/right
2.Change the height of dots

Why is there only one component you will get to click the links? Because dots are hidden，the table color is very similar to the dots color，you may not notice that the dots is hidden

This is my reproduction link [https://codesandbox.io/s/fmhw3](https://codesandbox.io/s/fmhw3)

**Comment by DrMuda** [comment]
When dotPosition: "top", the height of dots is too high, so the url within a table is blocked
**How to solve**
1.Set dotPosition to bottom/left/right
2.Change the height of dots

Why is there only one component you will get to click the links? Because dots are hidden，the table color is very similar to the dots color，you may not notice that the dots is hidden

This is [my reproduction link](https://codesandbox.io/s/fmhw3)

My English is very poor, so please forgive me for misusing words or grammar

**Comment by sturlath** [comment]
Ahh, thank you so much @DrMuda !  Your English is just fine and you understood quite well! This explains a lot why this wasn´t working for me. I'll close this issue.
