### ISSUE TITLE
[DatePicker] - `defaultValue` of `showTime` doesn't work for `SSS`

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#28591]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/riqishijianxuanze-antd494-forked-pgkws?file=/index.js)

### Steps to reproduce
- Select a date and view the format result.

### What is expected?
- `defaultValue` of `showTime` should work for `SSS`.

### What is actually happening?
- `defaultValue` of `showTime` doesn't work for `SSS`.
![image](https://user-images.githubusercontent.com/14918822/103265263-295af800-49e8-11eb-9a4f-a875d4e7cc5a.png)

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.14.0 |
| System | MacOS 10.15.5 |
| Browser | Chrome 81.0.4044.138 |

**Comment by afc163** [comment]
- #28188  
- #28075

**Comment by joshua-lehmann** [comment]
@afc163  Even int antd 5 Milliseconds are still not supported in the TimePicker. Is there any plan to fix this?

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
