### ISSUE TITLE
[Date/RangePicker] YearPicker on RangePicker is fixed to YYYY

### ISSUE THREAD

**Issue by patch-lee** [ant-design/ant-design#28689]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kze2b?file=/index.js)

### Steps to reproduce
* Open Date/RangePicker
* Click Year (2564 in the link)

### What is expected?
It should display buddhist year on YearPicker (at least BBBB)

### What is actually happening?
It displayed christian year (YYYY format)

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | Mac OS High Sierra 10.12.6 |
| Browser | Google Chrome 87.0.4280.88 |

---
I just attemped to use buddhist year instead of christian year, so I replaced moment with dayjs buddishEra plugin. But it's not working.
Any suggestion or quick fix?

Thanks in advance! :)

**Comment by zombieJ** [comment]
Is that a bug with original moment picker?

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
