### ISSUE TITLE
Now button doesn't work when date panel  (showTime = true) is switched to month or year panel

### ISSUE THREAD

**Issue by 07akioni** [ant-design/ant-design#28811]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/#components-date-picker-demo-time](https://ant.design/components/date-picker/#components-date-picker-demo-time)

### Steps to reproduce
Follow the video.

https://user-images.githubusercontent.com/18677354/104154440-e48b8400-541f-11eb-9802-99ebb622901f.mov

### What is expected?
When I click now, time should be set to now.

### What is actually happening?
Not working.

| Environment | Info |
|---|---|
| antd | undefined |
| React | latest |
| System | Mac OS |
| Browser | Chrome@latest |

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
