### ISSUE TITLE
Carousel 如何设置轮播元素之间的间距

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design#28841]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有些时候我们轮播时，并不是一个一个的轮播，可能是直接显示若干个轮播元素，
我发现在给轮播元素写css的margin时并不生效，看了react-slick文档貌似也没找到。

请问是需要对轮播元素再包一层么？然后给包裹元素加padding来实现轮播元素间的间隙

### What does the proposed API look like?
提供一个margin值，控制轮播元素的间的间距

**Comment by afc163** [comment]
https://react-slick.neostack.com/docs/example/multiple-items

**Comment by mweiss9676** [comment]
Not sure why this is closed. The React Slick docs show margin by default and it appears that Ant Design removes that margin somehow (all examples on the Carousel page have no margin between items). The docs don't have anything in them about adding margin (probably because they already do by default)

**Comment by keqingf** [comment]
我也在找这个，但好像并不支持，选择使用其他插件
