### ISSUE TITLE
Button Wave Effect doesnt work inside Shadow Root (web component)

### ISSUE THREAD

**Issue by JohnDeved** [ant-design/ant-design#28934]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0o49z?file=/index.js)

### Steps to reproduce
see reproduction example.
Click the button

### What is expected?
wave effect for button click

### What is actually happening?
nothing

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 17.0.0 |
| System | Windows 10 |
| Browser | Chrome 87.0.4280.141 |

---
shoud maybe use getPopupContainer config setting
https://github.com/ant-design/ant-design/blob/481335bbaa0caacc6b2a8140093684d5f04e6df2/components/_util/wave.tsx#L80

**Comment by afc163** [comment]
https://github.com/react-component/trigger/pull/227/

@rinick

**Comment by rinick** [comment]
ok @afc163  I will work on this in the weekend

**Comment by rinick** [comment]
This should not use getPopupContainer, because style element is not a popup.
One might put UI element in shadow dom but keep popup in main dom, that's totally fine.
but the style must be in the same dom as the UI element

In this case we just need to use `ownerDocument.`  instead of `document.`
I will create a PR later

**Comment by JohnDeved** [comment]
sadly still isn't fixed.
ownerDocument still returns document outside of shadowRoot
when using `element.getRootNode` instead of it `element.ownerDocument ` to works

**Comment by afc163** [comment]
@JohnDeved PR welcomes

**Comment by JohnDeved** [comment]
@afc163 thank you I'm on it :)

**Comment by JohnDeved** [comment]
@afc163 @rinick suggested change a change in the pr https://github.com/react-component/trigger/pull/227#discussion_r564338213

**Comment by rinick** [comment]
@JohnDeved you are right, I should use getRootNode instead of ownerDocument
I will create another PR this weekend.

but I don't think that change should go in rc-triggers.

if my button is implemented in shadow-dom,   parent container might clip content or even having scroll bar,  if popup is also created in the shadow dom, it just won't be visible.
