### ISSUE TITLE
Grid: setting vertical spacing on the gutter property of Row as grid spacing is not working?

### ISSUE THREAD

**Issue by linxux** [ant-design/ant-design#29250]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9uw68)

### Steps to reproduce
Please check on codesandbox.

### What is expected?
Downgrade the version to `4.8.2`
[demo](https://codesandbox.io/s/antd-reproduction-template-forked-nc9ww)

The vertical padding values should be set.
```
<div class="ant-col Col" style="padding: 12px 8px;">
...
</div>
```

### What is actually happening?
The vertical padding values are missing.
```
<div class="ant-col Col" style="padding-left: 8px; padding-right: 8px;">
...
</div>
```

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 16.13.1 |
| System | Ubuntu 20.04.1 LTS |
| Browser | Chromium Version 88.0.4324.96 (Official Build) snap (64-bit) |

**Comment by Shannor** [comment]
Yep can confirm. Saw this same issue this morning when I updated to the latest antd at `4.12.2`. Is the solution to downgrade to `4.8.2` for the time being?

**Comment by linxux** [comment]
Hi @Shannor, rollback to your previous version should work.

**Comment by TrueMoein** [comment]
Downgrade to `4.11.2` should fix it.

**Comment by zombieJ** [comment]
Additional padding of Row by `gutter` is not by design. It's caused that we use negative margin of Row and padding of Col to realize the visual effect. We move to `flex-gap` style in recent version. You can still provides padding style of Row if need this padding effect.

ref https://github.com/ant-design/ant-design/pull/29059

**Comment by linxux** [comment]
@zombieJ Aha?! Not by design?

[Grid Gutter](https://ant.design/components/grid/#components-grid-demo-gutter)

```
You can use the gutter property of Row as grid spacing, we recommend set it to (16 + 8n) px (n stands for natural number).

You can set it to a object like { xs: 8, sm: 16, md: 24, lg: 32 } for responsive design.

You can use a array to set vertical spacing, [horizontal, vertical] [16, { xs: 8, sm: 16, md: 24, lg: 32 }].
```

Not quite understand.
So is it a breaking change? Maybe the component document need to be updated.

**Comment by vorlov** [comment]
its a breaking change and should be listed on changelog. how should we add padding at the bottom as of now?

**Comment by bn3t** [comment]
Breaking change also for me, please reopen. It seems I have to revert up to 4.10.3 to have work again.

**Comment by JoeCMorgan** [comment]
Breaking change for me also, we used hundreds of rows/cols in our application. I shouldn't have to go through each one and manually set the padding, what's the correct fix? @zombieJ

**Comment by JoeCMorgan** [comment]
Also, just to confirm that we doing the following everywhere

```
<Row gutter={[12, 24]}>
    <Col span={12}></Col>
</Row>
```

and the vertical spacing on the row is only intermittently being set, 9 times out of 10 I don't see any vertical padding, but after a few refreshes it appears. Obviously that isn't acceptable.

**Comment by JoeCMorgan** [comment]
@afc163 @zombieJ  any update on this please?

**Comment by mixj93** [comment]
Breaking change for me! Almost every page broken, downgrade to `4.11.2` works.

**Comment by MyCupOfTeaOo** [comment]
Why is it not written in the change log

**Comment by aashayamballi** [comment]
I just upgraded from 4.10.1 to the latest version 4.16.0and wherever grid is being used the vertical spacing is gone.. please help

**Comment by JoeCMorgan** [comment]
Shocking that there's still no update on this 😂  Looks like our temporary hardcoded padding fixes will have to be made permanent. Even just an acknowledgement would be better than ignoring every message.

**Comment by zombieJ** [comment]
antd change Row vertical gap from `margin + padding` mock to `flex gap` for fixing [margin issue](https://github.com/ant-design/ant-design/issues/28976). Normally Row is a layout component that we not recommend to patch too many style on it since it may break by responsive or other dynamic style change.

This change comes from [4.12.0](https://ant.design/changelog#4.12.0). Pls feel free to hack [styleChecker](https://github.com/ant-design/ant-design/blob/737c172c2bc598a253e87e6e438a74444a5b4b04/components/_util/styleChecker.tsx#L16) to disable the flex gap support to disable it.

**Comment by JoeCMorgan** [comment]
Thanks for getting back to us @zombieJ - however we shouldn't have to hack anything to get the grid layout working as expected. The issue that I believe most of us are facing is that it's intermittent, sometimes the padding exists and sometimes it doesn't. My guess would be that the `detectFlexGapSupported` method returns a different result each time. I'll have a check my end to see if it's an issue with how we're rendering our components and add my findings to this thread. 

Again, thanks for getting back to us, it's good to know that there's support available for this issue.

**Comment by zombieJ** [comment]
With the development of front-end technology, the implementation of some hacks in the past has gradually used new methods to achieve. `detectFlexGapSupported` as what browser really support is what we want. It's little tricky if official provide a way to disable this check.

**Comment by JoeCMorgan** [comment]
@zombieJ Thanks for getting back to me. In our case it looks as though sometimes (on the newest version of Chrome) that functions returns false, and sometimes it returns true. When it returns false, the paddings/margins are all wrong. Could you point me to where this function actually gets called?

Also, I think the main issue that people aren't happy with is that whether that function returns true or false, it shouldn't break the layout of the grid. The Ant framework should have checks in place to ensure that the grids look identical over all browsers, regardless of whether that browser supports flex row gap.

**Comment by zombieJ** [comment]
For the `sometimes return true & false`, it's always return false at first mount since SSR env do not support flex layout. The flex gap check is trigger `useEffect`.

Grid component is design to help simplify the layouting. It's not expect to patch much style on the Grid component but use customize node instead:
```tsx
<Row style={{}}>
  <Col style={{}} />
</Row>
```

to

```tsx
<div style={{}}>
  <Row>
    <Col>
      <div style={{}} />
    </Col>
  </Row>
</div>
```

We also meet some feedback when move v3 to v4 by using flex layout instead of float layout. It breaks user who put something in Row directly like:
```tsx
<Row>
  <div style={{}} />
</Row>
```

We try to avoid breaking official documents under minor versions, but for some unexpected usage, we can only try to keep compatibility as much as possible. It is difficult to achieve a perfect balance, but for new features that can solve bugs and stay the same, we will prefer the former. If really don't want to inject the method, choose the locked version maybe the last choice.

**Comment by JoeCMorgan** [comment]
Thanks @zombieJ - the fact that it always returns false on the first render is our biggest issue. This [if statement](https://github.com/ant-design/ant-design/blob/737c172c2bc598a253e87e6e438a74444a5b4b04/components/_util/styleChecker.tsx#L21) checking if the value exists never allows the first render to return true, and therefore always messes up the layout. Is there anything that can be done to fix this, without hacking the fix into the stylechecker?

**Comment by monolithed** [comment]
<img width="973" alt="Screenshot 2023-07-10 at 01 19 12" src="https://github.com/ant-design/ant-design/assets/803674/916b464f-ff3c-4cd3-b5f9-9949d87a3598">

@zombieJ I can't use Row/Col at all because when I set the gutter property, extra spaces are added. This happens when I change the direction of Row through CSS. It occurs because instead of using gap for horizontal spacing, padding-left and padding-right are used. This is very archaic and it's unclear why it was done that way.
