### ISSUE TITLE
[Pagination] Jump button shouldn't always be active

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#29882]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gengduo-antd4141-forked-lzjts)

### Steps to reproduce
Click the jump next button and move our mouse away from it after jumping.
![Kapture 2021-03-23 at 21 48 52](https://user-images.githubusercontent.com/50612752/112156858-9b2a9280-8c21-11eb-9126-9fd1a88be1d4.gif)

### What is expected?
The jump button should be inactive until we hover on it.

### What is actually happening?
The jump button keep active even we have moved mouse away.

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by 87182485** [comment]
Hi, I am new here.
After spend sometime on this one, I found the root cause of this problem is the dependency `rc-pagination` Ant is using, after click the jumper, the jumper button is set focused automatically, and it would be easier to overwrite onClick event on `rc-pagination` side to make that happen I believe.

**Comment by kerm1it** [comment]
@87182485  We only need to remove style of focus state, welcome to PR
