### ISSUE TITLE
date-fns DatePicker format bug when typing in the date input

### ISSUE THREAD

**Issue by mk-nickyang** [ant-design/ant-design#30097]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1znqw)

### Steps to reproduce
1. Type `01/01/2021` in the date input
2. `01/01/0002021` is entered instead

See [![Image from Gyazo](https://i.gyazo.com/8ebba70acb3619b8a2c52c74803c61e5.gif)](https://gyazo.com/8ebba70acb3619b8a2c52c74803c61e5)

### What is expected?
`01/01/2021` should be entered in the date input

### What is actually happening?
`01/01/0002021` is entered is the date input

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.1 |
| System | macOS Big Sur 11.2.3 |
| Browser | Chrome 89.0.4389.114 |

**Comment by appleshell** [comment]
The reason is the result of `parse('01-01-2', 'dd-MM-yyyy', new Date())` is `Tue Jan 01 0002 00:00:00`, and it is a valid date. The `parse` is a method of `date-fns`. click [here](https://github.com/appleshell/picker/blob/master/src/generate/dateFns.ts#L103).
so you can use `rc-picker/lib/generate/moment` rather than `rc-picker/lib/generate/dateFns` to solve the prolbem. @afc163 @mk-nickyang

**Comment by mk-nickyang** [comment]
@appleshell Thanks for pointing out the reason mate.

But replacing `date-fns` with `moment` or `dayjs` doesn't really _solve_ this problem, and I believe most people who switched from `moment` to `date-fns` would prefer not to go back

**Comment by mk-nickyang** [comment]
Actually, I just found a simple workaround that stops leading zeroes being added to date input when typing year.

Instead of using the `yyyy` pattern,
```
<DatePicker format="dd/MM/yyyy" />
```

just using `y` will do the trick
```
<DatePicker format="dd/MM/y" />
```

**Comment by parkeunae** [comment]
I have the same problem with dayjs.
In a RangePicker with time selection, the same problem occurs when entering the time. 😢

**Comment by KathrynArmitage** [comment]
Adding the y instead of yyyy does fix the leading the typing zeros...however when you delete the year it deletes below in the actual date picker leaving 000s there until you type in the year again...aka May 0002.

<img width="367" alt="Screenshot 2023-03-21 at 11 08 49" src="https://user-images.githubusercontent.com/47405136/226589302-8e06c375-f21f-426e-98b7-4dda9257a07e.png">
