### ISSUE TITLE
arrow in collapse not working correct with flex header node

### ISSUE THREAD

**Issue by akaguny** [ant-design/ant-design#30722]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapse-reproduce-bug-antd4160-forked-sl4ro?file=/index.css)

### Steps to reproduce
open example preview

### What is expected?
header rendered block positioning with arrow on one line
![image](https://user-images.githubusercontent.com/3505959/119770135-7920eb00-bec4-11eb-885f-8841202ac690.png)

### What is actually happening?
header rendered block positioning on another line
![image](https://user-images.githubusercontent.com/3505959/119769973-319a5f00-bec4-11eb-88a8-f8a77b35d261.png)

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 16.14.0 |
| System | Windows |
| Browser | Chrome |

---
this was broken with https://github.com/ant-design/ant-design/commit/cf342de7cf461b3edf9e5a2c5be295e90c1436c9

**Comment by JonathanLeeWH** [comment]
Agreed I have also encountered the same issue. I think this was from the latest `antd 4.16.0` as from the codesandbox `antd 4.15.6` did not have the issue.

I think @akaguny reproduction link is showing dependency `antd 4.15.6` which showed the expected result rather than the bug behaviour (I might be mistaken). I have updated the link below with `antd 4.16.0` where the difference between actual and expected can be seen to avoid confusion.

### Reproduction Link

#### In the latest antd@4.16.0 where the bug can be seen:
[![The collapse reproduce bug in antd@4.16.0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapse-reproduce-bug-antd4160-forked-ojsvq?fontsize=14&hidenavigation=1&theme=dark)

#### In the previous antd@4.15.6 where it behaves as expected result mentioned by @akaguny:
[![The collapse reproduce expected result in antd@4.15.6](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapse-reproduce-bug-antd4160-forked-sl4ro?fontsize=14&hidenavigation=1&theme=dark)

**Comment by JonathanLeeWH** [comment]
@afc163 对不起关于以上的问题 (collapse component) 是不是bug?

**Comment by afc163** [comment]
We can't guarantee compatibility of custom styles, in this case, you may have to do it this way: https://codesandbox.io/s/collapse-reproduce-bug-antd4160-forked-0txzc?file=/index.css

**Comment by JonathanLeeWH** [comment]
@afc163 Thank you for the prompt reply. Actually my issue is slightly different as mine was grouping of different typography components from antd in the header property of collapse's panel component but led to the same behaviour not present in previous version of antd but I have resolved it with custom css.

Thank you for your help. Appreciate it.

**Comment by akaguny** [comment]
thanks @afc163 and @JonathanLeeWH 
But i think that previous position implementation was taken some logic from programmer to component and i don`t think about it when use component.
