### ISSUE TITLE
table summary's fixed props is not work in function component

### ISSUE THREAD

**Issue by flyingCrp** [ant-design/ant-design#30864]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zongjielan-antd4161-forked-i4xg9?file=/index.js)

### Steps to reproduce
just look that link

### What is expected?
the fixed props is work

### What is actually happening?
not work

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | last |
| System | win10 |
| Browser | chrome  |

---
confused me

**Comment by zombieJ** [comment]
Table.Summary is a syntactic sugar which mean it do not support HOC. Thought we have the ability to get config by context, it will cause additional render to collecte config data. Before strongly feedback requirement, we may not apply this.

ref https://github.com/react-component/table/blob/master/src/Table.tsx#L391

**Comment by mdogadailo** [comment]
@flyingCrp the problem is only with component type validation, where it expects Table.Summary
https://github.com/react-component/table/blob/master/src/Table.tsx#L411

Your code is suppose to work if Table.Summary will be first in summary, not in **CstSummary** 
```javascript
const CstSummary = () => {
  return (
      <Table.Summary.Row>
        <Table.Summary.Cell index={0}>Summary</Table.Summary.Cell>
        <Table.Summary.Cell index={1}>
          This is a summary content
        </Table.Summary.Cell>
      </Table.Summary.Row>
  );
};

<Table
  summary={() => <Table.Summary fixed><CstSummary /></Table.Summary>}
/>
```

It is even possible to force it work when remove validation on type, 
```
summaryNode.type === Summary && (summaryNode.props as SummaryProps).fixed;
```
but still how you gonna pass **fixed** argument, because summary can be **not fixed**. 

@zombieJ maybe it make sense to find summaryNode in children of what passed to summary and ignore everything before it? 

```javascript
  summary={() => <><Table.Summary fixed><CstSummary /></Table.Summary></>}
```
