### ISSUE TITLE
[RangePicker] When only the end date is selected, it hopes to display the end date in the right panel

### ISSUE THREAD

**Issue by AsakuraC** [ant-design/ant-design#31100]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[demo](https://codesandbox.io/s/xuanzebuchaoguoqitiandefanwei-antd4163-forked-nzyyv?file=/index.js)

When I only select the start date, the situation is as follows 

![2021-06-23 14-44-01 2021-06-23 14_44_23](https://user-images.githubusercontent.com/18549833/123048953-93050d80-d431-11eb-9a46-660d8242d8a9.gif)

But When I select the end date, it's behavior is inconsistent

![2021-06-23 12-00-04 2021-06-23 12_00_42](https://user-images.githubusercontent.com/18549833/123047420-da8a9a00-d42f-11eb-9dc2-26de92b06359.gif)

### What does the proposed API look like?
hope to display the end date in the right panel

**Comment by AsakuraC** [comment]
I hope it performed like this

![2021-06-23 14-50-17 2021-06-23 14_50_37](https://user-images.githubusercontent.com/18549833/123050001-c4320d80-d432-11eb-96b5-9d8600ba3917.gif)

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
