### ISSUE TITLE
Providing open=flase in TimePicker prevent to set a value to it

### ISSUE THREAD

**Issue by lxtadhamnawito** [ant-design/ant-design#31158]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-q2q1vp?file=index.js](https://stackblitz.com/edit/react-q2q1vp?file=index.js)

### Steps to reproduce
Set the open attribute to false for the TimePicker to hide the dropdown list.

### What is expected?
Hiding the dropdown list and being able to set the time manually.

### What is actually happening?
The dropdown list is hidden successfully, but I'm not able to set any value to the TimePicker anymore.

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | ^16.13.1 |
| System | Windows 10 |
| Browser | Chrome |

---
It should work with and without the dropdown list, as I might need to hide it from the user to avoid confusing him from selecting from dropdown or setting manually.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
