### ISSUE TITLE
Date picker custom date format is not applied to tooltip that appears on hovering on a date

### ISSUE THREAD

**Issue by nameishari** [ant-design/ant-design#31339]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/?locale=en-US#header](https://ant.design/components/date-picker/?locale=en-US#header)

### Steps to reproduce
1) Create a date picker with a custom date format
2) Open the date picker
3) Hover on a date
4) wait for a tool tip to appear

### What is expected?
Tool tip should show the custom date format

### What is actually happening?
Tool tip shows the default ISO format

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | macOS Big Sur 11.3.1 |
| Browser | Chrome Version 91.0.4472.114 |

---
I'm happy to submit a pr if you think that this needs to be fixed.

**Comment by nameishari** [comment]
Hi @afc163, I create a Draft PR on how I would do it. If you like my proposal/approach, then I will create tests and edit docs. Waiting for your feedback.

PR: https://github.com/react-component/picker/pull/273

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
