### ISSUE TITLE
DatePicker 手动录入数据，失焦无法保存

### ISSUE THREAD

**Issue by rabbitbiubiubiu** [ant-design/ant-design#31691]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/date-picker-cn/](https://ant-design.gitee.io/components/date-picker-cn/)

### Steps to reproduce
实例demo也无法录入之后视角保存

### What is expected?
失焦可以保存

### What is actually happening?
DatePicker 手动录入数据，失焦无法保存

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 16.13.1 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
目前的交互需要回车保存。

**Comment by rabbitbiubiubiu** [comment]
> 当前的交互需要回车保存。

可是对于用户来说，失焦保存会有更好的体验

**Comment by KAROTT7** [comment]
我这边也希望是失焦保存

**Comment by fengyun2** [comment]
我这边的业务也是希望是失焦保存，或者支持配置是否是失焦保存配置

**Comment by fengyun2** [comment]
antd@3.x版本也是默认失焦保存的

https://3x.ant.design/components/date-picker-cn/#API

**Comment by phoema** [comment]
我这边客户也提出来了，失去焦点默认选中，并且客户给了我一份其他组件的功能，说这个组件可以
![image](https://user-images.githubusercontent.com/8730272/134639835-e6faab23-955b-48ce-ba67-84318ee3ca39.png)

**Comment by blackcorgi** [comment]
我想到的临时方案是增加onOpenChange事件在面板关闭时，获取组件下input元素的value值。验证有值，且不等与当前值，做时间格式验证再赋值给组件。

**Comment by sun90581737** [comment]
这个问题 有什么样的方案？

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
