### ISSUE TITLE
DatePicker clear value when mouse up

### ISSUE THREAD

**Issue by wangzongming** [ant-design/ant-design#31799]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/date-picker-cn/](https://ant-design.gitee.io/components/date-picker-cn/)

### Steps to reproduce
在选择页面上面的文字时，鼠标移动到输入框右侧清除按钮上，然后放开，输入框中的日期就会被清除掉。

### What is expected?
希望改成监听点击清除按钮后才监听鼠标放开的事件，而不是在网页上随便点击都可以清除值

### What is actually happening?
清除操作更加严谨

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 17.0.1 |
| System | win 10 |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/react-component/picker/pull/35

@zombieJ 看看为啥这里要用 onMouseUp 而不是 onClick。

**Comment by zombieJ** [comment]
原本是 mouseDown 会触发开窗，所以把事件后移到 mouseUp 里。看了变更感觉是当时不想把什么东西冒上去，可以改成 onClick 试试。

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
