### ISSUE TITLE
Can not trigger message.destory(key) when the prefixCls has set

### ISSUE THREAD

**Issue by yanqing6628780** [ant-design/ant-design#31910]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9oz4r?file=/index.js)

### Steps to reproduce
Click the button the messages were showed, the onClick event was trigger, but the destroy method didn't execute.
However, if the prefixCls param was removed, the onClick logic was worked, the messages can be destroy

### What is expected?
I can add customize the message style and can destroy the message by onClick event.

### What is actually happening?
The destroy method with key didn't work

| Environment | Info |
|---|---|
| antd | 4.15.6 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
Because it's waiting for leave animation:

<img width="759" alt="截屏2021-09-13 下午5 34 18" src="https://user-images.githubusercontent.com/5378891/133060607-785f591c-a709-4c9c-ae18-36d31f2ee9af.png">

When you change the `prefixCls`, you should either add animation css or remove `transitionName` to disable animation.
