### ISSUE TITLE
Provide option to not clear an invalid date in DatePicker

### ISSUE THREAD

**Issue by mellis481** [ant-design/ant-design#32475]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Clearing user input (in this case, an invalid date) rather than retaining the date and providing error messaging informing the user of the invalid value is arguably a bad user experience.

### What does the proposed API look like?
It would seem a new property for the common date picker API would be required.  Something like `allowInvalidValue` which would be a boolean and have a default value of `false`.  Additionally changes would be needed I assume.

**Comment by mellis481** [comment]
I believe it would take an automation tool to create a code example.  Alternatively, here is a video of it occurring:

![ezgif-6-f5a4726bac58](https://user-images.githubusercontent.com/39313898/137320241-327d09c0-0377-46ae-9462-b6664a84c421.gif)

Is this satisfactory?  It's simply the default behavior for DatePicker when an invalid date is entered and the field blurs.

**Comment by dgreene1** [comment]
I'm sharing this cartoon because it illustrates how dangerous and strange it is to let users type the date into the date picker. If it was an accessible solution, my preference would be to just disable the ability to type into the field. However, I imagine it's really useful to type it in when motor impaired users are using the widget. So that's why I think this ticket should be treated as a feature request where we consider what the ideal behavior is when a user types in a date that is not the correct format. My proposal is to show an error with aria-alert or to provide a callback that allows anyone to choose what they want to do.

![image](https://user-images.githubusercontent.com/14020024/148841295-82405b68-9ce1-49b2-b6d4-3942c60125ff.png)
citation: https://xkcd.com/2562/

**Comment by IvanLuLyf** [comment]
> @zombieJ It would take an automation tool to demonstrate it in an example. It's simply how every instance of a DatePicker behaves when an invalid date is entered and the field blurs.
> 
> Also, why would I need a repro for a feature request?
> 
> In any event, here is a video of it occurring:
> 
> ![ezgif-6-f5a4726bac58](https://user-images.githubusercontent.com/39313898/137320241-327d09c0-0377-46ae-9462-b6664a84c421.gif) [ ![ezgif-6-f5a4726bac58](https://user-images.githubusercontent.com/39313898/137320241-327d09c0-0377-46ae-9462-b6664a84c421.gif) ](https://user-images.githubusercontent.com/39313898/137320241-327d09c0-0377-46ae-9462-b6664a84c421.gif) [ ](https://user-images.githubusercontent.com/39313898/137320241-327d09c0-0377-46ae-9462-b6664a84c421.gif)

Is this effect https://codesandbox.io/s/antd-reproduction-template-forked-yljhp8?file=/index.js?

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
