### ISSUE TITLE
component select coordinate - First select option is blank when using an array of objects

### ISSUE THREAD

**Issue by josephdempsey** [ant-design/ant-design#32925]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

Following example here - https://ant.design/components/select/

### Reproduction link
[https://codepen.io/joekaren17/pen/RwZEXEd?editors=0010](https://codepen.io/joekaren17/pen/RwZEXEd?editors=0010)

### Steps to reproduce
First select providence on the left.
Then select area on the right dropdown.
The select option does not appear to be selected

### What is expected?
Selected option should appear appear to be selected

### What is actually happening?
select option does not appear not appear to be selected

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | Mac |
| Browser | Chrome |

**Comment by AlexeyAbramov** [comment]
Hey, @josephdempsey . This is because the first time you take "1" from the "area" of the "secondCity" object, and when you change, you put it in the "secondCity" value (1,2,3, etc.). As a result, in "secondCity" you have not an object {area: 2}, but 2.
setSecondCity ({area: value}); for your example. Sorry for my english. GL ;)

**Comment by josephdempsey** [comment]
Thanks all sorted now. 👍
