### ISSUE TITLE
响应式栅格可否增加1920的尺寸？

### ISSUE THREAD

**Issue by fynh518** [ant-design/ant-design#32954]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前的响应式栅格xxl 是≥ 1600px，但是现在好多1920的屏幕有好多，2560的也有很多，从1920到2560直接是否也加一下，例如加一个xxxl的尺寸是>=2000

### What does the proposed API look like?
xxxl: >=2000px

**Comment by tangjinzhou** [comment]
参考这个来个 PR ？    https://github.com/vueComponent/ant-design-vue/pull/4953

**Comment by azro352** [comment]
@afc163 Hi, what's the status regarding this feature ? 

That would be SUPER useful to differenciate half-screen of full-screen on 4k screens

Would a nice PR about that (inspired from the https://github.com/vueComponent/ant-design-vue/pull/4953 one) have a change to included in a release ? I don't want to write the PR and then waiting for months to be used because there is other priorities :)
Thanks !

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/39105
