### ISSUE TITLE
TreeSelect Search not working

### ISSUE THREAD

**Issue by vadymhimself** [ant-design/ant-design#33323]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select/#examples](https://ant.design/components/tree-select/#examples)

### Steps to reproduce
Use treeCheckable: true, type any search

### What is expected?
Checkable items filtered to match the search query

### What is actually happening?
No data

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Mac OS |
| Browser | Chrome |

**Comment by thisrabbit** [comment]
Hi, I humbly believe that it is simply because that [demo](https://ant.design/components/tree-select/#components-tree-select-demo-checkable) does not implement a customized `filterTreeNode` function so that `TreeSelect` component will use it's children's `value`(by default, which was initialized with pattern like `0-0`) rather than displayed `title`, and thus of course it will filter nothing if you search `nodexxx`, actually search with `0-0` will indeed return some certain nodes.

**Comment by thisrabbit** [comment]
@vadymhimself So it is more a doc issue rather than code issue~

**Comment by dongyuwei** [comment]
set `reeNodeFilterProp` prop, eg: ` <TreeSelect reeNodeFilterProp="label" />`
