### ISSUE TITLE
onClear triggers onDeselect for all selected values

### ISSUE THREAD

**Issue by Kn3cht** [ant-design/ant-design#33790]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sizes-antd-4-18-4-forked-9e5vo?file=/index.js)

### Steps to reproduce
1. Create a Select element with mode `multiple`, the flag `allowClear` and multiple selectable options
2. Implement `onSelect`,  `onDeselect` and `onClear`
3. Select multiple options
4. Click on the clear button

### What is expected?
The on clear button should only execute `onClear`.

### What is actually happening?
`onClear` gets called first then for each selected value `onDeselect` is called.

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | 18.0.0-rc.0 |
| System | Kubuntu 21.10 |
| Browser | Chrome 96.0.4664.110 (Official Build) (64-bit) |

---
Expected behavior works for antd v4.17.3

**Comment by heiyu4585** [comment]
@afc163 这个不算bug吧,onClear代码逻辑应该就是通过 `onDeselect` 实现的

rc-select/src/BaseSelect.tsx:685
```
  // ============================= Clear ==============================
  let clearNode: React.ReactNode;
  const onClearMouseDown: React.MouseEventHandler<HTMLSpanElement> = () => {
    onClear?.();

    onDisplayValuesChange([], {
      type: 'clear',
      values: displayValues,
    });
    onInternalSearch('', false, false);
  };
```

**Comment by duuliy** [comment]
There is no conflict between the two. When you clear the content, you can also trigger deselection, which is no problem

**Comment by xrutayisire** [comment]
Hello, 

Same problem here. Since v4.18.0, onDeselect is called when onClear is triggered. 

If this is wanted it should be considered a breaking change and documented. It's a huge difference when you override these functions.

But for me, it's a bug. onClear should not call onDeselect. If someone wants to trigger something for onClear AND onDeselect it's easy to do it in both function. But now that onClear trigger onDeselect you cannot prevent both function to be executed. It should be reverted or at least a param should be given to onDeselect, so it's possible to know when to change the behavior because it's onClear. 

Btw, the library I created now have a bug because of this: https://github.com/xrutayisire/react-js-cron/issues/18 😢 

I hope this can be fixed soon 😃 

Happy to help if needed!

**Comment by xrutayisire** [comment]
Hello,

Following my last comment, do tou think someone could take a look at this?

Have a good day!

**Comment by SCWR** [comment]
@afc163  请问有进展吗

**Comment by Witee** [comment]
下面的方式可以实现清空和取消选择同时使用:

```javascript
const [ids, setIds] = useState([]);

const onDeselect = (id) => {
    // onClear时会多次调用, 由于 useState 是异步更新, 所以这里要利用 useState 的函数式更新功能, 
    // 因为 prevState 是上次更新后的值
    setIds((prevState) => [... prevState.filter(i => i !== id)]);

    // 如果直接使用下面的方法, 则在 onClear 时只会删除掉最后一个
    // setIds([...ids.filter(i => i !== id)])
}

// 通过多次调用 onDeselect 实现清空
const onClear = () => {
    setIds([])
}

```

**Comment by Kn3cht** [comment]
Are there any updates on when it will be merged?
