### ISSUE TITLE
Tooltip trigger=["focus", "hover"] does not work properly together

### ISSUE THREAD

**Issue by pobch** [ant-design/ant-design#34064]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-river-r4jpu?file=/src/App.js)

### Steps to reproduce
1. Go to https://codesandbox.io/s/musing-river-r4jpu?file=/src/App.js
2. Click the second input
3. Move the mouse out of the input

### What is expected?
After step 3, the Tooltip should still be shown since we use `trigger=["focus", "hover"]` as a prop in Tooltip.

### What is actually happening?
The second Tooltip only works in `hover` mode, not `focus` mode.

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | 17.0.2 |
| System | mac os 12.1 |
| Browser | Firefox 96 |

**Comment by zombieJ** [comment]
Discussed about this case. Current behavior is work as expect. any of `trigger` reach hide condition should makes tooltip hide instead of each condition reach hide.

For example, if config `trigger={['hover', 'click']}`, user mouse enter and show the tooltip. User click on the content and then mouse leave. If all the condition takes into count, click to open is true but user can not aware this. They only see that mouse enter to show and mouse leave not hide.

Similar to `['focus', 'hover']`, when user mouse enter and click to get focus, they found tooltip show expected by `hover` but not aware of `focus`. When mouse leave but not lose focus, the tooltip still exist will make confuse.

If want to all the condition should keep to show, my suggestion is to HOC for counter. But origin Tooltip component will no handle this.
