### ISSUE TITLE
clearFilters is not working on Table component

### ISSUE THREAD

**Issue by smoudenwa** [ant-design/ant-design#34109]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-custom-filter-panel](https://ant.design/components/table/#components-table-demo-custom-filter-panel)

### Steps to reproduce
Add a filter on the 'Name' column for example. 
Click on Search button to apply the filter
Click on Reset button to clear the filter

### What is expected?
Filter should be cleared, and the table data should be back to default

### What is actually happening?
Filter is cleared but the table data don't change

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | 17 |
| System | Windows |
| Browser | Chrome |

---
Link to CodeSandbox example : https://codesandbox.io/s/hi7fs 
Working example on 3.X : https://3x.ant.design/components/table/#components-table-demo-custom-filter-panel

**Comment by qcxiaoshuai-snake** [comment]
今天早上突然客户说 表格上的列重置不好用了，
于是就打开代码测试，发现ant design Table的里的也不好用了（如下图）
![image](https://user-images.githubusercontent.com/54222132/154612967-9ef09f17-10d0-472a-91ce-02172edf146f.png)
这就很崩溃了，跟领导说是Antd的问题，但是领导不管这么多啊，客户还等着用，打算上来提个issue, 发现已经有人提了这个问题，我用的版本也是Antd4.x的版本

也看到了 楼上说的
Since 4.17.0 we introduced filterSearch into table, and clearFilters didn't trigger table change anymore.
We should provide clearFilters({ confirm: boolean }) to cover the missing feature.
这个，也尝试了clearFilters({ confirm: boolean }) 这个  clearFilters({ confirm: false }) 和 clearFilters({ confirm: true }) 均无效
也是很崩溃了，后来一想 clearFilters() 不好用，但是confirm()好用啊，就尝试了用confirm() 发现好用了，但是要组合用，如下图当我点击重置的时候 要组合调用（下图 红色 框内的标记）

不管是你用的是ProTable 还是 antd4.x的 Table 下面的重置方法 都可以

![image](https://user-images.githubusercontent.com/54222132/154613354-512beacf-0eb5-4f1e-9c6c-a31f6895148d.png)

最后，如果官网修复了这个bug 还是要改回去的

**Comment by qcxiaoshuai-snake** [comment]
@heiyu4585 贴代码呗

**Comment by heiyu4585** [comment]
> @heiyu4585 贴代码呗



> @heiyu4585 贴代码呗

稍等,方案确认,reviewer通过后,我贴

**Comment by fabripeco** [comment]
Maybe it will be useful to have this feature not only for the custom filter dropdown, but also for the filters integrated in the header (see https://ant.design/components/table/#components-table-demo-head) . Click on 'Reset' doesn't trigger the confirmation (as in antd 3.x), but it resets only the selected checkboxes. Is the intended behavior?

![image](https://user-images.githubusercontent.com/11854441/155144245-f85aa09a-3191-48d8-bf25-7dc43bbf3691.png)

Thank you!!

**Comment by d9k** [comment]
thanks to @qcxiaoshuai-snake.

[Custom filters demo](https://ant.design/components/table/#components-table-demo-custom-filter-panel) code should be changed from

```
          <Button onClick={() => this.handleReset(clearFilters)} size="small" style={{ width: 90 }}>
            Reset
          </Button>

// . . . .

  handleReset = clearFilters => {
    clearFilters();
    this.setState({ searchText: '' });
  };
```

to

```
          <Button onClick={() => this.handleReset(clearFilters, confirm)} size="small" style={{ width: 90 }}>
            Reset
          </Button>

// . . . .

  handleReset = (clearFilters, confirm) => {
    clearFilters();
    confirm();
    this.setState({ searchText: '' });
  };
```
