### ISSUE TITLE
DatePicker.RangePicker设置defaultOpen需要选择两次开始日期

### ISSUE THREAD

**Issue by zhangyuanyuan828** [ant-design/ant-design#35239]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-datepicker-rangepicker-defaultopen-j8dl2v?file=/src/App.tsx)

### Steps to reproduce

进入页面，**不要点击输入框**，直接去选择日期，需要选择三次，开始日期选择后选择结束日期然后又会回到选择开始日期

### What is expected?

选择开始和结束日期后就关闭选择框，而不是再去选择一次开始日期

### What is actually happening?

开始日期选择后选择结束日期然后又会回到选择开始日期

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 18.0.0 |
| System | Windows10 |
| Browser | Chrome 87 |

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/24083

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
