### ISSUE TITLE
Added Expand All Button to expand all sub-table or row in antd Table

### ISSUE THREAD

**Issue by kevinladani9151** [ant-design/ant-design#35300]
### What problem does this feature solve?

In this feature we can only expand single row at a time not all row expand by clicking on one button Expand All.
https://codesandbox.io/s/my02ok19wy

### What does the proposed API look like?

In this feature we can only expand single row at a time not all row expand by clicking on one button Expand All.

**Comment by afc163** [comment]
You can add button outside Table to control expandedKeys of Table.

**Comment by kevinladani9151** [comment]
Give me code or live example for this

**Comment by kevinladani9151** [comment]
> ### You may look for issues:
> 1. 51% [andt table - load table scrolled to a column based on tag clicked #33885](https://github.com/ant-design/ant-design/issues/33885)
> 
> 🤖 By [issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis)

no i am talking about Expand all button for expand all row at a same time, not for individual.

**Comment by abneed** [comment]
I know this issue is from 2 years ago, but I want to provide the solution for that old question:

You need to play with expandable.onExpand and expandable.expandedRowKeys to be able to implement the "Expand All" and "Collapse All" buttons.

I'm adding here the code snippet solution to ge able to expand/collapse all the rows (even the nested ones) with just one click:

https://codesandbox.io/p/sandbox/j9tjny

The Ant Design version using from this solution is "5.0.6", but is also compatible with the "4.24.16".
