### ISSUE TITLE
How to Expand All Row in antd table By clicking on single button.

### ISSUE THREAD

**Issue by kevinladani9151** [ant-design/ant-design#35302]
### What problem does this feature solve?

In Below example How to add single button to expand all row at a same time instead of clicking on single row button.
https://codesandbox.io/s/my02ok19wy

### What does the proposed API look like?

Here https://codesandbox.io/s/my02ok19wy single row expand is working fine but how can i added single button to expand all rows at a time.

**Comment by zombieJ** [comment]
Use `expandedRowKeys`

**Comment by kevinladani9151** [comment]
> 

why you r close my issue without any solution. if its done ten send me sample code ir live example bcoz above issues also not solved.

**Comment by abneed** [comment]
I know this issue is from 2 years ago, but I want to provide the solution for that old question:

You need to play with `expandable.onExpand` and `expandable.expandedRowKeys` to be able to implement the "Expand All" and "Collapse All" buttons.

I'm adding here the code snippet solution to ge able to expand/collapse all the rows with just one click:

https://codesandbox.io/p/sandbox/j9tjny

The Ant Design version using for this "5.0.6", but is also compatible with the "4.24.16".

**Comment by abneed** [comment]
I know this issue is from 2 years ago, but I want to provide the solution for that old question:

You need to play with expandable.onExpand and expandable.expandedRowKeys to be able to implement the "Expand All" and "Collapse All" buttons.

I'm adding here the code snippet solution to ge able to expand/collapse all the rows with just one click:

https://codesandbox.io/p/sandbox/j9tjny

The Ant Design version using from this solution is "5.0.6", but is also compatible with the "4.24.16".

**Comment by abneed** [comment]
I know this issue is from 2 years ago, but I want to provide the solution for that old question:

You need to play with expandable.onExpand and expandable.expandedRowKeys to be able to implement the "Expand All" and "Collapse All" buttons.

I'm adding here the code snippet solution to ge able to expand/collapse all the rows (even the nested ones) with just one click:

https://codesandbox.io/p/sandbox/j9tjny

The Ant Design version using from this solution is "5.0.6", but is also compatible with the "4.24.16".
