### ISSUE TITLE
Bug: scroll={{ x: 'max-content', y: 'any-numberpx' }} don't work on Safari 15.4

### ISSUE THREAD

**Issue by Andreybest** [ant-design/ant-design#35504]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-meninsky-7qnu49?file=/index.js)

### Steps to reproduce

1. Create any table with columns that has different (and sometimes long) data
2. Add scroll prop to table with x: 'max-content'

### What is expected?

Columns get "auto-width" and all column fit all data in one row

### What is actually happening?

Columns not auto-fits and data being split in 2 rows

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 17.0.2 |
| System | macOS 12.3.1 |
| Browser | Safari 15.4 |

---
Happens only on Safari: 15.4. On any other browser (Chrome, Brave, Firefox, Edge)

**Comment by solitia7125** [comment]
use `x: "-webkit-max-content"` ?

**Comment by zombieJ** [comment]
Tested find `-webkit` prefix also not work.

<img width="948" alt="截屏2022-05-12 下午4 16 52" src="https://user-images.githubusercontent.com/5378891/168024729-e9fb1be5-9b8d-4454-af58-0090e94a5fa6.png">

I believe it's Safari bug since `max-content` is passed to style directly without magic. Please fire bug to Safari instead. and we can do nothing on component side.

**Comment by afc163** [comment]
Try `width: intrinsic`. https://github.com/ant-design/ant-design/pull/34415

**Comment by Andreybest** [comment]
@afc163, x: 'intrinsic' does not help
