### ISSUE TITLE
Customized filter panel "filterDropdown": press "Tab" not focus the next Input on the filter panel, trigger sort column when press "Enter" 

### ISSUE THREAD

**Issue by vietthanhbk1994** [ant-design/ant-design#36176]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-filter-panel-antd-4-21-3-forked-ui8zuu?file=/demo.js:1583-1595)

### Steps to reproduce

**Bug does not focus next input when pressing Tab.**

1. Click the Search icon on the header column
2. Press "Tab", Press "Tab" again

**Bug trigger sort when press Enter**
1. Click the Search icon on the header column
2. Press Enter

### What is expected?

1. Focus on the next input on "filter panel" when press Tab
2. Not trigger sort when press Enter

### What is actually happening?

1. See the focus on icon Search, focus on the next header column
2. Sort on the column is actived

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18.3.0 |
| System | Mac OS |
| Browser | Chrome version 102.0.5005.115 |

---
On "antd": "4.18.9" is working normal, but on higher version has bug

**Comment by afc163** [comment]
@vietthanhbk1994 @danielkov PR is welcome~

**Comment by danielkov** [comment]
I've narrowed the issue down to the following "feature" in `rc-dropdown`, which got pulled in with the update to said library ([see diff here - the line responsible is highlighted](https://github.com/react-component/dropdown/compare/v3.2.5...v3.3.2#diff-aa5abc92f943dd00e600b37f0270ea359ddcb5b735170d5ddcff9f4326eb6ce3R39)).

Ultimately the problem seems to be that `antd` wraps whatever you provide in `filterDropdown` in an `RcDropdown`, which isn't designed to have forms inside it.

Possible bugfixes are:
- Downgrade version of `rc-dropdown` - which isn't ideal and would not provide a continuous solution.
- Update `rc-dropdown` to remove `TAB` from the keys triggering close - also not ideal because it would be a regression to the happy flow of the normal use-case of this library
- Remove wrapping of the `filterDropdown` in `RcDropdown`, which means implementing and maintaining a similar component within `antd`
- Propose a PR to `rc-dropdown`, which adds the ability to switch this behaviour off and then update this in `antd` - this seems to be the best option so far

**Comment by jojoi05** [comment]
This problem appeared on version 4.20.2

> **Bug trigger sort when press Enter**

1. Click the Search icon on the header column
2. Press Enter

**Comment by hfknight** [comment]
I found a workaround solution to solve the sorting issue when pressing "Enter" by adding event.stopPropagation() to Input onPressEnter function.

 `<Input
     ...
     onPressEnter={(e) => { e.stopPropagation(); handleSearch(selectedKeys as string[], confirm, dataIndex);}}
     ...
  />`

It prevents the enter event from passing to the column, where pressing enter will trigger the column sorting.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/38393
