### ISSUE TITLE
RangePicker组件，选择开始时间后，面板退回上次选择的月份

### ISSUE THREAD

**Issue by AdonLee** [ant-design/ant-design#36251]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sgpus4?file=/index.js)

### Steps to reproduce

1. 开始时间选择08-16，面板停留在当前月份，选择结束时间，完成时间选择，正常。
2. 重新开始，选择一个10-16，面板跳回八月份

### What is expected?

选择开始时间后，面板停留在当前月份

### What is actually happening?

选择开始时间后，面板不会停留在当前月份

| Environment | Info |
| --- | --- |
| antd | 4.18.9 |
| React | 17.0.2 |
| System | windows 10 64 |
| Browser | Microsoft Edge Version 102.0.1245.44 (Official build) (64-bit) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/22471
https://github.com/ant-design/ant-design/issues/22351
https://github.com/ant-design/ant-design/issues/27898
https://github.com/ant-design/ant-design/issues/31100

看上去这些都是同类问题。

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
