### ISSUE TITLE
Table filter do not persist filter status when filter dropdown is visible

### ISSUE THREAD

**Issue by jochenshi** [ant-design/ant-design#36946]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interesting-snowflake-b7cgpr?file=/src/App.js)

### Steps to reproduce

1. click filter dropdown
2. click "reset" and wait

### What is expected?

the filter status will not change

### What is actually happening?

filter was recovered to the old status

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 18 |
| System | MacOS 12.3 |
| Browser | Chrome 103.0.5060.134 |

---
https://github.com/ant-design/ant-design/issues/10209
It seems that the problem is similar to this problem,  and is fixed in 3.x, but appears in 4.x now

**Comment by ablakey** [comment]
I seem to be reproducing this with Antd 5.

I have a managed filtered state that I provide the table.  When the filter dropdown is opened, these checkboxes are checked.  If a user unchecks one, but new data causes a table re-render, it resets what the user did.  There is no way to manage this sub-state (nor do we want to), given `onChange` is only called when the dropdown closes.

Ideally the filter dropdown remains stable if the `filteredValue` and `filters` properties are unchanged.

The issue appears to be a regression as it was addressed in https://github.com/ant-design/ant-design/issues/10209 but I don't see any handling of this logic in the Antd 5 code.

**Comment by ablakey** [comment]
Here is a working reproduction:   https://codesandbox.io/s/antd-reproduction-template-forked-hztkcg?file=/index.js

## Steps
1. Open the filter dropdown (top-right, tricky to see)
2. Check the filter item
3. Wait and observe that the item unchecks itself because the data updated.

This makes it very hard to adjust filters on dynamic data (eg. from WebSocket).  But if the `filters` and `filteredValue` haven't changed, the internal state of the checkboxes should remain stable. They should only reset if the user clicks `reset` or `Apply` or closes the dropdown or one of the dependent props changes.

**Comment by ablakey** [comment]
I have a fix for this that is in testing.  Will post tomorrow.
