### ISSUE TITLE
React 18 - the submenus have a flickering effect before hiding

### ISSUE THREAD

**Issue by leclerc91** [ant-design/ant-design#37160]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-menu-react-18-antd-4-22-6-forked-umtzxw)

### Steps to reproduce

The code (it is already created in the link above):
1. Add a Menu component
2. Among its items, add a submenu with 4000 children

The user behaviour:
3. Move the mouse over the submenu
4. Move the mouse out of the submenu

### What is expected?

The submenu should go away smoothly (without causing any visual artefacts) as it does in React 17.
https://codesandbox.io/s/antd-menu-react-17-antd-4-22-6-6p73ec?file=/index.js

### What is actually happening?

There is a kind of **flickering effect when the submenu goes away**.

One can see it clearly when the submenu has a very large number of items. But **it also does happen with a small number of items** when the "_CPU is overloaded or slow_" (To test it in chrome: Developer Tools -> Tab: Performance Insight -> Set CPU throttling to 6x slowdown)

| Environment | Info |
| --- | --- |
| antd | 4.22.6 |
| React | 18.2.0 |
| System | any |
| Browser | Chrome 104.0.5112.101 |

**Comment by leclerc91** [comment]
Animated gifs with the behaviours
React 18 (issue)
![antd-menu - react@18 - antd@4 22 6](https://user-images.githubusercontent.com/16676041/185608043-6fe94f7f-033f-4849-8023-04367dd91e9e.gif)

React 17 (works fine)
![antd-menu - react@17 - antd@4 22 6](https://user-images.githubusercontent.com/16676041/185607971-291b4efd-dcaf-40b8-bbd9-719519f8b960.gif)

**Comment by DHEERAJPRAKASH** [comment]
For me also the same issue arised but my configurations were:
  1. React 18
  2. Ant v3
  
The main reason for this is that Ant Design v3 uses a different rendering model than React 18. React 18 uses a concurrent rendering model, which allows multiple components to be rendered at the same time. Ant Design v3, on the other hand, uses a single-threaded rendering model, which means that only one component can be rendered at a time. This difference in rendering models can lead to problems when using Ant Design v3 with React 18.

If you are using Ant Design v3 with React 18, you may experience the following problems:

**Hydration errors:** When React 18 hydrates a page that was rendered with Ant Design v3, it may not be able to match the initial UI with the rendered UI. This can lead to hydration errors.

**Performance problems:** Using Ant Design v3 with React 18 can lead to performance problems. This is because Ant Design v3 is not optimized for concurrent rendering.

If you are experiencing problems with Ant Design v3 and React 18, you can try the following solutions:

Upgrade to Ant Design v4 or v5: Ant Design v4 is compatible with React 18.
Use a different UI library: There are many other UI libraries that are compatible with React 18. If you are not able to upgrade to Ant Design v4, you can try using a different UI library.

**Disable concurrent rendering:** If you are not using any of the features that require concurrent rendering, you can disable concurrent rendering in React 18. This will prevent the problems that can occur when using Ant Design v3 with React 18.

**Comment by leclerc91** [comment]
It has been resolved at least since the version 5.8.0 of antd.
