### ISSUE TITLE
Table的expandable中childrenColumnsName与rowExpandable都有时，不会调用rowExpandable

### ISSUE THREAD

**Issue by frankChungNL** [ant-design/ant-design#37208]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-y51dkm?file=/index.js)

### Steps to reproduce

1.同时配置表格的expandable中的childrenColumnsName和rowExpandable

### What is expected?

子表格的可展开按钮根据rowExpandable受控

### What is actually happening?

子表格的可展开按钮不受控

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 16.14.30 |
| System | macOS Monterey 12.3.1 |
| Browser | Google Chorme 104.0.5112.101（正式版本）（arm64） |

---
树形结构数据的子数据不存在时（空值或空数组），不显示对应行的展开按钮

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-e35jwm?file=/index.js

貌似 rowExpandable 目前都不会被调用，即使没有 childrenColumnsName

**Comment by afc163** [comment]
哦，rowExpandable 目前应该只针对 expandedRowRender 生效。

https://ant.design/components/table-cn/#components-table-demo-expand

**Comment by Teeoo** [comment]
在线等修复.

**Comment by Teeoo** [comment]
都快一年了这个还没修吗~

**Comment by bn3t** [comment]
It seems when the Table component is in tree mode some of the expandable properties are working and others not. I guess this issue is about that problem (the text is in Chinese and I don't understand it).
For instance, `expandedRowClassName` does not work like it does when the expandable is not a tree. It is probably because in the case of a Table tree, the expandable is just another row with some identation.

It is quite confusing that some properties of the expandable object are working and others not.

**Comment by frankChungNL** [comment]
https://github.com/react-component/table/pull/907#issuecomment-1330001498
won't fix
