### ISSUE TITLE
Modal.confirm这个方法用Promise控制延迟关闭时，快速点击是，当resolve的瞬间按钮loading消失的时机比弹窗销毁的时机快，导致按钮能再次点击到

### ISSUE THREAD

**Issue by zcy97** [ant-design/ant-design#37329]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/que-ren-dui-hua-kuang-antd-4-22-8-forked-06k1t3?file=/demo.js)

### Steps to reproduce

1：点击按钮
2：点击确定
3：在loading状态的按钮上快速点击

### What is expected?

先销毁弹框再取消loading

### What is actually happening?

先取消loading了导致未销毁之前还能触发到按钮的点击事件

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 17.0.2 |
| System | win10 |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
牛了。 。 。这都能被发现。看起来要关闭的时候加一个 disabled。

**Comment by Zixiaobowen** [comment]
Can i work on this?

**Comment by berber1016** [comment]
可以啊，上次需要写个test覆盖这种情况，我写了一下无法覆盖，就cancel了---- 回复的原邮件 ***@***.***>发送日期2022年09月29日 15:43 ***@***.***> 抄送人GEARLESS ***@***.******@***.***>主题Re: [ant-design/ant-design] Modal.confirm这个方法用Promise控制延迟关闭时，快速点击是，当resolve的瞬间按钮loading消失的时机比弹窗销毁的时机快，导致按钮能再次点击到 (Issue #37329)
Can i work on this?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ant-design/ant-design/issues/37329#issuecomment-1261892835",
"url": "https://github.com/ant-design/ant-design/issues/37329#issuecomment-1261892835",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by KangXinzhi** [comment]
> Reference

开发的怎么样了？要不我来试试

**Comment by KangXinzhi** [comment]
> Can i work on this?

开发的怎么样了？要不我来试试

**Comment by Wxh16144** [comment]
> > Can i work on this?
> 
> 开发的怎么样了？要不我来试试

我也尝试修复这个问题，解决倒是挺简单。主要卡在了测试用例如何去写的问题上 😂

**Comment by KangXinzhi** [comment]
> 倒是挺简单。主要卡在了测试用例如何去写的

我是用了一个计数器，刚开始默认数量为0，点击确认一下，数量加一，最后判断下数字是否等于1，这样的思路写的测试用例。

**Comment by berber1016** [comment]
> > 倒是挺简单。主要卡在了测试用例如何去写的
> 
> 我是用了一个计数器，刚开始默认数量为0，点击确认一下，数量加一，最后判断下数字是否等于1，这样的思路写的测试用例。

瞅瞅，我当时修复的时候也是卡到了用例上，尝试了一下实在是覆盖不了后又close了 😭

**Comment by zhengmenghuang** [comment]
5.1.0 const { modal } = App.useApp(); modal.confirm 还会复现

**Comment by BBBigCat** [comment]
4.24.13 还会复现
