### ISSUE TITLE
v5 ConfigProvider theme for components not working

### ISSUE THREAD

**Issue by HStokbro** [ant-design/ant-design#38825]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ler7t4?file=/index.js)

### Steps to reproduce

Use ConfigProvider and try to set modalHeaderTitleFontSize for Modal component. How do you set it? There is no documentation for setting component specific variables in ver. 5.

### What is expected?

I want to be able to customize the theme of components with their component specific variables. For example 'ModalToken' (typescript) for setting Modal specific variables

### What is actually happening?

I can't change the component specific variables

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | CRA |
| System | mac |
| Browser | chrome |

---
See reproduction for an example

**Comment by MadCcc** [comment]
Currently we donot have component tokens for Modal, because these tokens may be unstable.
We will provide more component tokens as feature of V5.

**Comment by HStokbro** [comment]
Ant Design v5 should provide tokens for all variables that were available in v4.

This is the v4 variable list:
https://github.com/ant-design/ant-design/blob/4.x-stable/components/style/themes/default.less#L552

It's really bad that Ant Design decided to launch v5 without support for this

**Comment by fihorvat** [comment]
@MadCcc do you have a list of components that still doesn't have tokens where we could track the progress and schedule the upgrade to v5 (since a lot of us need to be able to update specific token on some components)?
I looked at this file https://github.com/ant-design/ant-design/blob/master/components/theme/interface.ts and it looks like all the components are here.

**Comment by HStokbro** [comment]
Yes. They are all there, but they don't work. You can try out my example: https://codesandbox.io/s/antd-reproduction-template-forked-ler7t4?file=/index.js

**Comment by koukoujohn** [comment]
@HStokbro, I'm not 100% sure because I can't upgrade to v5 right now, but by reading the file for modal at [github](https://github.com/ant-design/ant-design/blob/master/components/modal/style/index.tsx), modalHeaderTitleFontSize is not to be used by you, like when you were using @modal-header-title-font-size with less in version 4.x.

As @MadCcc said, they haven't added Component tokens(yet) but can you try adding this in your global css or less (whatever you are using) as a workaround for now?

```
.ant-modal-title {
    font-size: (your font size)px !important;
}
```

this used to work in version 4 to change the modal's title font size. Since all ant components still use classNames I'm guessing this still works. Unless they changed "ant" prefix to something else.

I hope it works for you

**Comment by MadCcc** [comment]
Trace in https://github.com/ant-design/ant-design/issues/38975
