### ISSUE TITLE
RangePicker 设置 defaultOpe/open，在选择完日期后不会触发 onOpenChange

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#39200]
### Reproduction link

[https://stackblitz.com/edit/react-qucdls?file=demo.tsx](https://stackblitz.com/edit/react-qucdls?file=demo.tsx)

### Steps to reproduce

1.点击加载
2.选择日期后，没有触发 onOpenChange

### What is expected?

触发 onOpenChange

### What is actually happening?

没有触发

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by crazyair** [comment]
另外，v5 删掉了 defaultOpen ？ https://stackblitz.com/edit/react-fauwfy-2uutyv?file=demo.tsx

**Comment by CNFeffery** [comment]
关于这个问题有什么新进展吗

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
