### ISSUE TITLE
Dark Mode / Dark Algorithm font color not being properly set after migrating from Antd4

### ISSUE THREAD

**Issue by simondiep** [ant-design/ant-design#39281]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-dark-theme-color-issues-f8crim?file=/index.js)

### Steps to reproduce

I migrated my Antd4 app to Antd5.

### What is expected?

Dark mode text should be white colored

### What is actually happening?

Dark mode text is still black

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 18.2.0 |
| System | macOS Monterrey |
| Browser | Chrome 107.0.5304.110 |

**Comment by MadCcc** [comment]
Since antd v5 won't provide custom styles for html/body element，theme will not work for these elements.
In 5.1.0, we will provide **App** to override some global styles in this case, ref:  https://github.com/ant-design/ant-design/discussions/38901
And in current version, you should change text color on body by yourself.
