### ISSUE TITLE
Add a validation at TimePicker and DatePicker

### ISSUE THREAD

**Issue by romaloshak** [ant-design/ant-design#39321]
### What problem does this feature solve?

When user enters time at TimePicker from a keyboard he needs to put a colon symbol manually.
Or to give a possibility to a developer to do a validation.

### What does the proposed API look like?

onInputChange={(event: React.ChangeEvent<HTMLInputElement>) => void }

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
