### ISSUE TITLE
Transfer "Invert current page" wrongly inverted all items

### ISSUE THREAD

**Issue by jas0ncn** [ant-design/ant-design#39403]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mcuz99)

### Steps to reproduce

Click "select all" in the title dropdown, and then click "invert current page"

### What is expected?

should just invert current page items

### What is actually happening?

wrongly inverted all items

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by zjfresh** [comment]
> This bug is caused by customized render children which is Table in this case.Transfer can't get the current page in Table.So maybe we should disabled "Invert current page" like "selectCurrent " when customized render children exists, or we can just change the default label "Invert current page" to "Invert all page" in this case.Hope I can help you.

+1, this's right. Transfer may not support "Invert current page" when using customized render children. In fact,  "Invert current page"  here is mean "Inver all".

So the problem of this issue should using Table props `pagination={false}` (and  `scroll={number}` in long table) to bypass and solve it.

Otherwise，we can manully update the text "Inver current page" by `<Transfer locale={{selectInvert: "Invert all"}} />`

**Comment by IndProgo** [comment]
Also without customized render children, "Invert current page" works as "Deselect all"

In docs, choose Select All, then Invert current page
https://ant.design/components/transfer#components-transfer-demo-large-data
