### ISSUE TITLE
TimePicker.RangePicker希望可以支持失焦保存

### ISSUE THREAD

**Issue by undefined9999** [ant-design/ant-design#39651]
### What problem does this feature solve?

目前的交互只能点击确定才能保存选择的时间, 但大多数人的使用习惯是选择完开始和结束就会点击其他空白区域, 会导致选择的值没有保存到输入框内, 所以希望能支持失焦保存.

### What does the proposed API look like?

可以提供配置项, 决定是否开启失焦保存功能

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
