### ISSUE TITLE
【影响使用】DatePicker 在选择一个日期后，按其他按键（包括 ALT / CTRL / WIN / CAPS 等）会再次弹出选择器。

### ISSUE THREAD

**Issue by zmjack** [ant-design/ant-design#40243]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

1、点击 DatePicker 区域；
2、选择一个日期；
3、按任意一个功能键（ALT / CTRL / WIN / CAPS 等）；
4、下拉选择器会再次弹出。

经测试，只有 Shift 不会导致选择器再次弹出。

### What is expected?

按下 功能键 应保持已选定日期的状态，不应弹出选择器。

### What is actually happening?

按下 功能键 会导致下拉选择器再次弹出。

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 17 |
| System | Windows 10 |
| Browser | 新版 Edge |

**Comment by YunxiaChan** [comment]
DatePicker支持一个属性onKeyDown可以使用
<img width="891" alt="image" src="https://github.com/ant-design/ant-design/assets/58042289/e0e40803-2b80-4ef6-b57b-dc679ff5d7e5">

例如
`    <DatePicker onChange={onChange} picker="week" onKeyDown={(event: React.KeyboardEvent<HTMLInputElement>, preventDefault: () => void)=>{
        if (event.ctrlKey || event.metaKey) {
          // 检查是否按下了Control键（Command键在Mac上也会触发）
          console.log(event)
          preventDefault();
        }
    }
    }/>`

**Comment by zmjack** [comment]
@YunxiaChan 这样太麻烦了，我认为这应该是默认处理才合理。

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
