### ISSUE TITLE
The tests in 5.x.x are taking longer to run than 4.x.x

### ISSUE THREAD

**Issue by fastndead** [ant-design/ant-design#40375]
### Reproduction link
no way to reproduce in the isolated environment

### Steps to reproduce

1. Migrate to Antd 5.x.x

### What is expected?

The tests performance being roughly the same

### What is actually happening?

Our tests performance took a significant hit after the update to Antd 5.x.x
Before the update the average time to run all the suites was 
`Time:        683.604 s`
Now when we try to update Antd to 5.x.x, the time becomes:
`Time:        1062.642 s`

The difference in the performance is about 46% only from upgrading the Antd library

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome |

**Comment by StefanoMagrassi** [comment]
@fastndead we had the same issue and I resolved it following [this tip](https://blog.bitsrc.io/why-is-my-jest-suite-so-slow-2a4859bb9ac0#14e6).

It was a long and boring work, but it was worth it

**Comment by zombieJ** [comment]
> @fastndead we had the same issue and I resolved it following [this tip](https://blog.bitsrc.io/why-is-my-jest-suite-so-slow-2a4859bb9ac0#14e6).
> 
> It was a long and boring work, but it was worth it

Thanks for your ref. This help to describe the reason since v5 export more components & style related file which is unnecessary to load all if only use part components.

But is there automated way? Since module import is standard, jest should handle it instead of user manually work.

**Comment by StefanoMagrassi** [comment]
It isn't an `import` related problem: Jest needs to traverse all the re-exported modules of barrel files in order to properly setup the test environment

Also, this it isn't related to Ant only, but it affects other libraries like material-ui or lodash.

By the way, I noticed a general test's performance degradation after v5 migration: it seems that rendering complex components takes now much more time than v4.
I think it could be related to the new css-in-js solution, but I haven't real evidences...

**Comment by zombieJ** [comment]
> Jest needs to traverse all the re-exported modules of barrel files in order to properly setup the test environment

I think this is the reason since each component takes a `cssinjs` file which increase env preparation times even it not use in test.

But I'm afraid we can help less on this since it's out of antd control.

**Comment by georgianafilote-pxo** [comment]
@fastndead @StefanoMagrassi @zombieJ could the issue that you noticed be related to this issue that I created: https://github.com/ant-design/ant-design/issues/47444 ?
do you also use in your tests jest queries and userEvent API? cause I saw that ant uses in their tests only plain querySelectors and fireEvent API

**Comment by fastndead** [comment]
@georgianafilote-pxo As far as I can tell this issue is solely related to the Jest's compilation process and the way it transforms the code before running it. 
I don't think there's much difference between using jest queries, userEvent API and plain querySelectors and fireEvent API since under the hood they all use plain DOM APIs. Also i don't think that the speed of the test execution is the problem, more of a compilation before execution. That's from my perspective, i might be wrong.

**Comment by georgianafilote-pxo** [comment]
@fastndead I did some benchmarking(without mocking cssinjs): for the same scenario (a component with 3 date pickers) I created a test that sets/selects a date in the date pickers and I tested using different API in antd4 vs antd5 and there I noticed the visible slowness on antd5 when getByRole and userEvent are used (which are the top recommended approaches by jest)
So cssinjs has a smaller/bigger impact depending on the API used, cause for the slowest antd5 test, when mocking cssinjs the run time came back to normal (from 8s to 2s)
![image](https://github.com/ant-design/ant-design/assets/153279089/4b476242-5b93-4fbe-94ff-e95ff59f929a)

**Comment by fastndead** [comment]
@georgianafilote-pxo that's pretty incredible what you did. It does look like the tests differ on the execution level. That's weird that there's such variation between using userEvent and fireEvent, i always assumed they run the same plain 'ol DOM APIs. Also that could be helpful if you provide version of jest, rtl and react that you're using

though if the issue is in cssinjs then it's a wrap probably, i don't think that it's plausible to convert a whole library to something else

**Comment by georgianafilote-pxo** [comment]
@fastndead
Some remarks: the differences in performance are mentioned also in each testing library
- userEvent: even if it's a wrapper over fireEvent, behind the scenes it fires multiple events and does additional checks in order to simulate the real user interaction, check https://testing-library.com/docs/user-event/intro/#differences-from-fireevent & https://github.com/testing-library/user-event/blob/5feaa942f46bb37d96c2f2fbeb4b33e8beff75ad/src/click.js#L87
- getByRole: it's mentioned that the calculations performed can be expensive in large DOMs(even though I assume that 3 date pickers are not considered as large DOM trees) and this is a tradeoff that you do if you prefer confidence over performance in tests: check https://testing-library.com/docs/queries/byrole/#performance & https://github.com/testing-library/dom-testing-library/issues/820#issuecomment-726936225
The thing that I don't understand is why cssinjs has such a big impact in some cases and who should tackle it in order to get rid of it in tests since there we don't care about styling: is it rtl/userEvent that should revise their API calculation logic to skip cssinjs or they don't have control/can't identify these and each library should provide a way to allow the cssinjs calculations to be skipped
Also, here are the dependencies used for the previous benchmark
![image](https://github.com/ant-design/ant-design/assets/153279089/e4df5584-4159-4951-b2bd-7f5c7e6a5880)

**Comment by alexandru-apostu-praxedo** [comment]
After further analysis, we discovered the main improvement point to fix the performance issues was upgrading jsdom to at least v21.1.0 which introduces style caching. Unfortunately, the most recent non-alpha `jest-environment-jsdom` has version `29.7.0` which brings in `"jsdom": "20.0.0"`.

For us, the fix was forcing a newer jsdom in our package.json:
```json
    "overrides": {
        "jest-environment-jsdom": {
            "jsdom": "21.1.0"
        }
    },
```
This drastically improves test times on antd5 and makes it feasible for us to upgrade.

**Comment by fastndead** [comment]
@alexandru-apostu-praxedo can confirm on my side that there is an improvement in performance.
without overrides my tests ran 391.7s, with overrides – 330.8 which equates to aprox. 15% improvement, which is plenty significant, though i must admit a expected more drastic improvement.

what do you think would be possible drawbacks in such solution. i would assume there could be some issues with DOM APIs because of this

**Comment by alexandru-apostu-praxedo** [comment]
The perf improvement was quite a lot larger for me, testing phase roughly halved. Maybe you could profile your tests to see a bit better where most time is spent. For us it was the 'window.getComputedStyle' as seen in the following image:
![window-computed-style](https://github.com/ant-design/ant-design/assets/152864566/801ce922-8813-416e-aed1-7fda78c9dd12) which led me to https://github.com/jsdom/jsdom/issues/3234 and then https://github.com/jsdom/jsdom/releases/tag/21.1.0 .

The main drawback is that nobody necessarily tested or intended for `jest-environment-jsdom` to work with `jsdom:21.1.0` :) This could mean that all sort of weirdness can happen. Given our tests work well and we have a decently large number of them we've felt comfortable enough to take this risk, since the alternative is to stick to antd4 for another while until `jest-environment-jsdom:3` exits alpha.

**Comment by fastndead** [comment]
@alexandru-apostu-praxedo hey, i actually wanted to add on to my previous comment. This 15% improvement wasn't real, i added `overrides` property to my package.json, but since i use yarn it didn't make any difference, so 15% fluctuation was the result of the second run. After i changed `overrides` to `resolutions` (yarn way) it all started to make sense. The performance doubled, but some tests straight up failed due to the usage of removed API (as far as i can understand). So your approach is definitely worth trying, but in my case i will have to work on many tests to get it working properly
