### ISSUE TITLE
Date picker unexpected behaviour

### ISSUE THREAD

**Issue by rustam-as** [ant-design/ant-design#40860]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hejwvz)

### Steps to reproduce

I use Antd and React. In my modal I set fields value with antd useForm hook. Click on datepicker and you will see weird dates with blue backgrounds. 

### What is expected?

As always datepicker should render dates

### What is actually happening?

datepicker renders unknown dates and while hoverin it shows different dates such as 02.09.2120

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | react@18.2.0 |
| System | Windows 11 pro 64bit (10.0 Build 22000) |
| Browser | Google Chrome Version 110.0.5481.77 (Official Build) (64-bit) |

---
this bug related to antd 5 not 4

**Comment by Yuiai01** [comment]
Hello, I find your problem is caused by the use of `moment`. In antd v5, `Dayjs` is used instead of `moment`. You can refer to this link to [use Dayjs,](https://codesandbox.io/s/antd-reproduction-template-forked-erw7i9?file=/index.js) or refer to this to continue [using moment](https://ant.design/docs/react/use-custom-date-library#datepicker).

**Comment by rustam-as** [comment]
@Yuiai01 great, thank you

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/50622#issuecomment-2317050774
