### ISSUE TITLE
Retrieve id of preset themes

### ISSUE THREAD

**Issue by riwu** [ant-design/ant-design#40886]
### What problem does this feature solve?

`theme.defaultAlgorithm` has `id:0` while `theme.darkAlgorithm` has `id:2`.

We need constants for these ids so that we can compare them for customization in non-antd components.
Eg. `className={ag-theme-alpine${currTheme.id === theme.DEFAULT_ALGORITHM_ID ? "" : "-dark"}}`.

### What does the proposed API look like?

`theme.darkAlgorithm.id` or `theme.DARK_ALGORITHM_ID` (should return `2`).

**Comment by zombieJ** [comment]
`algorithm` do not have id, is just a function. Theme object `id` do not mean anything since it's auto increase.

You can use `(theme as any).derivatives` to force get the Theme real using algorithm function to compare whether is using `darkAlgorithm` or `defaultAlgorithm`.

Another way is wrap the customize algorithm to inject a token like `customize` mark:
```tsx
const myAlgorithm = (token: SeedToken) {
  // ...
  return {
    // ...
   customize: true,
  } as MapToken;
}
```
