### ISSUE TITLE
How to format dropdown value in timepicker component?

### ISSUE THREAD

**Issue by storageChu** [ant-design/ant-design#40964]
### What problem does this feature solve?

Which I can customize format dropdown values, eg: format hour 09 to 09H

### What does the proposed API look like?

formatDropdownValue={hour: 'HH小时', minute: 'mm分', second: 'ss秒'}

**Comment by gitstart** [comment]
@zombieJ I would like to pick this up.

**Comment by gitstart** [comment]
@zombieJ I have so far been unable to implement this issue because the time picker dropdown values are generated by an external library called `rc-picker`, and I have so far been unable to find an effective way to format the dropdown values generated by that library. However, I am open to any suggestions as to how I can go about this differently, thanks.

**Comment by linxianxi** [comment]
you can use `cellRender`

**Comment by zombieJ** [comment]
> you can use `cellRender`

+1 https://codesandbox.io/s/ji-ben-antd-5-10-0-forked-p6gf2f?file=/demo.tsx
