### ISSUE TITLE
Ant Design DatePicker and TimePicker onChange not working 

### ISSUE THREAD

**Issue by jahidulsaeid** [ant-design/ant-design#40972]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-x6p489)

### Steps to reproduce

Follow the codesandbox project [https://codesandbox.io/s/antd-reproduction-template-forked-x6p489](https://codesandbox.io/s/antd-reproduction-template-forked-x6p489)
First step Click the Set Values Then Try to change date and time it's not working

### What is expected?

When i change it should change the value

**Note: When i using Today(DatePicker) or Now(TimePicker) Button then it's working**

### What is actually happening?

When i try to setFields and try to change this value its not working DatePicker show all date are selected and TimePicker not change the value

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 18.2.0 |
| System | Ubuntu 22.04.2 LTS |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
@jahidulsaeid Hello, I find your problem is caused by the use of moment. In antd v5, Dayjs is used instead of moment. You can refer to this link to [use Dayjs,](https://codesandbox.io/s/antd-reproduction-template-forked-erw7i9?file=/index.js) or refer to this to continue [using moment](https://ant.design/docs/react/use-custom-date-library#datepicker).

**Comment by Lupe-Fiasco** [comment]
I encounter the same problem.. have you solved that? (I also use momentjs)
