### ISSUE TITLE
InputNumber and Password component behaves different when importing from lib and es folders 

### ISSUE THREAD

**Issue by manikandanm1757** [ant-design/ant-design#41039]
### Reproduction link

[https://stackblitz.com/edit/react-zxppg6?file=demo.tsx](https://stackblitz.com/edit/react-zxppg6?file=demo.tsx)

### Steps to reproduce

1. Run the stackblitz sample.
2. See the difference between both number components imported from lib and es folders

### What is expected?

Component should behave same irrespective of from where its imported

### What is actually happening?

Component rendering behaviors are different for both es/input-number and lib/input-number

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 17 |
| System | Stackblitz |
| Browser | Chrome latest |

**Comment by Wxh16144** [comment]
It is not recommended to mix `lib` and `es`. This can cause a lot of problems. Because our component has a lot of context. When brought in from two different places, the two contexts will be completely different.

In the demo you provided, you can try importing the `<Form />` component from `lib` and `es` respectively to see the effect.

Example of the error:
![image](https://user-images.githubusercontent.com/32004925/222852435-7c2eb4e7-beaa-459c-8be7-5f20b4c23230.png)
