### ISSUE TITLE
An input element is not bound when using `genComponentStyleHook`

### ISSUE THREAD

**Issue by ArtyomVancyan** [ant-design/ant-design#41403]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-j6v3vp?file=/index.js)

### Steps to reproduce

If you are already opened the sandbox link, just click the **Check** button.

### What is expected?

I expected to see the input element change its status when the form was invalid.

### What is actually happening?

It realizes the invalidity of the form by showing the `message` value provided in `rules`, but it does not make the input's borders red.

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | Ubuntu OS |
| Browser | Firefox |

---
I also tried to achieve this by providing the input reference to the `useStyleRegister` hook, returned by `genComponentStyleHook`, thinking that it would bind the input and handle the needed changes, but it did not work.

**Comment by MadCcc** [comment]
Well, that's really not recommended to apply style to components in this way, and your usage of genComponentHook is totally wrong. If you are interested in how antd apply styles to components, just check the [source code](https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx).

Going to close this issue because of unexpected usage.
