### ISSUE TITLE
No validation check for format prop in DatePicker component when passing random string

### ISSUE THREAD

**Issue by NegiBaba** [ant-design/ant-design#41546]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/green-leaf-rv12uq)

### Steps to reproduce

1. Import the DatePicker component from 'antd'.
2. Pass any random string to this DatePicker component as the 'format' prop, e.g. dxfdx
3. Select any date in the DatePicker component and you will see a very long invalid date string.

### What is expected?

There should a validation check when a format is passed to the component, if the format is not valid then there should be a fallback value such as "MM/DD/YYYY".

### What is actually happening?

The internal library dayjs is formatting the date based on the "format" passed and returns invalid date, such as if you pass dxfdx you will get something like this: 21680001334166f21680001334166

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.2.0 |
| System | MacOS Ventura |
| Browser | Google Chrome |

---
This bug is caused by dayjs/momentjs as they just check the format string for characters like d, h, D, M, Y etc, but we can surely have some validation check at the component's end verifying the format or the formatted date.

**Comment by MadCcc** [comment]
> but we can surely have some validation check at the component's end verifying the format or the formatted date.

`Format` is an API provided by both Moment and Dayjs. I don't believe it's appropriate for the component library to encapsulate it. If a fallback format is added, it will be difficult for users to detect any issues with their own format.

Therefore, I believe this issue is better raised with Moment or Dayjs, and we won't be expanding on it ourselves. Of course, you could also create your own validation for `format`.
