### ISSUE TITLE
Draggable tree mis-aligned when text overflows

### ISSUE THREAD

**Issue by kwengontra** [ant-design/ant-design#41915]
### Reproduction link

[https://codepen.io/kevinwengontra/pen/poxNadj](https://codepen.io/kevinwengontra/pen/poxNadj)

### Steps to reproduce

Drag preview window to be narrower than 400px

### What is expected?

"parent sibling" and "parent long-text ..." to be left-aligned or wrap

### What is actually happening?

"parent long-text ..." ends up shifting to the left
<img width="348" alt="image" src="https://user-images.githubusercontent.com/124843626/233481738-8e67d7a3-0519-4aa3-af71-f33600795942.png">

### Additional info
This only happens when tree is `draggable`
The underlying rc-tree library seems to handle draggable better

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | macOS 13.3.1 |
| Browser | Chrome 112.0.5615.121 |

**Comment by Yuiai01** [comment]
I found that it was probably due to this, I removed the style and it was aligned.
![image](https://user-images.githubusercontent.com/112228030/233512166-8340269b-ae2d-4f62-b0f0-305df5867af2.png)
![image](https://user-images.githubusercontent.com/112228030/233513283-71ed94ed-aba1-41af-857a-cf2a5c5146e0.png)
