### ISSUE TITLE
Strange behavior in a DatePicker inside a form with a default value

### ISSUE THREAD

**Issue by PauCodina** [ant-design/ant-design#41913]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-vcb65o?file=/index.js)

### Steps to reproduce

Open the date picker

### What is expected?

The calendar should appear so you can select a date.
The default date should be checked (selected).
Using the navigation buttons it should be possible to change the month and year.

### What is actually happening?

The calendar appears but not in the correct month or year.
All days are marked as selected.
When you hover over the days, the date is changed automatically.
The navigation controls do not work correctly.

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | react |
| System | Mac OS ventura & windows 11 |
| Browser | chrome & firefox |

**Comment by Yuiai01** [comment]
@PauCodina Hello, I find your problem is caused by the use of moment. In antd v5, Dayjs is used instead of moment. You can refer to this link to [use Dayjs,](https://codesandbox.io/s/antd-reproduction-template-forked-erw7i9?file=/index.js) or refer to this to continue [using moment](https://ant.design/docs/react/use-custom-date-library#datepicker).

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/50622#issuecomment-2317050774
