### ISSUE TITLE
[Modal]弹框打开后，fixed或者absolute元素会抖动

### ISSUE THREAD

**Issue by jx62257070** [ant-design/ant-design#41956]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vibrant-lalande-ckk85f?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

点击【Open Modal】唤起弹框

### What is expected?

header标签中居中的元素【fixed定位】与下面的【test】元素一样，唤起弹框后位置不变

### What is actually happening?

header标签中居中的元素，因为隐藏滚动条导致宽度变化，使里面元素的居中位置变化，产生抖动视觉效果

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome 114.0.5720.4 |

---
I. https://github.com/ant-design/ant-design/issues/19729 该issues有提出类似问题，但是在它close前没有看到解决方案，而且issues里讨论的解决方案在5.x版本已经不用了，5.x版本的antd 只是对html和body标签calc了宽度。
II. 解决以上场景，可以额外增加一个class样式例如：
```
.ant-scrolling-effect{
    width: `calc(100% - ${scrollBarSize}px)`,
}
```
用户可以自行配置class:ant-scrolling-effect，例如：```<header class="ant-scrolling-effect" />```

**Comment by zombieJ** [comment]
嗯，是个已知问题。但是不好解，因为滚动条变化是会影响宽度的。css 里配置的宽度不会受 padding 影响。

**Comment by jx62257070** [comment]
> 嗯，是个已知问题。但是不好解，因为滚动条变化是会影响宽度的。css 里配置的宽度不会受 padding 影响。

我看到弹框唤起时会插入这个style标签：
![image](https://user-images.githubusercontent.com/42292902/234509719-ced1b4f4-8c6e-4d3d-8088-a5b3ffe3c278.png)

如果在这个style标签里额外加入类似我上述的class样式：
![image](https://user-images.githubusercontent.com/42292902/234513020-41945cab-b58b-4861-9c16-dda7952a0f34.png)

让使用者通过在header标签自己加入该class来控制宽度，是否可行呢？
![image](https://user-images.githubusercontent.com/42292902/234513256-bad10854-3e1f-403c-b90a-4802ae96bce6.png)

**Comment by zombieJ** [comment]
这种就是需要开发同学自行添加对应逻辑，组件层面就没办法做了。

**Comment by jx62257070** [comment]
> 这种就是需要开发同学自行添加对应逻辑，组件层面就没办法做了。

毕竟组件不好判断哪些元素需要一起变宽度，只能让使用者自己视情况配置了。

比起使用者监听每个弹框显隐，然后再自己插入和移除style标签，感觉在【插入style标签】代码处优化下更好。

不过这段【插入style标签】的代码似乎在rc-util这个库，不好直接改..

看antd之前有给rc-util库提issues，上述解决方案是否可以也提个issues优化下呢？

**Comment by TimoA200** [comment]
# Let me translate this thread for you (you're welcome):
### [jx62257070](https://github.com/jx62257070)
### Steps to reprodue
Click [Open Modal] to invoke the pop-up box

### What is expected?
The centered element [fixed positioning] in the header tag is the same as the [test] element below, and the position remains unchanged after the pop-up box is evoked

### What is actually happening?
The centered element in the header tag, because the hidden scroll bar causes the width to change, the centered position of the element inside changes, resulting in a jittering visual effect

[shows his environment]

I. #19729 This issue raised a similar problem, but I didn't see the solution before it was closed, and the solution discussed in the issue is no longer used in version 5.x. Antd in version 5.x only supports html and body tags Calculate the width.
II. To solve the above scenarios, you can add an additional class style such as:
```
.ant-scrolling-effect{
    width: `calc(100% - ${scrollBarSize}px)`,
}
```

Users can configure class:ant-scrolling-effect by themselves, for example:  `header class="ant-scrolling-effect" />`


### [zombieJ](https://github.com/zombieJ)
Well, it's a known issue. But it is not easy to solve, because the change of the scroll bar will affect the width. The width configured in css will not be affected by padding.


### [jx62257070](https://github.com/jx62257070)
I see this style tag is inserted when the popup pops up:
![image](https://user-images.githubusercontent.com/22802100/234687240-7fcfda72-0c29-4cca-b8ca-3fa93ed772f8.png)

If you add an additional class style similar to the one I mentioned above to this style tag:
![image](https://user-images.githubusercontent.com/22802100/234687290-21ed444a-003c-4949-91c6-51b346ae764f.png)

Is it feasible for users to control the width by adding this class in the header tag?
![image](https://user-images.githubusercontent.com/22802100/234687338-f0cb1368-f6fa-45c6-a32c-5e5dd73d8045.png)


### [zombieJ](https://github.com/zombieJ)
This kind of thing requires developers to add corresponding logic by themselves, and there is no way to do it at the component level.


### [jx62257070](https://github.com/jx62257070)
After all, it is not easy for components to judge which elements need to be changed in width together, so users can only configure them according to the situation.

Compared with the user monitoring each pop-up box to show and hide, and then inserting and removing the style tag by himself, it feels better to optimize the [insert style tag] code.

But this [insert style tag] code seems to be in the rc-util library, so it’s not easy to change it directly..

Seeing that antd has raised issues for the rc-util library before, can the above solution also raise issues for optimization?

**Comment by TimoA200** [comment]
In my case, I have overridden all html, body related `width` values, with the css `!important` rule, in my global.css.
```
html,
body {
  width: 100% !important;
}
```

This is for sure not applicable in all cases, but for me it was the fastest way to solve this.

**Comment by zombieJ** [comment]
You can use `:is` selector to raise priority instead of `!important`:

https://codesandbox.io/s/divine-resonance-g4c009?file=/src/styles.css

**Comment by zombieJ** [comment]
Close since current prevent scroll is only  for css control. We can do nothing more on this.

**Comment by huangsheng7271** [comment]
大佬们，这个问题应该怎么解决呀
