### ISSUE TITLE
Please allow us to not show the checkbox for some menu options in Cascader (in multiple mode)

### ISSUE THREAD

**Issue by georgeciobanu** [ant-design/ant-design#41997]
### What problem does this feature solve?

When in multiple node, the Cascader shows a checkbox for every single option. Can you please allow us to not show the checkbox for some options, similar to the ReactSuite Multicascader uncheckable parameter: https://rsuitejs.com/components/multi-cascader/#uncheckable

Sometimes we need to allow the user to make multiple choices for say depth level 2 but not for level 1.
For example, I want to show the users the option to pick A *or* B on the first level, but allow the user to pick as many of A's children as needed.

### What does the proposed API look like?

<Cascader uncheckable={[option1 option2 option4]}>

**Comment by BoyYangzai** [comment]
I used https://github.com/react-component/cascader/pull/408 and  https://github.com/ant-design/ant-design/pull/42024 to complete this feature😄
![image](https://user-images.githubusercontent.com/94534613/234700417-7020994d-f6b5-4077-ab4b-14c7a0709e70.png)

![image](https://user-images.githubusercontent.com/94534613/234700290-20829d33-df07-4783-8e3e-cec14efdbc99.png)

There should be nothing wrong with the feature. You can check the feature by clone both projects and use the npm link

But strangely enough I managed to complete the unit test on https://github.com/react-component/cascader/pull/408 
But the https://github.com/ant-design/ant-design/pull/42024 test failed. He told me invalid hook call, it's may be react verision confilct because of npm link

I have not mentioned pr to rc- component before, I don't know if it's because of local debugging, but please help me look at it. @zombieJ @li-jia-nan @MadCcc

**Comment by georgeciobanu** [comment]
So grateful, thank you! I'll try it asap - not sure how to patch the local antd version but will try to figure it out. You are an angel!

**Comment by Zzwhite3** [comment]
@BoyYangzai 问一下 我现在antd 4x的版本也遇到这个需求， 需要二级级联的 checkbox动态禁用， antd4x有没有类似disabledcheckout的属性？
