### ISSUE TITLE
日期选择扩展  至今  功能  ,时间范围可控制高亮面板

### ISSUE THREAD

**Issue by ty01** [ant-design/ant-design#42338]
### What problem does this feature solve?

1.结束时间的选择，在岗在职状态下，当前组件不能够很好的表达
2.时间范围希望可以控制当前高亮是开始还是结束

### What does the proposed API look like?

1.参考antd-mobile 的  tillNow属性
2.activeTab   start | end    onActiveTabChange

**Comment by MadCcc** [comment]
可以再给些细节吗？可以举个具体例子

**Comment by ty01** [comment]
比如：要录入教师的任职时间    如果教师已经离职  则结束时间是具体的（当前的时间范围选择器没问题）  如果老师还在职   结束时间就不好具体选择 （不选也不好理解，希望扩展  一个按钮  ‘至今’   ，表示他当前还在职） 如：任职时间：2013-06 ~ 至今

**Comment by 18319700115** [comment]
有解决方案了吗

**Comment by Wxh16144** [comment]
算一个 feature， rc-picker @zombieJ  在重构。看看大佬怎么说~

**Comment by zombieJ** [comment]
嗯，在计划里了

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
