### ISSUE TITLE
Selection box scrolls continuously with repeated content

### ISSUE THREAD

**Issue by yoke0104x** [ant-design/ant-design#42457]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-5-0-forked-guh6mk)

### Steps to reproduce

https://codesandbox.io/s/ji-ben-shi-yong-antd-5-5-0-forked-guh6mk

连续多次滚动，会显示所有选项重复

![](https://files.catbox.moe/3wied4.png)

### What is expected?

选项不在重复

### What is actually happening?

选项重复

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.0.0 |
| System | v5 |
| Browser |  112.0.5615.137（正式版本） (arm64) |

---
https://codesandbox.io/s/ji-ben-shi-yong-antd-5-5-0-forked-guh6mk

连续多次滚动，会显示所有选项重复

![](https://files.catbox.moe/3wied4.png)

**Comment by yoke0104x** [comment]
因为使用了虚拟滚动导致数据多次滚动后会重复

**Comment by CwRv07** [comment]
你可以看到报错，这是由于你有options.value，也就是select组件内的选项数据的key重复导致

**Comment by yoke0104x** [comment]
> 
？？？？有个demo你试试一直鼠标滚轮上下滚动

**Comment by CwRv07** [comment]
就是demo中的报错：
Warning: Encountered two children with the same key, `千瓦时`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

你数据中id为13和id为20的数据的name属性都是'千瓦时'

**Comment by BoyYangzai** [comment]
@yoke0104x https://codesandbox.io/s/ji-ben-shi-yong-antd-5-5-0-forked-wd6v7n?file=/demo.tsx
加个key就好了哈
@li-jia-nan 可以close了
