### ISSUE TITLE
 Set validateFirst as Default for Form.Item Rules

### ISSUE THREAD

**Issue by sanshao** [ant-design/ant-design#42567]
### What problem does this feature solve?

Currently, the default value for validateFirst in Ant Design's Form.Item component is false. However, in the majority of real-world development scenarios, it is more common and useful to validate only the first rule defined for a form field.

I propose setting validateFirst as the default behavior for Form.Item rules. This change would simplify the validation process and align with the typical use case. It would greatly benefit developers by reducing the need to explicitly set validateFirst for each form field, especially when only a single rule is defined.

Please consider implementing this change as it would improve the developer experience and align the default behavior with the common usage pattern.

Thank you for your attention to this matter.

### What does the proposed API look like?

Set validateFirst as Default for Form.Item Rules

**Comment by zombieJ** [comment]
Thanks for feedback. But `validateFirst` by default maybe not the best way. In some validate condition, it's better to show all the validate message for user to easy to modify input and other is one rule failed is enough. We choose `validateFirst: false` by default is to choose the bottom line strategy instead of part good strategy.

 You can HOC Form.Item to auto inject `rule` with `validateFirst` for the requirement : )

**Comment by zombieJ** [comment]
PS: Modify default config is a breaking change, even it accept we still need to apply on the next major version instead.
