### ISSUE TITLE
DatePicker.RangePicker when input width size change, picker popup position-left is not correct

### ISSUE THREAD

**Issue by Landon-CN** [ant-design/ant-design#42775]
### Reproduction link

[https://github.com/scliuyang/antd-rangepicker-bug](https://github.com/scliuyang/antd-rangepicker-bug)

## Reproduction step
RangePicker first set width 100%, and then set to 300px.
RangePicker will align right click it and the dropdown panel position-left is not correct. but if you click again it will correct

### first click
![截屏2023-06-01 17 43 16](https://github.com/ant-design/ant-design/assets/12167648/3196ce1d-e9bb-4d3a-8165-371937cb6a57)

### second click
![截屏2023-06-01 17 43 29](https://github.com/ant-design/ant-design/assets/12167648/37779e57-f75c-43bc-9d89-6285faa962d1)

demo code
```tsx
const BugDemo = () => {
  const [width, setwidth] = useState('full');

  useEffect(() => {
    setwidth('small')
  }, [])
  return (
    <div>
      <Button
        onClick={() => {
            window.location.reload()
        }}
      >
        reload
      </Button>
      <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
        <div style={{ width: width === 'full' ? '100%' : '300px', marginLeft: width === 'full' ? 0 : 500 }}>
          <DatePicker.RangePicker style={{ width: '100%' }}></DatePicker.RangePicker>
        </div>
      </div>
    </div>
  );
};
```

### What is expected?

i expect RangePicker Dropdown panel will position correct points

### What is actually happening?

poistion left is not right

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 17.0.2 |
| System | 12.6.5 |
| Browser | chrome 113.0.5672.126 |

---
i try used codesandbox to reproduce bug,but i can't. so I provide github repo url. 
demo guide
1. yarn install
2. yarn run start
3. open chrome  brower and link http://localhost:3000/

**Comment by officialkanav** [comment]
Can I solve this?

**Comment by BoyYangzai** [comment]
> Can I solve this?
> 

of course~

**Comment by officialkanav** [comment]
Able to reproduce this. The problem is coming for both width and marginLeft. For some reason the value for popup is not changing with state changes.
@BoyYangzai I am new to open source and this repo, can you please provide me with a document or any resource that can help me with debugging this and testing the changes?

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
