### ISSUE TITLE
希望 RangePicker 组件提供 onSelect 事件

### ISSUE THREAD

**Issue by 97702573** [ant-design/ant-design#43079]
### What problem does this feature solve?

实时获取用户select的时间

### What does the proposed API look like?

实时获取用户select的时间，而不是点击确定按钮才能获取到用户选择的时间

**Comment by 97702573** [comment]
还有一个疑问：为什么TimePicker的当前时间不是输入框里面的value，而是我们当前的北京时间？这和DatePicker组件不一致啊

**Comment by Yuiai01** [comment]
目前好像没有 onSelect 事件，按照你的描述，或许你可以使用 [`onCalendarChange` ](https://ant.design/components/date-picker-cn#rangepicker) 方法。关于第二个疑问，我看了一下 TimePicker 和 DatePicker 获得的此刻 / 今天都是当前的北京时间，不一致是指在什么地方呢？

**Comment by 97702573** [comment]
我说的不是此刻时间，disabledTime事件有一个参数，DatePicker组件和TimePicker组件获取到的参数并不一致。TimePicker组件获取到的是北京时间，而DatePicker获取到的是select的时间，默认是input里面的value。

**Comment by 97702573** [comment]
onCalendarChange 事件只能在点击确定之后获取到实时选择的时间，而我想要实时的获取选择的时间。

**Comment by Yuiai01** [comment]
> 我说的不是此刻时间，disabledTime事件有一个参数，DatePicker组件和TimePicker组件获取到的参数并不一致。TimePicker组件获取到的是北京时间，而DatePicker获取到的是select的时间，默认是input里面的value。

不是很理解，能提供一个 codesandbox 吗？

**Comment by Yuiai01** [comment]
> onCalendarChange 事件只能在点击确定之后获取到实时选择的时间，而我想要实时的获取选择的时间。

你所指的实时选择是鼠标 hover 过的时间吗？

**Comment by 97702573** [comment]
DatePicker组件和TimePicker组件都有disabledTime这个事件，然后disabledTime事件获取到的参数不一样，DatePicker获取的是用户选择的时间，TimePicker获取到的是北京时间。您可以试一下。

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
