### ISSUE TITLE
"Warning: `value` of Option should not use number type when `mode` is `tags` or `combobox`" - not showing up in combobox mode

### ISSUE THREAD

**Issue by gmoniava** [ant-design/ant-design#43255]
### Reproduction link

[Demo](https://codesandbox.io/s/tags-antd-5-6-3-forked-jfj6sx?file=/demo.tsx)

### Steps to reproduce

1. Run the code
2. See warning: "`value` of Option should not use number type when `mode` is `tags` or `combobox`"

### What is expected?

You can see the warning when I use "tags" mode.

But **according to the warning** I can't use `number ` as type for `value ` of option in "combobox" mode also.
But if I run above example in "combobox" mode like this with same options:

```
 <Select
    //  mode="tags" -- commented
    style={{ width: "100%" }}
    placeholder="Tags Mode"
    onChange={handleChange}
    options={[{ value: 1, label: "test" }]}
  />
```

The **warning is not there anymore** despite value of option having `number ` type.
I see warning only in "tags" mode.

### What is actually happening?

Not getting warning in "combobox" mode.

| Environment | Info |
| --- | --- |
| antd | 5.6 |
| React | 18 |
| System | Windows 10 |
| Browser | Chrome 114 |

---
So maybe modify the warning and remove "combobox" part, and say: 
"`value` of Option should not use number type when `mode` is `tags` "?

**Comment by zombieJ** [comment]
`tag` mode means user type can be an option, input passed by `<input />` element always return string as event value. So when your option is `number: 1` and user delete it and type back of `string: 1`, it can be align back to `number: 1`.

`combobox` is not provided directly by Select component. We extract to `AutoComplete` component instead because `combobox` is `<input />` with additional options popup which also means user can not type `number` value with native element.

In most case, user provided `string` input to be part of value but `options` provided `number` will have potential type mismatch issue. My suggestion is not mix this up as warning told.

**Comment by gmoniava** [comment]
@zombieJ So `Select ` has no combobox mode? It means I can use value as `number ` in **all cases except** "tags" mode with `Select`?

**Comment by zombieJ** [comment]
Yes. The warning is from `rc-select` which has `tags` & `combobox` mode. And antd wrap `combobox` mode to AutoComplete~

**Comment by gmoniava** [comment]
Ok I see thanks. So if I use `select ` without `mode ` specified I can use `number ` for option's value.
