### ISSUE TITLE
TreeSelect无法横向滚动的问题，三年了都没修这个缺陷吗？

### ISSUE THREAD

**Issue by LXY02** [ant-design/ant-design#43352]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yi-bu-jia-zai-antd-4-24-12-forked-8rz3ds?file=/demo.tsx)

### Steps to reproduce

上面的链接多点点就可以看到无法横向滚动，这还是官网例子。

### What is expected?

层级多了的时候，可以横向滚动。

### What is actually happening?

异步加载子节点，层级多了，无法横向滚动。

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome 114.0.5735.133 |

---
这个问题我看在github很多人都问了，但是一直都没人修复啊。
https://github.com/ant-design/ant-design/issues/25268 （2020年就有人提了啊，到现在都没有修复啊）

**Comment by zombieJ** [comment]
有兴趣来个 PR 吗~

**Comment by afc163** [comment]
Trace #33849 , PR is welcome~

**Comment by LXY02** [comment]
> 

解决了，感谢兄弟，还真没注意到虚拟滚动是默认开启的。关了虚拟滚动就行。鱼和熊掌不可兼得。。

**Comment by Tatekii** [comment]
> > 
> 
> 解决了，感谢兄弟，还真没注意到虚拟滚动是默认开启的。关了虚拟滚动就行。鱼和熊掌不可兼得。。

我也遇到了，找半天宽度😂

**Comment by Flcwl** [comment]
我这里场景类似树，里面每列节点想用虚拟滚动，然后外部容器也能横向滚动。gg

**Comment by berkaykirtillii** [comment]
> 我这里场景类似树，里面每列节点想用虚拟滚动，然后外部容器也能横向滚动。gg 得魔改了
I use a tree component with Virtual scroll in the sidebar. I want to scroll horizontally when a long data arrives. That's why I assigned width: max-content style to the Tree component, but it didn't work. Afterwards, I assigned the width:max-content style to a container element, but I still could not succeed. Do you have any suggestions ?
