### ISSUE TITLE
Can someone add antd tag to Stackoverflow?

### ISSUE THREAD

**Issue by vladimirpekez** [ant-design/ant-design#4353]
I can't pick antd tag on Stackoverflow. Can someone with 1500 reputation create antd tag on Stackoverflow?

**Comment by SergioCrisostomo** [comment]
I created one: [`ant-design`](http://stackoverflow.com/questions/tagged/ant-design)

And when someone has some points in this new created tag we can add the synonym `antd`.

**Comment by benjycui** [comment]
@SergioCrisostomo I am not sure if you can rename `ant-design` to `antd`?

**Comment by vladimirpekez** [comment]
Thanks Sergio - I will use ant-design for all my questions.

**Comment by SergioCrisostomo** [comment]
I just added the tag to more questions. We can add a synonym so both exist when someone has `5+` in that tag.

@afc163, @benjycui: Which do you prefer to be the main tag `ant-design` or `antd`?  
(personaly I think `ant-design` is better because you can read the name of the project in the tag name).

**Comment by afc163** [comment]
I think `antd` is better cause it is easy to related with the npm pakage name.

**Comment by SergioCrisostomo** [comment]
@afc163 now both tags exist in Stackoverflow! [One of the mods ♦ helped](http://meta.stackoverflow.com/q/340328/2256325) and now `antd` the main one, and `ant-design`synonym to it.

**Comment by vladimirpekez** [comment]
Thanks Sergio!

Vladimir
