### ISSUE TITLE
When clicked outside the table filters drop-down, it also apply the changes

### ISSUE THREAD

**Issue by zeelmodi-simform** [ant-design/ant-design#43908]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gwdjtd)

### Steps to reproduce

1. Click on the filters icon on Name column
2. Select "Joe"
3. Click on any area outside the dropdown
4. Observe the table data

### What is expected?

The table filters should be applied when clicked on Okay/Reset button but they are applying with outside clicks as well. I want a way to disable this

### What is actually happening?

The table filters are applying with outside clicks as well.

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 18.2.0 |
| System | Ubuntu 20.04.6 LTS |
| Browser | Google Chrome 115.0.5790.102 |

**Comment by zeelmodi-simform** [comment]
@afc163 Can you please help here??

**Comment by xsjcTony** [comment]
+1. It could be better to provide a boolean prop on the column to configure this.

@MadCcc Sorry for the ping, as I just want to check whether you can receive notification even without being assigned (as I can see you are one of the participants of this issue).
I recently got scolded because of pinging OSS maintainer straight away🤣. If you can in this scenario, I'll not use  `@` anymore.

I may try to attempt to give PR for this, but depends on my time availability.

Does the official team have any plan for this enhancement?
