### ISSUE TITLE
Date range picker with status broken animation when selecting the end date

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44177]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x5gxvh?file=/demo.tsx)

### Steps to reproduce

select the start date and when choose the end date the dropdown animation is broken

### What is expected?

smooth animation transition

### What is actually happening?

animation flickers

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by AsuraKev** [comment]
this is the sandbox containing the range picker https://codesandbox.io/s/x5gxvh

Try populate the start and end date you ll see the datepicker dropdown shaking like a seizure

**Comment by MadCcc** [comment]
Could you provide a video on your screen? Didn't find anything wrong in your reproduction.

**Comment by AsuraKev** [comment]
Sure :)

https://github.com/ant-design/ant-design/assets/52765572/d63d7d66-a61d-4c07-8951-5dd6ee01661f

**Comment by AsuraKev** [comment]
Better quality recording

https://github.com/ant-design/ant-design/assets/52765572/ad1e7911-6d05-405c-99c8-0fbb3fca9225

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
