### ISSUE TITLE
DatePicker组件，选择日期完成，保持焦点时，在mac系统下，按下option键会弹出选择框，

### ISSUE THREAD

**Issue by wersling** [ant-design/ant-design#44203]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

1. 使用DatePicker选择一个日期
2. 保持组件焦点
3. 按下mac键盘option键

### What is expected?

应该保持和下拉菜单一致的逻辑

### What is actually happening?

按下option键弹出了

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 1 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Duplicate of #40243

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
