### ISSUE TITLE
RangePicker component dose not  support double-clicking date to confirm the date

### ISSUE THREAD

**Issue by JianDaRui** [ant-design/ant-design#44295]
### What problem does this feature solve?

This operation is too tedious that RangePicker must click the ok button to trigger ok event to choose start time or end time,  if date element suppose double-click, its easy to operate。

### What does the proposed API look like?

```jsx
<RangePicker 
onDateDoubleClick={(currentDate, today, info) => {
console.log(currentDate, today, info)
}}
/>
```

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
