### ISSUE TITLE
RangePicker with new defaultValue instead of deprecated defaultPickerValue has different behaviour for showing the calendar range

### ISSUE THREAD

**Issue by DercilioFontes** [ant-design/ant-design#44905]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-68y98l)

### Steps to reproduce

See the reproduction link. Click to open the calendar.

I need the user to select the dates and the calendar to show the month before and the current one. So, I am setting `[dayjs().subtract(1, "M"), dayjs()]` and the value to `[null, null]`.

Deprecated `defaultPickerValue` shows the calendar for the month before and the current, while the `defaultValue` shows the current and next month. It doesn't obey the values passed. I see that if I remove the `value={[null, null]}` it sets the default values, but I need to show the calendar to select from a month before the current, at least.

How can I get the same behaviour using `defaultValue`?

### What is expected?

To show the calendar with months from the dates passed.

### What is actually happening?

It shows the current month and the next.

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2.0 |
| System | macOS Ventura 13.5.2 |
| Browser | Version 118.0.5993.11 (Official Build) dev (arm64) |

![Screenshot 2023-09-15 at 6 04 00 PM](https://github.com/ant-design/ant-design/assets/20172847/c2ec0c9b-f412-4fbb-a4e0-e6dcafb0adac)
![Screenshot 2023-09-15 at 6 04 07 PM](https://github.com/ant-design/ant-design/assets/20172847/135f1917-8dd5-4fda-8bf2-08ddb1389d9b)

**Comment by Yuiai01** [comment]
In the relevant source code, `value` and `defaultValue` are first merged, and then this value is merged with `defaultPickerValue` to generate the panel date. Since the value of `value` is `[null, null]`, it will override the value of `defaultValue` but will not override the value of `defaultPickerValue`. Perhaps here, it should be considered to use the `value` of `defaultValue` if value is [null, null]. 🤔

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行处理。

如果有任何问题，欢迎随时创建新的 issue :)

**Comment by DercilioFontes** [comment]
It is working fine now! Thanks.
