### ISSUE TITLE
Highlighting when dropdown menu item is a popconfirm

### ISSUE THREAD

**Issue by FearZee** [ant-design/ant-design#45173]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-violet-f8ftwj?file=/src/App.tsx)

### Steps to reproduce

1. Open Dropdown Menu
2. Click on menu item
3. Popconfirm opens, dropdown menu keeps open
4. Move mouse outside of dropdown and menu, and back in

### What is expected?

Selected dropdown items keeps highlighted

### What is actually happening?

Hightlight changes even when popconfirm is left. The popconfirm extends the highlighting effect/hovering

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | React v18.2 |
| System | macOS |
| Browser | Chrome |

![poconfirm](https://github.com/ant-design/ant-design/assets/38909210/06695da5-7440-47d8-b113-b1f397d9dec7)
I dont know why the box shadow is bugged on this recording..

**Comment by Yuiai01** [comment]
Perhaps should add an active state style to its menu item after clicking.

**Comment by MadCcc** [comment]
Because `getPopupContainer={(trigger) => trigger.parentElement!}` makes Popconfirm inside menu item.
I believe that you add this configuration due to `z-index` problem, we have a RFC on it: https://github.com/ant-design/ant-design/discussions/45154

Currently you can set `z-index` of Popconfirm separately with ConfigProvider `theme`.

```
<ConfigProvider
  theme={{
    components: {
      Popconfirm: {
        zIndexPopup: 1000
      }
    }
  }}
>
```
