### ISSUE TITLE
The icon of Message component is not horizontally centered.

### ISSUE THREAD

**Issue by recallwei** [ant-design/ant-design#45192]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-message-style-bug-s2tfs5?file=/index.css)

### Steps to reproduce

Click the show message button.

### What is expected?

The icon and text should be horizontally centered samely.

### What is actually happening?

The text works, but the icon does not work.

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | macOS M2 14.0 (23A344) |
| Browser | 117.0.5938.149 |

---
I change the font family, if I don't use another font, it will work. But I think it should not be the problem of custom font.

**Comment by MadCcc** [comment]
Noticed that you are using your own font family, which make line height different from antd.

Icon is maked aligned with first line, and this would be broken if you use different font-family since we will not apply center alignment to icons and texts for multiple lines.

You could align them yourself by overriding the styles in your app currently, which may be a workaround.
