### ISSUE TITLE
zIndexPopupBase is not reflected for confirmation modals (Unable to stack modals properly)

### ISSUE THREAD

**Issue by vict-shevchenko** [ant-design/ant-design#45237]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-9-4-forked-gg538x)

### Steps to reproduce

1. Using Antd "ConfigProvider" to increase zIndexPopupBase value (for example to 1055)
2. Open Modal
3. Inside Modal open confirmation Modal

### What is expected?

Confirmation modal to have the same z-index as regular Modal and to be displayed above regular modal

### What is actually happening?

Confirmation modal receives a z-index of 1000 and is displayed below the regular modal. Due to increased zIndexPopupBase regular modal has a z-index of 1055.

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.0.0 |
| System | Mac OS latest |
| Browser | Chrome latest |

---
If zIndexPopupBase is not applied - everything works well. Both confirm and regular modals get z-index 1000 and are property displayed one over another.

**Comment by Yuiai01** [comment]
It appears that the internal `Modal` did not apply `zIndexPopupBase`.

**Comment by Yuiai01** [comment]
> It appears that the internal `Modal` did not apply `zIndexPopupBase`.

@vict-shevchenko This is because the static methods of Modal cannot consume the [ConfigProvider](https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx). But you can [useModal.useModal](https://ant.design/components/modal#modalusemodal) or [App component ](https://ant.design/components/app).

**Comment by Yuiai01** [comment]
@vict-shevchenko This is because the static methods of Modal cannot consume the [ConfigProvider](https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx). But you can [useModal.useModal](https://ant.design/components/modal#modalusemodal) or [App component ](https://ant.design/components/app).

**Comment by vict-shevchenko** [comment]
Many thanks. Clear now.

**Comment by vict-shevchenko** [comment]
Hi, I would appreciate it if you could suggest. Seems because of the same issue I can not style "dropdow menu" I need to change a selected color of the item in the dropdown. Here is what I use 

```
<ConfigProvider
      theme={{
        components: {
          Menu: {
            itemSelectedColor: 'red',
          },
        },
      }}
    >
```

But this only changes its code in Menu but not in Menu of a Dropdown


Here is a demo: https://stackblitz.com/edit/react-4ecccp?file=demo.tsx
