### ISSUE TITLE
defaultPickerValue个人感觉不该被弃用

### ISSUE THREAD

**Issue by zcSkr** [ant-design/ant-design#45382]
### What problem does this feature solve?

1.官方弃用的原因是觉得源代码和defaultValue取值是一样的
2.但是场景在RangePicker上不一样，表象是 defaultValue是显性的，能看见值，而defaultPickerValue是隐性的，控制的是展开后面板的默认时间。
3.所以因为DatePicker就把RangePicker 的defaultPickerValue都砍掉的话不合理。

### What does the proposed API look like?

期望RangePicker还是有defaultPickerValue。例如defaultPickerValue: [dayjs().subtract(2, 'month'), dayjs().subtract(1, 'month')]
控制的是展开后的面板控制在8月 - 9月。而不是通过defaultValue来让输入框显示。

**Comment by crazyair** [comment]
`defaultPickerValue` or `pickerValue` 这应该就是控制面板的默认展示日期，如果没有才可以使用 `defaultValue` or `value`
`pickerValue` 这好像目前还不支持

我理理，是不是有3套字段

`deaultValue` `value`
`defaultPickerValue` `pickerValue`
`defaultOpenValue` `openValue`

`openValue`  应该可以去掉

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行处理。

如果有任何问题，欢迎随时创建新的 issue :)
