### ISSUE TITLE
[Timepicker] am-pm/AM-PM format does not pick it up when typed manually

### ISSUE THREAD

**Issue by mrLuisFer** [ant-design/ant-design#45463]
### Reproduction Link

[https://3x.ant.design/components/time-picker/#components-time-picker-demo-12hours](https://3x.ant.design/components/time-picker/#components-time-picker-demo-12hours)

### Steps to Reproduce

Click on the Timepicker component and manually type in some time following the format. For example, `12:32:22 AM` for `format="h:mm:ss a"` or `12:32:22 am` for `format="h:mm:ss A"`, and press the Enter key (or notice that it does not recognize it as a valid time).

### Expected Behavior

I would expect it not to be case-sensitive for the format, allowing both `A` and `a`, and accepting both `am` and `AM`.

### Actual Behavior

Currently, it does not accept the am-pm format when it does not match the format. I would like to know if there is a way to make it accept both.

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 16.8.3 |
| System | macOS Sonoma 14.0 |
| Browser | V118.0.5993.70 (arm64) |

---
I remain attentive to whether this behavior is a result of an internal decision or if it can be modified with some prop ;)

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
