### ISSUE TITLE
Timepicker validations are not working properly

### ISSUE THREAD

**Issue by shirodkarpushkar** [ant-design/ant-design#45489]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hrrnhh?file=/index.js)

### Steps to reproduce

1. Select Date and Time from the DatePicker dropdown
2. Update Time Value exceeding the disabled value using keyboard and press enter , this will update time value exceeding the disabled value

### What is expected?

Time value should have not updated to a value in range of disabled values of time. It should have reverted to the old correct value which was picked using UI at step1 analogous to the behavior of date

### What is actually happening?

Time value can be updated to a value in range of disabled values of time using keyboard.

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.0.2 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
