### ISSUE TITLE
DatePicker.RangerPicker 不使用 defaultPickerValue 默认面板日期失效

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#45528]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuan-ze-bu-chao-guo-qi-tian-de-fan-wei-antd-5-10-2-forked-lgcj72?file=/demo.tsx)

### Steps to reproduce

打开日期面板

### What is expected?

默认显示 1-2月

### What is actually happening?

显示10-11月

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
这是 bug 么？代码里打开 DatePicker 的时候手动把 value 清空了，这样预设的日期面板自然应该是不生效的。

**Comment by crazyair** [comment]
> 这是 bug 么？代码里打开 DatePicker 的时候手动把 value 清空了，这样预设的日期面板自然应该是不生效的。

面板清空是为了禁用日期范围场景使用的，默认显示月份还是需要跟 value 对应

**Comment by afc163** [comment]
value 都被清空了，怎么确定默认显示哪个月份呢？

**Comment by crazyair** [comment]
> value 都被清空了，怎么确定默认显示哪个月份呢？

value 是假象清空，属于限制范围特定的交互，只有这样，才能再次选择开始结束时间，如果不清空，则无法重新选择开始结束时间

**Comment by zombieJ** [comment]
这个 7 天范围的例子，我重构后会加更简单的实现方式。现在这个例子有很多犄角旮旯的交互问题。

**Comment by afc163** [comment]
还是得把面板日期拿回来：https://github.com/ant-design/ant-design/issues/45382

**Comment by yoyo837** [comment]
打算直接revert有关pr还是豆酱在大重构里做？

**Comment by yoyo837** [comment]
> 打算直接revert有关pr还是豆酱在大重构里做？

露看前面了，看来是走后面这条路

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
