### ISSUE TITLE
Date in TimePicker is set to today when using keyobard

### ISSUE THREAD

**Issue by andrewslock** [ant-design/ant-design#45564]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-24-14-forked-23tgyj?file=/demo.tsx:489-499)

### Steps to reproduce

1) Take a look at the initial date (const initialValue), it is set to "2023-09-09 04:00:00".
2) Pick another time in the TimePicker using ONLY mouse/trackpad (for example 07:03:03) and click OK.
3) Take a look in the console, now the value is "2023-09-09T07:03:03"
4) Pick another time in the TimePicker using ONLY keyboard (for example, clear it and type 08:08:08) and click OK.
5) Take a look in the console, now the value is "2023-10-27T08:08:08" (the month and the day is set to today (changed from 2023-09-09 to 2023-10-27))

### What is expected?

The value is "2023-09-09T08:08:08"

### What is actually happening?

The value is "2023-10-27T08:08:08"

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 18.0.0 |
| System | macos 13.4 |
| Browser | Google Chrome 114.0.5735.198 (Official Build) (arm64)  |

---
The day and month are set to today if you type in the input using keyboard and they stay the same if you select time using only your mouse/trackpad.
The bag persists in 5.x.x

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
