### ISSUE TITLE
Table filter dropdown overflows outside of the table on scrolling horizontally while it's open

### ISSUE THREAD

**Issue by LizaMaharjan2001** [ant-design/ant-design#45613]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-columns-antd-5-9-4-forked-y9vxg5)

### Steps to reproduce

- Open the link
- Click on the filter icon of the column ('Column 1')
- After the filter is opened, scroll the table without closing the filter
- The popped up filter container is overflowing out of the table

### What is expected?

- The popped up filter container to be inside of the table even after scrolling while it's open

### What is actually happening?

- The popped up filter container is overflowing out of the table while scrolling

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
It's by design to avoid filter length exceed the content:

<img width="511" alt="截屏2023-11-01 14 01 52" src="https://github.com/ant-design/ant-design/assets/5378891/c7d239a5-1e02-49db-9287-b942d13374c4">

You can use ConfigProvider with `getPopupContainer` to modify this behavior. but it will be cut for the above case:

<img width="510" alt="截屏2023-11-01 14 06 59" src="https://github.com/ant-design/ant-design/assets/5378891/91c743c0-6b12-45ff-8d05-0c68ca439b99">
