### ISSUE TITLE
DatePicker.RangePicker 组件在弹层受控时 blur 方法无效

### ISSUE THREAD

**Issue by bingqichen** [ant-design/ant-design#45647]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-5-10-3-forked-ysvrvl?file=/demo.tsx)

### Steps to reproduce

在面板展开状态受控时，失焦状态无法设置

### What is expected?

可以正确调用 blur 方法

### What is actually happening?

blur 方法无效

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18 |
| System | macOS |
| Browser | Chrome 118 |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-5-10-3-forked-fnrn6g?file=/demo.tsx

加一个延时，`setOpen` 需要等下一次 render 才能生效，导致 RangePicker 认为当前还是 `open` 状态所以强制设置了焦点。

**Comment by bingqichen** [comment]
> https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-5-10-3-forked-fnrn6g?file=/demo.tsx
> 
> 加一个延时，`setOpen` 需要等下一次 render 才能生效，导致 RangePicker 认为当前还是 `open` 状态所以强制设置了焦点。

感谢，确实可以，就是不知道官方有没有更棒的方法修复这个问题

**Comment by zombieJ** [comment]
我先记录一下，RangePicker 有一个比较麻烦的点在于有两个输入框。从一个切换到另一个时候，会依次触发 focus blur focus。所以在关闭的时候会延迟关闭。

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
