### ISSUE TITLE
[TimePicker]: Remove scroll in the format "hh:mm A" when selecting between AM or PM

### ISSUE THREAD

**Issue by mrLuisFer** [ant-design/ant-design#45691]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/12-hours-antd-5-11-0-forked-kkgkjt?file=/demo.tsx)

### Steps to reproduce

- Open popUp to select a time
- Click on `PM`, (this will move the scroll, making `AM` hide)

### What is expected?

A way, so that the scroll is only done in the hours, but not in `AM/PM` so that they remain static. 

### What is actually happening?

Clicking on `PM` causes `AM` to hide over it

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 16.8.3 |
| System | MacOs Sonoma 14.0 |
| Browser | V118.0.5993.70 (arm64) |

---
I was in doubt whether to report it as a **Bug** or a **discussion**, but if there is a way to modify the mentioned behavior it would be great, but also to know that this is an expected behavior.

**Comment by zombieJ** [comment]
`open` control is not well support since Picker has complex interactive logic. But yes, I think it's a bug.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
