### ISSUE TITLE
DatePicker defaultPickerValue

### ISSUE THREAD

**Issue by mikayel** [ant-design/ant-design#45699]
### What problem does this feature solve?

Please do not depreciate DatePicker defaultPickerValue, because defaultValue is preselecting a date, but for some applications, I need the user to make the selection of the required "Date of Birth" of the customer.

### What does the proposed API look like?

defaultPickerValue={()=> dayjs().add(-30, 'y')}

**Comment by zombieJ** [comment]
Yes. I'm working for refactoring. This prop will be fully controlled in future.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
