### ISSUE TITLE
RangePicker日期时间选择器先有交互很难满足限制用户选择区间小于哪个范围

### ISSUE THREAD

**Issue by HzhOvO** [ant-design/ant-design#45909]
### What problem does this feature solve?

例如我要限制用户选择的时间前后差不能大于1天，现有交互可能在没选的时候能限制到，但当我两个时间都选完以后再次打开无法感知到我聚焦的是前面的选择框还是后面的选择框导致根本不知道怎么限制用户选择的时间范围

### What does the proposed API look like?

希望聚焦的时候有api可以让我感知到我在修改前面的时间还是后面的时间

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by HzhOvO** [comment]
> What does the proposed API look like?

目前只是发现了问题，还没有去想怎么解决，官方可以先看看，后续我有好的想法会立刻提上来

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
