### ISSUE TITLE
State in modal is outdated

### ISSUE THREAD

**Issue by konossow** [ant-design/ant-design#46029]
### Reproduction link

[https://stackblitz.com/edit/react-jm5n2f?file=demo.tsx](https://stackblitz.com/edit/react-jm5n2f?file=demo.tsx)

### Steps to reproduce

1. Open an example
2. Click on the 'Info' button.
3. Inspect the console, foo variable is now 'bar'
4. Click on 'Invoke Callback Function'.
5. Inspect the console

### What is expected?

At step 5 there should be logged 'bar'

### What is actually happening?

At step 5 there is logged 'foo' instead.

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Config won't get updated since it was only called once, and the function remains unchanged so that you will always get 'foo' logged. You could find that it will changed to 'bar' if you reopen this Modal.

The right way to have state updated in Modal is to directly use Modal in your component instead of hook or static function.
