### ISSUE TITLE
Form Item cannot use getValueProps without valuePropName

### ISSUE THREAD

**Issue by kevinchen-pimq** [ant-design/ant-design#46417]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-tzg8yr)

### Steps to reproduce

Use `Form.Item` with a custom input component which don't have value prop.
Not provide `valuePropName` to `Form.Item` only use `getValueProps`.

### What is expected?

Input works normally without provide `valuePropName` to `Form.Item`.

### What is actually happening?

Input not working.
Need to provide `valuePropName`.

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | all |
| Browser | all |

---
According to document.
valuePropName:  This prop is an encapsulation of getValueProps, which will be invalid after customizing getValueProps.

**Comment by zombieJ** [comment]
Seems `getValueProps` not trigger the sub component update.

**Comment by LongHaoo** [comment]
<img width="445" alt="image" src="https://github.com/ant-design/ant-design/assets/45565100/b5d5322c-5d90-4a44-b63b-2805f0d33fd4">
 Incorrect memo value

**Comment by LongHaoo** [comment]
我想到的方案是在 getValueProps 和 valuePropName 都交给 rc-field 控制的前提下，透出一个 "memoValue" 纯净的值，通过这个值去控制组件的更新,在 antd 这一层不对 getValueProps 和 valuePropName 做任何的处理。

深入地去想一想🤔️，getValueProps 应该交给 antd 层而不是 rc，rc-field 应该就负责最纯净的数据更新与处理，对于 rc-field 来说不需要关心任何子组件需要传递的 props。它的职责就是 trigger 和传递 value。
valuePropName 应该同时作用于 getValueProps 与 trigger 函数，默认认为 event.target 与 ComponentProps 类型是相通的，比如 Checkbox,Switch。

所以有一个新的的方案就是将 getValueProps 交给 Form.Item 去处理而 rc-field 不进行任何处理，但是带来的副作用就是 rc-field 会有一个 break change 失去了 getValueProps 这个接口，但是让两个组件的职责更加清晰明了

English:
The solution I came up with is to reveal a pure "memoValue" value under the premise that getValueProps and valuePropName are both controlled by rc-field, and use this value to control the update of the component. The antd layer does not do anything with getValueProps and valuePropName. processing.

Think about it deeply🤔️, getValueProps should be handed over to the antd layer instead of rc. rc-field should be responsible for the purest data update and processing. For rc-field, there is no need to care about the props that need to be passed by any sub-component. Its responsibility is to trigger and pass value.
valuePropName should act on both getValueProps and trigger functions. By default, event.target and ComponentProps types are considered to be the same, such as Checkbox and Switch.

So there is a new solution which is to hand over getValueProps to Form.Item for processing without any processing in rc-field, but the side effect is that rc-field will have a break change and lose the getValueProps interface, but let the two Component responsibilities are clearer
