### ISSUE TITLE
Add support for responsive UI

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#4682]
If my viewport width is less than 990px then nothing is displayed except for the sidebar:
![image](https://cloud.githubusercontent.com/assets/10534563/22182144/bf174828-e0ae-11e6-8d60-aea01b24e5d3.png)

**Comment by afc163** [comment]
Just scroll down.

**Comment by avalanche1** [comment]
I don't think 'scroll down' is what is meant under 'responsive css'.
This sd be reopened and investigated whether this is expected behaviour of the Layout component.
If this is expected behaviour - this can't be called responsive design.

**Comment by afc163** [comment]
Yes, can't agree more 😅

**Comment by avalanche1** [comment]
Will you reopen?

**Comment by afc163** [comment]
Could you give us PR to improve responsive view of smaller device cause we are out of hands recently.

**Comment by avalanche1** [comment]
I will try to look into it, but anyway it's better to keep known issues open, even if we can't fix them right away. So that we can do that when we have the time :smile:

**Comment by benjycui** [comment]
ping~

**Comment by kprathapk** [comment]
Ant ui components are good but on part of implementing Responsive UI using ant is not easy.
No proper written examples or document compared to bootstrap.

**Comment by benjycui** [comment]
@kprathapk hope that you can provide detailed advice 😄

**Comment by kprathapk** [comment]
@benjycui Let me clearly explain this to you..
1. The menu, Header components are not going to be responsive by default. (check bootstrap for reference)
2. For a fixed Menu on top, the can't make it center aligned unless we write some stupid hacks.
3. Why we need .ant-layout { overflow: auto } for a fixed header? due to this, if we remove styles from component then it behaves weirdly.

Why I am saying that most of the stuff is not responsive is, see we don't use 100% fluid container all the time. Sometimes we want to go with fixed layout like 960px, then creating header, navigation components responsive is a headache.

**Comment by jljsj33** [comment]
https://github.com/ant-motion/drawer-menu

Component has been developed, I will be revised in the near future

**Comment by JesperWe** [comment]
How come `rc-drawer-menu` is a dev dependency? Shouldn't it be a normal dependency?

**Comment by afc163** [comment]
@JesperWe just for site.

**Comment by JesperWe** [comment]
@afc163:  I see.  I was hoping a responsive drawer was coming to antd. It would be a very welcome addition.

**Comment by andriijas** [comment]
@afc163 consider replacing Layout.Sider with rc-drawer-menu,  thanks

**Comment by zachguo** [comment]
Another reason why `rc-drawer-menu` may be better than current collapsable `Sider` is that, it won't trigger a relayout or repaint of `Content`, which makes animation laggy, especially when you have tables in `Content`.

**Comment by andriijas** [comment]
layout.sider is 5k, rc-drawer-menu is almost 10k.
