### ISSUE TITLE
DatePicker with showTime ignores cellRender for time picker part

### ISSUE THREAD

**Issue by SAUn1t** [ant-design/ant-design#47416]
### Reproduction link

[https://stackblitz.com/edit/react-a3im3u?file=demo.js](https://stackblitz.com/edit/react-a3im3u?file=demo.js)

### Steps to reproduce

open picker
check console - it's empty

### What is expected?

should be console loged cellRenderInner

for example, showTime property minuteStep does not ignored as you can see in picker

### What is actually happening?

DatePicker showTime.cellRender seems to be ignored now

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2.0 |
| System | Win 11 |
| Browser | Chrome |

**Comment by SAUn1t** [comment]
seems like you forgot to add cellRender in SharedTimeProps
![image](https://github.com/ant-design/ant-design/assets/24840202/9c647268-1b1f-496a-956e-0e1f705289e3)

**Comment by MadCcc** [comment]
Place `cellRender` on TimePicker, not inside `showTime`

**Comment by joshua-lehmann** [comment]
Hi @MadCcc, @SAUn1t 
The suggested workaround of putting `cellRender` on a separate `TimePicker` is **not equivalent** to using `showTime` on `DatePicker`.

* With `DatePicker + showTime`, we get a single, integrated component where date and time share the same `value` and `onChange`. This is required for consistency in state handling and UI.
* With a separate `TimePicker`, we end up with **two disconnected components**. That means extra state syncing, different `onChange` contracts, and a visually disjointed UI.

Our use case requires applying the same `cellRender` logic to both the date grid and the integrated time columns inside `DatePicker`’s `showTime` panel. Right now `cellRender` only applies to the date cells, and there’s no way to hook into the time cells when using `showTime`.

This is a **missing feature**, not a usage error. To be clear:

* Expected: `DatePicker` with `showTime` should support `cellRender` (or a new prop like `timeCellRender`) that affects the integrated time panel.
* Actual: We must drop down to a separate `TimePicker` to get time cell rendering, which breaks the unified Date+Time workflow.

Can this issue be reopened so that `DatePicker` supports time cell rendering when `showTime` is enabled?
