### ISSUE TITLE
Dropdown 使用<Dropdown menu={{ items: [...] }} />方式时，希望点击整个Item都能触发Popconfirm

### ISSUE THREAD

**Issue by Sharang-heng** [ant-design/ant-design#47630]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/jian-tou-antd-5-14-1-forked-4fqm4j?file=%2Fdemo.tsx%3A8%2C4)

### Steps to reproduce

```
const items: MenuProps["items"] = [
    {
      key: "delete",
      label: (
        <Popconfirm
          placement="topLeft"
          title="确认删除该会话吗"
          onConfirm={(e) => {}}
        >
          <span
            onClick={(e) => {
              e.stopPropagation();
            }}
          >
            删除
          </span>
        </Popconfirm>
      ),
      icon: (
        <Icon
          component={() => ()}
        />
      ),
    },
  ];
```
目前只找到用Popconfirm包裹label，但是因为存在padding，导致用户有时点击不会触发Popconfirm

### What is expected?

点击Item都会触发

### What is actually happening?

label外的区域不触发

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 17.0.2 |
| System | window |
| Browser | Chrome |

**Comment by afc163** [comment]
span 改成 a 试试

**Comment by renny-ren** [comment]
I'm facing the exactly same issue, my scenario is trying to hover and show the dropdown, then click the `delete` button, then confirm to delete.
![image](https://github.com/ant-design/ant-design/assets/19547819/b761e881-48c7-4fb9-a6f1-27b53945b0af)

The issue is that the element in `items label` is wrapped in the `<li>` node, so I have to click exactly on the text instead of the menu item to open the Popconfirm.

![image](https://github.com/ant-design/ant-design/assets/19547819/4ba354e8-a6e0-476a-974e-12e557563eee)
![image](https://github.com/ant-design/ant-design/assets/19547819/1a11c020-8743-4352-bcca-3410b3832474)

**Solution:**
Change `<span>` to `<a>` worked for me!

```html
<span
  onClick={(e) => {
      e.stopPropagation();
    }}
  >
    delete
  </span>
```
changes to 

```html
<a
  onClick={(e) => {
    e.stopPropagation();
  }}
>
  delete
</a>
```

BTW, I also have tried to control the `open` status of `Popconfirm` manually, set state by the menu item `onClick` event. But that didn't work because setState is asynchronous.
