### ISSUE TITLE
Switch themes in UI

### ISSUE THREAD

**Issue by varun-dev** [ant-design/ant-design#4837]
Hi,

What would be the best way to switch themes in the UI ?
Anyone has tried this yet?

Thanks

**Comment by benjycui** [comment]
Bundle several `antd.theme-x.css` with different themes, ant modify `<link href="xxx" />` dynamically.

**Comment by varun-dev** [comment]
I am not sure how snappy it would be as downloading a new file may take time so you can expect a delay.
I am going to investigate on namespacing the two themes with a theme name at top and having both the themes loaded in the UI

**Comment by benjycui** [comment]
Yep, it's not convenient to change antd theme dynamically now.

**Comment by nisimjoseph** [comment]
do you have today a way to change theme quicker? just change colors somewhere in the app and it will influence the entire UI?

**Comment by mzohaibqc** [comment]
@varun-dev That is possible because on Ant Design website there is a color picker to change theme's primary color instantly in all components but I don't know how are the doing. I am finding solution for that. If you have any solution, kindly share
Currently, I'm trying to send custom variables in POST request to server and then returning generated css and replacing the old one but there are some issues.

**Comment by wahidshafique** [comment]
@varun-dev Hey! Where exactly is that in the Antd docs?

**Comment by varun-dev** [comment]
@nisimjoseph - in our project, we are loading the stylesheet of two themes at once. We names space the two themes with a class, so as soon as you change the classname, the whole theme loads immediately without needing to download a new css file

@wahidshafique - I am not sure what you are referring to, here is a link to the theming
https://ant.design/docs/react/customize-theme

@mzohaibqc - Will have a look at your work, thanks for sharing.

**Comment by bobbui** [comment]
this is another good option to implement theme switcher https://github.com/mzohaibqc/antd-theme-webpack-plugin
