### ISSUE TITLE
Inconsistency in border styling of disabled form controls

### ISSUE THREAD

**Issue by jljouannic** [ant-design/ant-design#48532]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-nuhqcw?file=demo.tsx)

### Steps to reproduce

- Open the minimal reproduction link,
- Click on the "Submit" button of the form,

### What is expected?

Both fields should be styled with a red border

### What is actually happening?

The `Input` field is not styled with a red border, but the `Select` field is.

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Firefox 125.0.1 |

**Comment by coderz-w** [comment]
<img width="359" alt="屏幕截图 2024-04-19 000503" src="https://github.com/ant-design/ant-design/assets/116932167/990a2ade-bc42-4dcc-9f95-30004a947504">

This is because the error style of the input component is excluded when it is disabled. You can try removing the disable attribute of the input component so that the styles of the two components can be rendered correctly

**Comment by jljouannic** [comment]
> This is because the error style of the input component is excluded when it is disabled.

This is exactly what I am pointing with this issue. The error style is not applied on the `Input` component when it is `disabled`, but it is applied on the Select component, even if `disabled`. Hence the inconsistency.
