### ISSUE TITLE
checkboxgroup doesn't rerender if value is set by form.setFieldsValue

### ISSUE THREAD

**Issue by AhmedSayed77** [ant-design/ant-design#4872]
#### Environment(required)

- antd version: 2.7.0
- OS and its version: ubuntu 16.04
- Browser and its version: chrome 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

Try two set checkboxgroup programmatically

#### What do you expected?

The value changes and the checkboxes in the value array are checked

#### What happen?

the checkboxes are not checked

#### Re-producible online demo

http://codepen.io/anon/pen/Lxqaez?editors=001

**Comment by benjycui** [comment]
`valuePropName` of `Checkbox.Group` should be `value` instead of `checked`, see: https://ant.design/components/checkbox/#components-checkbox-demo-group

Ant Design team use GitHub issues to trace bugs or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions.

You should read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before ask a question, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by AhmedSayed77** [comment]
Thanks for the reply and sorry for the misusage

**Comment by zhuqingguang** [comment]
How about adding a clear usage example or note about when to use 'checked' or 'value' ? I have read the document, but I only find this:
![image](https://user-images.githubusercontent.com/24694223/38234512-a708e8aa-3750-11e8-9b06-4e124cb93598.png)

This is very misleading.
