### ISSUE TITLE
Input.OTP numeric values only

### ISSUE THREAD

**Issue by anotheri** [ant-design/ant-design#49049]
### What problem does this feature solve?

Now it's possible to input any symbol into the OTP field. It'd be helpful to have a prop which makes sure that it's possible to input (type or paste from the clipboard) only the symbols which passes the certain regex (e.g. numbers only).

### What does the proposed API look like?

`<Input.OTP allowedSymbols={/\d/} />` or `<Input.OTP type="numeric" />`, `<Input.OTP type="alphanumeric" />` as presets/shortcuts

**Comment by pranav-inaira** [comment]
`<Input.OTP
                    inputMode='tel'
                    type="tel"
                    input
                    length={6}
                    onChange={onChange}
                    size='large'
                    value={otp}
                     />
                <>`
                
                I have tried this code & its not working

**Comment by hemanth12321** [comment]
Didn't expect this from Antd. 

1. The Input.Otp component doesn't work with Form element although they have used it in their documentation. It throws `" Form. The issue is when I click on submit it gives me only the  last entered number of otp. And in console it says"`
2. There is no way to store the otp value in local state, there is only one function which gets triggered when the user enters all the digits of the OTP. If I want to trigger otp submit from another button there is no way for me. 

I searched through the API documentation couldn't find any possible solutions. If any one has any solution, pls let me know.

Workaround - I'm storing the otp value when onChange is triggered and if user clicks on Submit OTP button I'm using that value.

**Comment by afc163** [comment]
Closed by https://github.com/ant-design/ant-design/pull/50811

**Comment by nathanredblur** [comment]
This not work in safary. 

I have something like this
```
import {
    InputNumber,
} from 'antd-v5';

<InputNumber
    type="number"
    min={0}
    stringMode={false}
    inputMode="numeric"
    pattern="[0-9]*"
    style={{ width: '100%' }}
    placeholder={field.label}
/>
```

and nothing works, every time I type any letter in this input in safari, I get that letter printed in the input box.

I create this sandbox, https://codesandbox.io/p/sandbox/basic-antd-5-23-1-forked-8jy68s
try it in safari vs any other browser

**Comment by pedramalipour** [comment]
Just add `type="number"`

```
<Input.OTP
      type="number"
/>
```
