### ISSUE TITLE
add props name to Select component

### ISSUE THREAD

**Issue by zMohammadz84** [ant-design/ant-design#50160]
### What problem does this feature solve?

I can't set name to Select component for control it , Please add name prop for Select component.

### What does the proposed API look like?

Please add name prop for Select component.

**Comment by MadCcc** [comment]
Please use state to control Select, or do you have any special usage?

**Comment by zMohammadz84** [comment]
> Please use state to control Select, or do you have any special usage?

When I want to use react hook form next to antd. I have to choose a name for the Select.. but there is no such props for the Select component ??? Although input is used inside the Select component.

**Comment by zombieJ** [comment]
I'm not use `react-hook-form`, but it seems should ask question for `react-hook-form` instead. It should have the way to control HOC component since not all the HOC component can align with native. Here is my google result, maybe help:

https://codesandbox.io/p/sandbox/antd-react-hook-form-9j9br?file=%2Fsrc%2Findex.tsx%3A45%2C5-45%2C13
https://javascript.plainenglish.io/combining-react-hook-form-and-ant-designs-input-component-for-efficient-form-handling-7606a38ff7c1
