### ISSUE TITLE
Tabs支不支持切换的时候只隐藏Panel，而不是销毁

### ISSUE THREAD

**Issue by avwo** [ant-design/ant-design#5020]
RT

**Comment by afc163** [comment]
It is not destory now. And default value of `destroyInactiveTabPane` in `false`: https://github.com/react-component/tabs#props

<img width="868" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23246512/3ec486ba-f9cf-11e6-870c-c99d6bb56969.png">

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!
