### ISSUE TITLE
antd.css breaks layout

### ISSUE THREAD

**Issue by kossel** [ant-design/ant-design#5032]
Please see this simple code:
http://codepen.io/kossel/pen/BWaZoX

It imported antd.css but not even using any ant components

resize the "preview" panel to smaller than the text box and scroll, you will notice the background only fill the current view size:
![image](https://cloud.githubusercontent.com/assets/1760498/23274108/1e3a0d28-f9c7-11e6-8d1f-4e56d87818f1.png)

if I remove `height:100%;` from `.olr-MainPage` class solves that problem but if the view size is large, then there is blank space:
![image](https://cloud.githubusercontent.com/assets/1760498/23274190/59acc7ba-f9c7-11e6-8a85-c36d46967944.png)

but if you remove https://unpkg.com/antd/dist/antd.css from codepen.io settings, everything works just as expected. (http://codepen.io/kossel/pen/zZYwzq)

is this a bug?

**Comment by NE-SmallTown** [comment]
@kossel The second is fine just because you cont' use `height: 100%` on body and html tag.The first one doesn't work just because you use `height: 100%` on `your own container`,cause that your `height` decided by `body`,and `body` decided by `html`,and `html` decided  by the viewport `height`,so the result is viewport `height`,not all content's `height` .

So,you can remove your `container`'s `height: 100%` or add `min-height` is fine.

**Comment by benjycui** [comment]
Because `antd` had [reset html and body's style](https://github.com/ant-design/ant-design/blob/4e59e9e769ebc7273a999cb2b28a73b2cff26a49/components/style/core/base.less#L14-L16)

I think it's OK, and impossible to change for it will be a breaking change.
