### ISSUE TITLE
treeSelect 下拉数据过长时下拉框位置变动

### ISSUE THREAD

**Issue by smart1993** [ant-design/ant-design#5034]
问题描述：
使用treeSelect组件时，当下拉的可选项较多时，展开/收拢操作后下拉框位置变动：
第一次，点击展开：
![image](https://cloud.githubusercontent.com/assets/6806376/23288017/e3b28652-fa7b-11e6-878e-e2aa9a3748fe.png)
第二次，点击展开一个选项较多的下拉选项：
![image](https://cloud.githubusercontent.com/assets/6806376/23288040/03bde6c6-fa7c-11e6-80ca-047469ff4149.png)
第三次，收拢这个选项后，下拉框位置变化:
![image](https://cloud.githubusercontent.com/assets/6806376/23288061/241581f4-fa7c-11e6-9d2e-d97c3ea702d3.png)
此外，在下拉选项较多的情况下，treeSelect支持select组件的下拉滚动条吗？
antd version：1.6.5
Browser version: Chrome  56.0.2924.87

**Comment by afc163** [comment]
https://ant.design/components/tree-select/#components-tree-select-demo-basic

`dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}`

**Comment by RaoHai** [comment]
The 2nd demo of TreeSelect passed a maxHeight in dropdownStyle. You mean we should offer a default `maxHeight` value to dropdownStyle of TreeSelect ?

**Comment by benjycui** [comment]
Actually, this is a expected behavior of `dom-align`.

**Comment by afc163** [comment]
@RaoHai No, we need to find what can we do about auto align.

**Comment by RaoHai** [comment]
Eureka！

1. https://github.com/yiminghe/dom-align/blob/master/src/index.js#L118 , could not put element in virtical direction, fip.

2. recalc region: https://github.com/yiminghe/dom-align/blob/master/src/index.js#L154 ,  into https://github.com/yiminghe/dom-align/blob/master/src/adjustForViewport.js#L33 , then top fit top edge of viewport, and height fit rect, issue occur.

Improvement.

1. When cannot put element in direction, calc width or height of flipped region, if large than origin, then flip it, otherwise, do nothing.

2. Other edge of element always not cover trigger element.

**Comment by afc163** [comment]
I agree with @RaoHai 👍 I th

1. Don't re-align when the other direction is can't fit either.
2. Don't  cover trigger element always.

I think we can resolve https://github.com/ant-design/ant-design/issues/3992 by this way too.

@yiminghe

**Comment by RaoHai** [comment]
@afc163 but if target region is large than origin region, re-aligin is better solution.

re-align rule is better follow this principle. always use larger region.
