### ISSUE TITLE
Layout Issues When Using sticky and virtual Simultaneously in Table

### ISSUE THREAD

**Issue by imamaad** [ant-design/ant-design#50471]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-eym5dx?file=demo.tsx)

### Steps to reproduce

1. Create a table with a large number of columns or rows.
2. Enable the `virtual` feature to optimize the display of the table data.
3. Activate the `sticky` feature to keep some columns or rows fixed during scrolling.
4. Render the table.

### What is expected?

The table should render correctly, with sticky columns or rows properly fixed in place.

### What is actually happening?

The table layout breaks, with sticky columns or rows not properly staying fixed, leading to a distorted table display.

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18.2.0 |
| System | All systems |
| Browser | All Browsers |

**Comment by zombieJ** [comment]
sticky deps on the `sticky` style. So when you use `absolute` container which break the `sticky`:
https://stackblitz.com/edit/antd-reproduce-5x-gzwez2?file=demo.tsx

**Comment by zombieJ** [comment]
css `position: sticky` deps on the parent nodes `position`. So it will follow the `absolute` position by the parent div. It can realize in css style. You can consider to use js sticky resolution to dynamic adjust container div position with `components` API.
For antd side, we may not fallback to use js since it will take much perf cost.
