### ISSUE TITLE
Documentation states that Tabs.TabPane will be removed in 5.0, but it is still working

### ISSUE THREAD

**Issue by mfialko** [ant-design/ant-design#50591]
### Reproduction link

[https://codepen.io/mfialko/pen/vYqrzpj?editors=001](https://codepen.io/mfialko/pen/vYqrzpj?editors=001)

### Steps to reproduce

1. Go to documentation and see message
2. Try to use Tabs.TabPane instead of items

### What is expected?

In discussions and documentation (https://4x.ant.design/components/tabs/), it is stated that the use of Tabs.TabPane is deprecated and will be removed in version 5.0.0.

### What is actually happening?

I see that the community has met this change with some skepticism, judging by this thread (https://github.com/ant-design/ant-design/issues/42021). Additionally, discussions about the benefits and effectiveness are not happening at all (https://github.com/ant-design/ant-design/discussions/43152). Tabs.TabPane is no longer in the documentation, but they still haven't been removed, despite the fact that it was promised.

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18.0.0 |
| System | MacOS |
| Browser | Chrome |

---
So, is it worth switching to items and not sticking with Tabs.TabPane? Will they continue to be supported in the future, considering they still haven't been removed?

**Comment by zombieJ** [comment]
Using the jsx structure for data collection is very inefficient because it cannot be memoized and will be re-collected on each render. In addition, it's not a real ReactElement which not support HOC.

For developer to have enough time to update, we do the follow step:

1. Deprecated in current version.
2. Remove in doc in next major version.
3. Remove the compatible code in next next major version.
