### ISSUE TITLE
Typography.Paragraph expand issues

### ISSUE THREAD

**Issue by tienviplaanh** [ant-design/ant-design#50728]
### Reproduction link

https://ant.design/components/typography#typography-demo-suffix

### Steps to reproduce
You can try the demo on antd page

It has an issue where, on the first render, it displays the entire text before collapsing it, which looks very irritating." Look at this demo on the homepage of Antd, if you reload the page, you'll see the text flicker momentarily. 

### What is expected?

I expected the page not to render a full paragraph upon initial load.

### What is actually happening?

On the initial render, the text would collapse, displaying the entire text before collapsing, which was very irritating.

| Environment | Info |
| --- | --- |
| antd | 5.20.5 |
| React | nextJS |
| System | Window |
| Browser | chorme |

**Comment by zombieJ** [comment]
It's by design.

When config the `expandable` or `copyable` or any other ability that can not use native css ellipsis. It will first render the full content and use js ellipsis with effect. Since for the SSR case, server do have the client info. If render empty will get SEO bad recording.

If want to use native css ellipsis, you can consider not config the additional ability of the Typography.
