### ISSUE TITLE
Layout siderbg not work

### ISSUE THREAD

**Issue by hmz22** [ant-design/ant-design#50759]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-rdkece?file=demo.tsx,index.css)

### Steps to reproduce

when try change bgBase or component layout bgSider not effected.

### What is expected?

must change background color of sider 

### What is actually happening?

--

| Environment | Info |
| --- | --- |
| antd | 5.20.5 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | chrome |

**Comment by LLmoskk** [comment]
@hmz22
![image](https://github.com/user-attachments/assets/36f1cf7a-ff74-4b34-8648-73b5f066c0e6)
Because you have set the siderBg token of the Layout component, ConfigProvider needs to wrap the Layout component to be set. If you don't want the innermost Layout to be affected, you can use App to reset 
eg: https://ant-design.antgroup.com/components/app

**Comment by hmz22** [comment]
I have two sider and need one of the sider configprovider change what should i do? Can show with example

**Comment by LLmoskk** [comment]
> I have two sider and need one of the sider configprovider change what should i do? Can show with example

https://stackblitz.com/edit/react-rdkece-h4ca3m?file=demo.tsx

**Comment by hmz22** [comment]
this my layout:
https://stackblitz.com/edit/react-rdkece-mqmyrw?file=demo.tsx
I need just one of sider bg change

**Comment by LLmoskk** [comment]
This is my layout: https://stackblitz.com/edit/react-rdkece-mqmyrw?file=demo.tsx I need just one of sider bg change

I see that the sidebar background has been changed to color rgb(56,144,226) ,  do you mean the color of the menu should be changed https://stackblitz.com/edit/react-rdkece-wleqrx?file=demo.tsx

**Comment by LLmoskk** [comment]
> this my layout: https://stackblitz.com/edit/react-rdkece-mqmyrw?file=demo.tsx I need just one of sider bg change

I see that the sidebar background has been changed to color rgb(56,144,226) , do you mean the color of the menu should be changed https://stackblitz.com/edit/react-rdkece-wleqrx?file=demo.tsx

**Comment by hmz22** [comment]
I know how change menu bg but if see I have two sider in Layout and need change bg change one of those:
https://stackblitz.com/edit/react-rdkece-eddura?file=demo.tsx
I handle it with style but I like use ConfigProvider because I have multiple them e.g. dark mode light mode and green mode

**Comment by LLmoskk** [comment]
I know how to change the menu background, but if you see, I have two siders in the layout and need to change the background of one of those: https://stackblitz.com/edit/react-rdkece-eddura?file=demo.tsx. I handled it with style, but I would like to use ConfigProvider because I have multiple options, such as dark mode, light mode, and green mode.

https://stackblitz.com/edit/react-rdkece-q18qy7?file=demo.tsx   Like this?

**Comment by LLmoskk** [comment]
> if see my code I have two sider in layout I need one of them different backgroundColor one red other blue if ConfigProvider don't support each Sider I must change one of them backgroundColor with style property. am I wrong?

Sorry, I misunderstood before. Now I understand. It seems that if only siderBg is specified in the Configurator, it will affect everything. Currently, it seems that we cannot tell the Configurator how to distinguish between different<Sider/>. Perhaps we can only use useTheme to get the theme change and then modify the inline style of the red sider.

**Comment by zombieJ** [comment]
Sider should support `ConfigProvider` wrap but seems currently is attach to the Layout. I think it can be improved
