### ISSUE TITLE
The Tour title will cover the close button at a certain length

### ISSUE THREAD

**Issue by mintsweet** [ant-design/ant-design#50919]
### Reproduction link

[https://codepen.io/mintsweet/pen/xxovrPB?editors=0010](https://codepen.io/mintsweet/pen/xxovrPB?editors=0010)

### Steps to reproduce

Set a longer title that does not wrap

### What is expected?

Separate title and close button

### What is actually happening?

Title will cover close button

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | MacOS 14.6.1 |
| Browser | Chrome 128.0.6613.138 |

**Comment by w2xi** [comment]
In fact, I found this bug was related to `Modal` component.

[Reproduction](https://codepen.io/w2xi/pen/RwXbLGM)

Simply setting the header's `padding-right: 32px` (equal to the width of  close button) works well:

![image](https://github.com/user-attachments/assets/eb6811e2-fbe3-4f23-812f-26bd10521b73)

But I ran into trouble when I cloned the `ant-design` repo and then tried to fix this bug.

I can simply add `paddingRight: token.modalCloseBtnSize` for the modal header:

`components\modal\style\index.ts`:
```ts
const genModalStyle: GenerateStyle<ModalToken> = (token) => {
  const { componentCls } = token;

  return [
    {
      [componentCls]: {
        [`${componentCls}-header`]: {
          color: token.colorText,
          background: token.headerBg,
          borderRadius: `${unit(token.borderRadiusLG)} ${unit(token.borderRadiusLG)} 0 0`,
          marginBottom: token.headerMarginBottom,
          padding: token.headerPadding,
          borderBottom: token.headerBorderBottom,
          paddingRight: token.modalCloseBtnSize, // new add
        },
      }
    }
  ]
}
```

Obviously, `paddingRight` and `padding` overlap, even though it works.

But, I don't know how to dynamically adjust `paddingRight` value based on the `closable` prop of the Modal.

We might not be able to access Modal's props in the context, right ?

Does someone have a good solution ?
