### ISSUE TITLE
passing button inline padding without block padding breaks the whole padding rule

### ISSUE THREAD

**Issue by Jamil-Bailony** [ant-design/ant-design#50921]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-dpbbef?file=index.tsx,demo.tsx)

### Steps to reproduce

The issue occurs when building the theme object for the button component. Setting the paddingInline prevents the other properties, specifically paddingBlock, from taking their default values, which breaks the padding rule for all buttons. We resolved the issue by explicitly setting the paddingBlock

### What is expected?

`paddingBlock` should take its default value.

### What is actually happening?

```
padding: NaNpx 16px;
```

* `NaN` should be the default value of the `paddingBlock` property.

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18.2.0 |
| System | Lunux, Ubuntu 24.04 |
| Browser | Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit) |

---
I have noticed that when setting `contentLineHeight` to a string, the issue happens, but when setting it to a number, the the `paddingBlock` will take its default value.

**Comment by Anju023** [comment]
maybe this will help
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by kiner-tang** [comment]
@Jamil-Bailony The contentLineHeight token must be set to number because it will participate in the default paddingBlock operation. It will work when you change contentLineHeight to number in your code.
![image](https://github.com/user-attachments/assets/71f0d3bc-10a3-4953-b42f-874740d4c1ec)
![image](https://github.com/user-attachments/assets/ef548571-6403-4f2f-9581-668f76f9b38f)
<img width="1765" alt="image" src="https://github.com/user-attachments/assets/e50bea4c-ae2b-4ea7-a2f0-1e49af43afab">
