### ISSUE TITLE
自定义的组件如何接收getFieldDecorator的options.initialValue？

### ISSUE THREAD

**Issue by zerozaki0752** [ant-design/ant-design#5098]

**Comment by afc163** [comment]
initialValue 默认会传递给任何表单组件的 value 属性（或 valuePropName 所指定的属性）。

请参考示例：https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!

**Comment by babycannotsay** [comment]
@afc163  自定义组件中包裹 表单组件，就拿不到 initialValue的值了， 比如

    const CustomFormComponent = () => <Input/>;

把这个作为FormItem的子组件，用getFieldDecorator包裹就拿不到initialValue

**Comment by babycannotsay** [comment]
另外 修改操作这个自定义组件 也不会触发 `Form.create()`中， `options`的`onFieldsChange`方法

**Comment by babycannotsay** [comment]
initialValue 可以通过prop.value 获得，， 要触发onFieldsChange方法，应该要在自定义组件中调用prop.onChange()

**Comment by awefeng** [comment]
prop.onChange()会触发validator自定义校验函数，这里是不应该触发的，有解决或者遇到的吗？
