### ISSUE TITLE
Button 组件如何通过点击获得 Input 组建的输入文本

### ISSUE THREAD

**Issue by gatsbychao** [ant-design/ant-design#5108]

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!
