### ISSUE TITLE
Anchor Link - Cannot read property 'props' of null

### ISSUE THREAD

**Issue by FacundoGFlores** [ant-design/ant-design#5129]
#### What did you do? Please provide steps to re-produce your problem.

Added conditional rendering to the link:

`{props.show && <Link href="#foo" title="foo">}`

#### What do you expected?

Just show the link when prop `show` is `true`

#### What happen?

Error:

```
Uncaught TypeError: Cannot read property 'props' of null
    at Anchor._this.renderAnchorLink
```

#### codepen

http://codepen.io/FacundoGFlores/pen/GWJdNK?editors=001

#### possible solution
I think it would be easy to solve it just adding: 
`var href = !!child ? child.props.href : null;`

**Comment by NE-SmallTown** [comment]
@FacundoGFlores Ye,I think it possibly is a bug.But your solution miss some situations.e.g,`{arr.length > 0 && <div>zzzz</div>}` or `{arr.length > 0 && 'xxxxx'}`

For your solution,it will still cause error because the elements above don't have `props` or `props.href` too.So I think judge the child whether is a instance of `Link` would be better.

**Comment by FacundoGFlores** [comment]
Yes, that's right. But we have to check child twice. First just for child and then for hrefs.
