### ISSUE TITLE
Buttons with variant "link" or "text" use the `info` color when the color is set to `primary`

### ISSUE THREAD

**Issue by AhmadMayo** [ant-design/ant-design#51343]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-s5ddw4)

### Steps to reproduce

- Customize primary color and info color
- Use a button and pass the props `color="primary" variant="text"`

### What is expected?

The text color should be the primary color

### What is actually happening?

The text color is the info color

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | doesn't matter |
| System | doesn't matter |
| Browser | doesn't matter |

**Comment by zombieJ** [comment]
It's by design since v4. Because some web app use `red` color as primary color. So it provide the info color for no-primary case.

**Comment by AhmadMayo** [comment]
@zombieJ I agree that this makes sense as a default for link and text buttons, but when the prop is explicitly `primary`, it should respect it, right?

**Comment by nadavhalfon** [comment]
> @zombieJ I agree that this makes sense as a default for link and text buttons, but when the prop is explicitly `primary`, it should respect it, right?

I agree :)

Moreover the example in the docs is very confusing because if you do not intend that setting a "color" will override the color choice you should change the example since it looks like the text and link are always respecting the color but it only looks like this because the primary color of ant is blue, here is another example:
https://stackblitz.com/edit/react-t3ejzn?file=demo.tsx

Thank you very much
