### ISSUE TITLE
请问在table的footer元素中，如何访问this对象

### ISSUE THREAD

**Issue by louiszhu2zgf** [ant-design/ant-design#5150]
```
const footer = () => (
  <div>
    <Button type="danger" style={{marginRight: '10px'}} onClick={() => { this.setModal2Visible(true)}}>批量删除</Button>
  </div>
);
```

**Comment by afc163** [comment]
footer 放到 class 里面。

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!
