### ISSUE TITLE
Collapse折叠面板只有一个时，是否支持默认收起

### ISSUE THREAD

**Issue by fengmiaosen** [ant-design/ant-design#5233]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by afc163** [comment]
You should try before ask.

http://codepen.io/anon/pen/MpJXVY?editors=0010

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!

**Comment by fengmiaosen** [comment]
@afc163 sorry，Its because I set "defaultValue "
