### ISSUE TITLE
Module build failed: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by iamhanson** [ant-design/ant-design#5369]
**I'm learning ant design.According to the exapmles,I copied follow code and build in my way.**
```javascript 

import React from 'react';
import ReactDOM from 'react-dom';
import { Layout, Menu, Icon } from 'antd';
const { Header, Sider, Content } = Layout;
const SubMenu = Menu.SubMenu;
import 'antd/dist/antd.css';
class SiderDemo extends React.Component {
  state = {
    collapsed: false,
  };
  toggle = () => {
    this.setState({
      collapsed: !this.state.collapsed,
    });
  }
//others
```

**error happened **
```javascript 
Module build failed: SyntaxError: Unexpected token
```
**but if I put these method in construct,it works well.**

```javascript 
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      collapsed: false,
      theme: 'dark',
      current: '1'
    };
    this.toggle = () => {
      this.setState({
        collapsed: !this.state.collapsed,
      });
    }
  };
//others
```
 follow the example url
[layout example](https://github.com/ant-design/ant-design/edit/master/components/layout/demo/custom-trigger.md)

**Comment by afc163** [comment]
It is not a antd-related issue, check this: https://babeljs.io/docs/plugins/transform-class-properties/

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!

**Comment by iamhanson** [comment]
Thank you very much
