### ISSUE TITLE
message  getContainer doesn't work

### ISSUE THREAD

**Issue by lcoder** [ant-design/ant-design#5380]
```javascript
message.config( {
    getContainer(){
        console.log('1')   // this should be console.log 1 , but doesn't
        return document.body ;
    }
} )
```
I checkd the code: [config options: ConfigOptions](https://github.com/ant-design/ant-design/blob/master/components/message/index.tsx#L87) find that getContainer never pass into the message module. anyone can fixed it?

**Comment by NE-SmallTown** [comment]
Maybe the [doc](https://github.com/ant-design/ant-design/blob/master/components/message/index.zh-CN.md#messageconfig) needs to update too?

Due to [here](https://github.com/ant-design/ant-design/blob/master/components/message/index.tsx#L98) and [here](https://github.com/ant-design/ant-design/blob/master/components/message/index.tsx#L98)

**Comment by afc163** [comment]
@NE-SmallTown you can PR to improve the documentation.

**Comment by NE-SmallTown** [comment]
@afc163 Ye,but to be honest,at most situations, I am not sure what I do is 100% right,so I think discuss in the issue at first would be better.PRs are more serious and holy than issues for repos.

On the other hand,maybe I will go outside or have something busy to do,so if anyone see this,they can pr too :smile:

**Comment by afc163** [comment]
140f3fb
