### ISSUE TITLE
In Form, if id of getFieldDecorator is variable, how to use setFieldsValue

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#5427]
demo: http://codepen.io/superlxc/pen/PpQMpj?editors=0000

![b](https://cloud.githubusercontent.com/assets/4329120/24142484/a9c5c036-0e61-11e7-9426-4b6d044c2513.png)

![1](https://cloud.githubusercontent.com/assets/4329120/24142545/d99246ae-0e61-11e7-9726-bc18fb34a1b0.gif)

As you can see, I have a data like this, and I want to show the typeValue of the data depends on what type is.

But I can't register the field before setFieldsValue since it's variable.

So how to solve that?

**Comment by afc163** [comment]
```jsx
setFieldsValue({
  [key]: value,
})
```

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!
