### ISSUE TITLE
Navigation sub menu rendering 

### ISSUE THREAD

**Issue by db-ra** [ant-design/ant-design#5586]
### What problem does this feature solve?
When loading a menu, submenu items are rendered only when you click on root element of the menu - this is bad for SEO. We need a feature where entire menu is rendered on load. 

### What does the proposed API look like?
when menu is rendered, submenu elements should be inside DOM

**Comment by useless-stuff** [comment]
Yep same problem here when I've started to use this awesome framework :)
Are there some reasons why the menu or other components hide by default the content? 
I'm not an SEO expert but that means that the search engines can't see the content, right? 
Especially in a menu component that link the most important parts of the application.
Thank you in advance for any clues about that :)

**Comment by plandem** [comment]
I suppose the only reason - optimization for performance.

**Comment by massa-man** [comment]
Not rendering the content until required makes complete sense for performance, but for a component like Menu, it is a big issue with SEO, since bots don't go around the page triggering click and hover events on DOM objects just to see if anything else gets rendered into the DOM, so using this Menu as the main application menu on a public application makes the application very SEO unfriendly.

There should by a prop in the Menu component that allows us to render the child objects by default. Set is as false by default for performance reasons, but allow developers to override that behaviour when using this in public, crawlable applications.

**Comment by plandem** [comment]
I was sure that for SEO a good practice is server-side rendering

**Comment by bang88** [comment]
Yep, need fix. I have a server-side rendering example using asp.net core. 

https://github.com/bang88/aspnet-core-react-antd-boilerplate

**Comment by massa-man** [comment]
Server side rendering is not necessary with modern search bots and
JavaScript based apps (at least Google, baidu is a bit behind Google in
this). Google bot will execute any JavaScript on the page and will render
the react components, what it will not do, AFAIK, is go around every single
Dom element in the page and trigger any user interaction event to see if
anything else gets rendered. As long as the menu renders the entire tree
when the main component renders, then Google bot would be able to see and
follow the menu links.

**Comment by benjycui** [comment]
Pending for: https://github.com/react-component/menu/issues/19

And we need to add a feature to rc-trigger, to force rendering popup menu to `document.body` when Menu is mounted.

**Comment by benjycui** [comment]
We can just force submenu render after componentDidMount, for Menu is based on rc-trigger which  are not able to render nodes before componentDidMount.

It's good enough for something like Google which will run javascript before analyse DOM.

**Comment by yesmeck** [comment]
A new prop called `forceSubMenuRender` will be added in antd@3.

**Comment by Stephen920611** [comment]
我想问一下，现在3.0 子菜单如何更改样式啊，为何查看不到dom元素了

**Comment by yesmeck** [comment]
在 body 上
