### ISSUE TITLE
DatePicker Tooltip Incorrect Format

### ISSUE THREAD

**Issue by ifflanb** [ant-design/ant-design#5724]
### Version
2.9.1

### Environment
Windows 10, Chrome 57.0.2987.133 (64-bit), React v15.4.2

### Reproduction link
[http://codepen.io/ifflanb/pen/VbZGJV](http://codepen.io/ifflanb/pen/VbZGJV)

### Steps to reproduce
Add a format for a DatePicker e.g. 'DD/MM/YYYY' > open DatePicker so that the calendar is displayed > select a date > look at the tooltip.

### What is expected?
Expect that the tooltip displayed matches the date format set on the date picker (e.g. if format is 'DD/MM/YYYY' I expect a tooltip like 01/01/2017.

### What is actually happening?
Format is ignored e.g. 2017/01/01 instead of 01/01/2017

**Comment by benjycui** [comment]
I don't understand, could you post some screenshots?

**Comment by nick-loader** [comment]
![image](https://cloud.githubusercontent.com/assets/17534962/25161669/7f85eef6-2511-11e7-9ad8-d02f8cb18864.png)

Notice the difference in the selected date value and the value inside of the tooltip e.g. 19/04/2017 is in the correct format but the tooltip shows 2017-4-19.

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/calendar/issues/222

It seems that we cannot solve this issue perfectly, until we add a new API.

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`

**Comment by abhayopspl** [comment]
Hey @benjycui Ni Hao :-P

![image](https://user-images.githubusercontent.com/35765637/37091835-9b959e5e-222f-11e8-8d89-c134d304bff4.png)

See the title attribute in the red line. When Antd date picker component generates the calender component, it is passing the title props a wrong value. Maybe the format of the date passed is not correct there.

So in your code logic, instead of generating a new time object and passing it in, please just pass the format value passed into DatePicker as props.

Hope this helps
