### ISSUE TITLE
Docs: Notification doesn't close itself after 4.5s 

### ISSUE THREAD

**Issue by gudh** [ant-design/ant-design#5869]
First of all, thanks for building antd, I am amazed at how FANTASTIC it is! 🌷

### Version
2.9.2

### Environment
lastest MacOS, Chrome

### Reproduction link
[https://ant.design/components/notification/](https://ant.design/components/notification/)

### Steps to reproduce
It's in the online docs 

### What is expected?
It should close itself after 4.5s 

### What is actually happening?
Notification doesn't close itself after 4.5s

Keep up great work! ❤️

**Comment by benjycui** [comment]
@afc163 close this issue?

**Comment by afc163** [comment]
Fixed in 2.9.3

**Comment by AsceticBoy** [comment]
online example, if you click several times frequently, after 4.5 secs, you will see after all Notifications close, have one Notification open again! I find <Notice /> component will in DidMount inject timer again

**Comment by afc163** [comment]
@AsceticBoy You can file a new issue about it.

**Comment by afc163** [comment]
@AsceticBoy I just revert https://github.com/react-component/notification/pull/17 and released in rc-notification@2.0.2, you can try to reinstall node_modules.

**Comment by paranoidjk** [comment]
hmm...  intersting bug 😅  I wonder why

**Comment by AsceticBoy** [comment]
A intersting bug, when set animateProps.component = '', it will find children[0] to return in <Animate />, so it will come <Notice /> DidMount to register Timer! Thx @afc163 resolve my problem

**Comment by paranoidjk** [comment]
The reason is  `animateProps.component` changed when destroy  the last but one notification instance, which caused the rc-animate root component tree rerendered, so the last notification actually is a totally new instance, so the timer is a restarted new timer too.

@afc163 But revert this will have influence on https://github.com/ant-design/ant-design-mobile/issues/1389, please fix this or release rc-notication as a major upgrade.
