### ISSUE TITLE
Modal.confirm and other global popup component can't set redux HOC Connect as content

### ISSUE THREAD

**Issue by zheeeng** [ant-design/ant-design#6321]
### Version
2.9.3

### Environment
MacOS 10.11.6

### Reproduction link
[http://sorry.its.easy.to.reasoning](http://sorry.its.easy.to.reasoning)

### Steps to reproduce
Create a Redux HOC Connect and a dump component, in dump component attach a click event on a button, it will popup Modal.confirm. This confirm contains the HOC Connect.

### What is expected?
The confirm dialog popup.

### What is actually happening?
Console report: `browser.js:40 Uncaught Error: Could not find "store" in either the context or props of "Connect(ModuleSelect)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(ModuleSelect)".`

ModuleSelect is the HOC Connect.

**Comment by benjycui** [comment]
What is your use case?

`Modal.method` is just for convenience, so they cannot/are not to support edge case.

**Comment by NE-SmallTown** [comment]
That's because your root component don't include your `Connect(foo)` component.So you know that the reason of the `Connect` component of react-redux can read `store` is that the `context` API.But if you put your  `Connect(foo)` component into a container which not in root component.The  `Connect(foo)` component can' read the `store` by `context` API because your `Provider` component under the root component.

So,just like the error says,you can wrap your component with the `Provider` component or pass the `store` as a prop to the component.

e.g.

`<Modal><Foo store={this.context.store} /></Modal>` or `<Modal><Provider store={this.context.store}><Foo /></Provider></Modal>`

**Comment by zheeeng** [comment]
@NE-SmallTown You are right, with this reason, Modal.confirm can't contain the Connect component, but will Modal.confirm provide an injecting mechanism in the future @benjycui ? Generate a Connect component in render method and then provide it to Modal.confirm.

**Comment by benjycui** [comment]
@zheeeng actually, you should get context data when you call `Modal.confirm`:

```jsx
handler() {
  const { data } = this.context;
  Modal.confirm(data);
}
```

You don't need to connect Modal.confirm, as I said, it just for convenient, don't make it so complicated.
