### ISSUE TITLE
DatePicker: clicking "Today" with a specified locale - French, German etc., changes the months to Russian

### ISSUE THREAD

**Issue by justcurious** [ant-design/ant-design#6645]
### Version
2.11.2

### Environment
Windows 7 (64bit), Firefox 54.0 (32 bit) 

### Reproduction link
[https://codepen.io/anon/pen/XgVbQM?editors=0010](https://codepen.io/anon/pen/XgVbQM?editors=0010)

### Steps to reproduce
1. Click the datePicker input to show the dropdown.
2. Click on "Aujourd'hui" at the bottom ('Today' in French)
Month names immediately switch to what looks to be Russian.

### What is expected?
French is the locale, so I expect 'Today' to go to the current day and continue to show French month names

### What is actually happening?
Months names now show as Cyrillic characters (my guess, Russian) in the datePicker.

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design/issues/4972#issuecomment-281235293

**Comment by afc163** [comment]
Here is the problem, Why Russion?

**Comment by priornix** [comment]
Hi guys, 

Thanks for the great work on this amazing project.

Just a few questions, why is this issue closed?

1. Why is it necessary need to set defaultValue in order for the text to be displayed correct? Doesn't this impose a restriction on the UI?
2. As shown in the codepen in this issue and in #4972, when the user clicks on the "Clear" icon, the DatePicker language reverts back to Russian. This is clearly a bug.
3. @benjycui I looked at your comments, but isn't it possible that since we are able set the locale of the components using LocaleProvider, that the DatePicker uses it's own instance of moment locale? https://momentjs.com/docs/#/i18n/instance-locale/.

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design/issues/5570#issuecomment-312167390

And we will publish something like `antd/dist/antd-with-external-moment.js` later. cc @yesmeck

**Comment by priornix** [comment]
Well, so this issue should be re-opened right?

**Comment by afc163** [comment]
with => without

**Comment by afc163** [comment]
> Well, so this issue should be re-opened right? Also, does it mean that using an external moment library will solve this issue?

You don't need a external moment library if you are using npm module. It is a problem only for using `antd/dist/antd.js`.

**Comment by priornix** [comment]
Shall I create a new issue for this that states that this issue exists for cases that uses `antd/dist/antd.js` directly?

**Comment by benjycui** [comment]
> Shall I create a new issue for this that states that this issue exists for cases that uses antd/dist/antd.js directly?

👍

**Comment by priornix** [comment]
Okay, new issue has been created, #6712, thanks!
