### ISSUE TITLE
Cleared data show in TreeSelect again when use AllowClear button

### ISSUE THREAD

**Issue by BillQiu** [ant-design/ant-design#6731]
### Version
2.11.2

### Environment
OSX, Chrome 59

### Reproduction link
[https://codepen.io/bill_q/pen/XgYgrw](https://codepen.io/bill_q/pen/XgYgrw)

### Steps to reproduce
1. select nodes in treeSelect
2. click clearAll button
3. click chechbox

### What is expected?
nothing in input

### What is actually happening?
cleared values show in input

**Comment by bang88** [comment]
I think it should use defaultValue here.

**Comment by BillQiu** [comment]
it doesn't work @bang88

**Comment by paranoidjk** [comment]
It because rc-tree-select did't clear cache data when you click clear icon.

I will handle this.

https://github.com/react-component/tree-select/blob/master/src/Select.jsx#L494

**Comment by paranoidjk** [comment]
@BillQiu Do not close this until https://github.com/react-component/tree-select/pull/61 get merged.

**Comment by BillQiu** [comment]
got it @paranoidjk

**Comment by afc163** [comment]
@paranoidjk

**Comment by paranoidjk** [comment]
@afc163  👌  I will have a look toady, pretty busy theses days.

**Comment by 43Laboratories** [comment]
Any updates on this? Having issues when dynamically changing options of a treeselect component. Where if i have a set of filters. I query lets say Option 1, select a filter which removes option 1 from the optionslist. however since i queried it it is still in cache. and until i trigger a different search it doesn't remove it from the options... Not sure how i can work around this rn.
