### ISSUE TITLE
Why does the component didn't receive 'value' prop in componentDidMount method while it is wrappered by getFieldDecorator 

### ISSUE THREAD

**Issue by liuzhenji** [ant-design/ant-design#6920]
### Version
2.12.1

### Environment
MacOS, Chrome

### Reproduction link
[https://codepen.io/anon/pen/OjLjGa?editors=001#anon-signup](https://codepen.io/anon/pen/OjLjGa?editors=001#anon-signup)

### Steps to reproduce
no operations.Just like the title

### What is expected?
component can receive value props transported from the wrapper
![code image](https://user-images.githubusercontent.com/10750792/28487803-ed7182aa-6ecb-11e7-9664-a9db05963ce3.png)
![code image](https://user-images.githubusercontent.com/10750792/28487811-181b9d92-6ecc-11e7-8127-d2030e019a16.png)

### What is actually happening?
didn't receive

**Comment by afc163** [comment]
You code don't make any sense, please learn React before using antd or just follow antd example. http://facebook.github.io/react/

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!
