### ISSUE TITLE
Tooltip position bug when the component is on the right side

### ISSUE THREAD

**Issue by topvis** [ant-design/ant-design#7038]
### Version
2.12.3

### Environment
Windows 7, Chrome 60

### Reproduction link
[https://codepen.io/topvis/pen/OjNxam?editors=001](https://codepen.io/topvis/pen/OjNxam?editors=001)

### Steps to reproduce
Run CodePen repo, then hover the mouse over the button.

### What is expected?
The little triangle arrow on the tooltip box should still point to somewhere on the component.

### What is actually happening?
The tooltip points to the wrong position. ref. to the screenshot.
![image](https://user-images.githubusercontent.com/5996531/28799167-70563e7c-7615-11e7-9d50-01efc1f43ad0.png)

**Comment by benjycui** [comment]
Trace: https://github.com/yiminghe/dom-align/pull/22

**Comment by yuezk** [comment]
@benjycui Have this issue been fixed? I can reproduce this issue with the latest Ant Design. Here is a demo compared with the react-bootstrap tooltip.

https://codesandbox.io/s/3xp4x41klq

![image](https://user-images.githubusercontent.com/3297602/53560231-dd8a5e00-3b86-11e9-8ad1-8f4f26670120.png)

**Comment by yuezk** [comment]
@afc163 Can you reopen this issue for easy tracking?

**Comment by yuezk** [comment]
@afc163 

I have been dealing with this issue for a few days and found that the position of the popup element is correct, while the position of the arrow is not correct. So it's not a problem with the `dom-align` module I think.

After debugging, I found that the position of the arrow was hardcoded in the CSS file, instead of calculating dynamically based on the position of the target element and the popup element. Eventually, the position of the arrow is not flexible enough, it will break in some special situations.

I tried to fix this problem on my own. The solution is that I extend the `Tooltip` class and override the `onPopupAlign` method, in which I can get the target element and the popup element both, base on which, I can calculate the correct position of the arrow.

Here is the demo solution. It works well for placements `top` `bottom` `left` and `right`.

[![Edit l9yy576wyz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l9yy576wyz?fontsize=14)

In this solution, I get the target region with the `getBoundingClientRect` method. But I think the better way is accessing the target region through the `align` parameter. Because the method [`doAlign`](https://github.com/yiminghe/dom-align/blob/98bcb1874f90a8725064f76449f85d9a452dba23/src/align/align.js#L69) inside the `dom-align` module has calculated the target region already and covered many corner cases, we don't need to recalculate it anymore. So I think the `doAlign` method should return the target region as well.

https://github.com/yiminghe/dom-align/blob/98bcb1874f90a8725064f76449f85d9a452dba23/src/align/align.js#L196-L201

OK, that's all, the solution above is just a proposal, feel free to comment if you have any question.

**Comment by ztplz** [comment]
https://github.com/ant-design/ant-design/issues/14582
The same reason, `dom-align` resets the points, but then moves the position of the element.

**Comment by yuezk** [comment]
@ztplz May not, I complaining about the position of the arrow, not the position of the popup element.

BTW, #14582 works well for me.

![image](https://user-images.githubusercontent.com/3297602/53948227-50a15080-4102-11e9-9d39-4513ec9b4ce0.png)

**Comment by ztplz** [comment]
https://github.com/yiminghe/dom-align/blob/98bcb1874f90a8725064f76449f85d9a452dba23/src/align/align.js#L159
虽然我没看到你的demo 但是我觉得问题是一样的  这里在没匹配成功的情况下  它会重置points  
但是然后它又会调整位置  但是其他的组件是根据这个points来决定自己的位置的 所以那些箭头在某些情况下错误方向的

**Comment by ztplz** [comment]
我好像搞错了 不是这个问题 虽然有关联  但是关联不大

**Comment by wbobeirne** [comment]
I can confirm that I'm also experiencing this issue, and that @yuezk's workaround works for me as well. Unfortunately the override is a little sub-optimal due to a lot of typing issues, namely that `this.tooltip` is private rather than protected. It'd be nice to see this fixed in antd proper.

**Comment by yuezk** [comment]
There are around 280 issues, 246 of them are marked as inactive. Good job! @ant-design-bot

**Comment by yuezk** [comment]
There are around 280 issues, 246 of them are marked as inactive. Good job! @ant-design-bot

**Comment by afc163** [comment]
@yuezk Feel free to compare with other open source projects, we try our best.

**Comment by afc163** [comment]
Trace https://github.com/react-component/tooltip/pull/166

**Comment by quyctd** [comment]
any update?

**Comment by afc163** [comment]
Supported in antd 5.x now! See https://ant.design/components/tooltip#components-tooltip-demo-shift
