### ISSUE TITLE
Use multiple InputNumber, making changes in one cause others displayed NaN

### ISSUE THREAD

**Issue by JrIdeA** [ant-design/ant-design#7358]
### Version
2.12.8

### Environment
OS: macOS Sierra 10.12.5 ，Browser: 60.0.3112.101 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/jridea/pen/yoReRX](https://codepen.io/jridea/pen/yoReRX)

### Steps to reproduce
input a number to `A`, and `B` displayed `NaN`.

![](http://ocblkgavm.bkt.clouddn.com/2017-08-28-070910.jpg)

### What is expected?
B displayed empty

### What is actually happening?
`B` displayed `NaN`

**Comment by jaggerwang** [comment]
![image](https://user-images.githubusercontent.com/1255011/29763672-bacb0f1c-8c06-11e7-9434-499e243b4e10.png)

Similar problem. When focus leave a input with NaN value, it's value changed to "", but all others changed to NaN. It's strange that it's ok in development, only occur in build version.

**Comment by gronstrand** [comment]
I am experiencing the same problem when using InputNumber components inside of controlled forms. It seems to be caused by [this commit](https://github.com/react-component/input-number/commit/24d87191fd5e079ef32e7dbf9ed61ddc72ced197) to rc-input-number, if revert to 3.6.5 it works. 

@jaggerwang The reason it breaks in your build but not in development is probably because you have an older version of rc-input-number installed locally than in your other build, even though antd is the same.
