### ISSUE TITLE
Default theme shouldn't fetch icons from CDN

### ISSUE THREAD

**Issue by ojab** [ant-design/ant-design#7809]
### Version
2.13.4

### Environment
--

### Reproduction link
[https://github.com/ant-design/ant-design/blob/89a6aa96eda893ab2ad2b66fd0b0bee1ed5e21bc/components/style/themes/default.less#L58](https://github.com/ant-design/ant-design/blob/89a6aa96eda893ab2ad2b66fd0b0bee1ed5e21bc/components/style/themes/default.less#L58)

### Steps to reproduce
--

### What is expected?
antd shouldn't fetch anything from network

### What is actually happening?
Right now icons are fetched from CDN

---
1. CDN (and external network in general) can be unavailable due to various reasons
2. Information leakage (IPs/Referer/etc) is a security issue and it definitely shouldn't happen in default configuration

I assume that default iconset should be bundled into antd or provided via separate package/dependency.

**Comment by nikogu** [comment]
Using the cdn can make your project to small. and the cdn address will not be broken. It's very reliablly.

The cdn services service provider  is alibaba.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1070

https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

**Comment by ojab** [comment]
Well, project size is mostly irrelevant:
- icons size is negligible compared to the sum of other npm packages in typical project
- client should download them anyway, no matter where they are located, so project size as seen by the client is the same

CDN is not so reliable, as can be seen in https://github.com/ant-design/ant-design/issues/1070

Anyway, security concern still stands.

I know that antd can be configured to serve locally hosted iconfont, but this issue is about default settings and I think that it should be reopened/fixed.

**Comment by martijntraa** [comment]
I agree with @ojab that:

* this is a security concern (it is for the projects/clients I work for);
* that the default should be not to use a CDN, with a seperate example to explain how to use antd with a CDN;
* that project size doesn't seem to be a relevant issue.

**Comment by davschne** [comment]
My organization is using antd in one of our applications, and we recently discovered an intermittent (and thus hard to diagnose) bug where an icon had disappeared. We discovered that the request for the anticon font on Alibaba was timing out, so it seems it's not quite as reliable as you may believe. We ended up hosting the font files as static resources locally, but doing so was not trivial. Please, please, please don't force users of this wonderful library to rely on an unreliable CDN (or else have to resort to advanced configuration) for something as small and simple as a font file.

**Comment by tibdex** [comment]
Hi Ant Design team and thank you for this beautiful library. I agree with all the previous concerns and would like `antd` to work offline too.

I'm trying to make a PR to use a local icon font but it's not very easy to understand how your build work with your webpack configuration spread across [webpack.config.js](https://github.com/ant-design/ant-design/blob/0bb531aca6cb2045d5323196a599c925537a4eb0/webpack.config.js) and [getWebpackConfig.js](https://github.com/ant-design/antd-tools/blob/e174b6723b304fe1c7c637ed5debc2513477e4d9/lib/getWebpackConfig.js) in https://github.com/ant-design/antd-tools. I'm currently getting nasty webpack loader errors when trying to have the font files end up in `dist`.

Before I invest more time in this, can you confirm that you would be willing to change the default theme to stop using the Alibaba CDN and ship the icon font files with the library instead?

**Comment by yesmeck** [comment]
I think the initial purpose of using CDN fonts is designed to simplify the process of using `antd`.

And Change this behavior will introduce a breaking change.

**Comment by ojab** [comment]
Another package w/ fonts in dependencies and `@icon-url` from that package (or even packaging fonts into `antd` itself) is no more difficult than using font from CDN.

This change will be breaking for cdnjs/unpkg/etc users if fonts will be packaged separately, but it probably can be solved by some kind of fallback (to CDN) for the current major version.

Anyway, technical moments are unrelated unless there is an agreement that CDN usage out of the box is indeed an issue.

**Comment by tibdex** [comment]
> The initial purpose of using CDN fonts is designed to simplify the process of using `antd`.

It might make it simpler for some users but it also prevents a lot of projects required to work off-line or without making requests to chinese servers to use Ant Design [without hacks](https://ant.design/components/icon/#Local-deployment).

I tried to mitigate the problem by not using the `<Icon />` component at all in my project but the fonts are eagerly loaded from the CDN so I cannot use any Ant Design component without this undesirable network request being made.
 
I can see two potential improvements:
 1. Use local icon font assets.
 2. Do the right thing and use SVG instead of an icon font. GitHub has a [convincing blog post](https://github.com/blog/2112-delivering-octicons-with-svg) on why this is a superior approach. This solution solves the CDN problem without making Ant Design harder to use since SVG is supported natively by React and the icon font is already abstracted behind the `<Icon />` React component.

What do you think of the last technique?

**Comment by yesmeck** [comment]
Proposal 2 looks like a viable option, but it's still a breaking change, we may revisit this issue when when we plan on 4.0

**Comment by tibdex** [comment]
@yesmeck I don't see how moving the icons from a font to embedded SVG would be a breaking change. The only visible change would be the absence of external HTTP requests which is a good thing.

The way I see it, it would make things easier for you as you wouldn't have to maintain the [local-iconfont package](https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont) anymore.

Besides, you already have the icons in SVG format. Indeed, it's the format used when you search for Ant Design icons on http://iconfont.cn/ and also the one imported here:

https://github.com/ant-design/ant-design/blob/c04377e5413d344b37c34ceac6fee456933fa516/components/style/core/iconfont.less#L14

Thus, the only thing to do to implement my "proposal 2" would be to split this SVG file into multiple React components (which is doable since [React has full support for SVG](https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes)) and use the existing `<Icon />` component to render the correct one.

If I were to submit a PR with these changes, would you consider approving it and merging it as a minor or patch release (without waiting for 4.0)?

**Comment by yesmeck** [comment]
You can't style SVG by `font-size`, so I think it's breaking change.

**Comment by tibdex** [comment]
This ["Align SVG Icons to Text and Say Goodbye to Font Icons" article](https://blog.prototypr.io/align-svg-icons-to-text-and-say-goodbye-to-font-icons-d44b3d7b26b4) explains how to scale SVGs like an icon font with the "1 em technique".

**Comment by yesmeck** [comment]
@tibdex Thanks for the link, I have some more concerns:

1. How can we support `line-height` which people may already used for font icon?
1. If we don't change the API of `Icon` component, do we need to bundle all SVG icons to production build?

**Comment by tibdex** [comment]
1. The article I linked to in my last comment also talks about `line-height`. [Its Codepen](https://codepen.io/elliotdahl/pen/ygYrvm) is using it too. Is this what you're thinking about?
2. Yes `<Icon />` would import all the SVG icon components and render the correct one with a `switch` based on the `type` prop. I know it's not ideal because it will increase the library size but it's the only way to do it without introducing breaking change or without relying on [dynamic `import()`](https://github.com/tc39/proposal-dynamic-import).
In the long term, we should probably do it the way [Material UI](https://www.material-ui.com/#/components/svg-icon) does it by using one React component per icon. Then we could leverage the [babel-plugin-import](https://ant.design/docs/react/use-with-create-react-app#Use-babel-plugin-import) technique to export all the icon components from a centralized `icons/index.js` module without impacting the bundle size.

I don't know if you've read the links listed at the end of the ["Align SVG Icons to Text and Say Goodbye to Font Icons" article](https://blog.prototypr.io/align-svg-icons-to-text-and-say-goodbye-to-font-icons-d44b3d7b26b4) but they are really convincing. Especially these ones:
 - [Inline SVG vs Icon Fonts](https://css-tricks.com/icon-fonts-vs-svg/)
 - [Seriously, Don’t Use Icon Fonts](https://cloudfour.com/thinks/seriously-dont-use-icon-fonts/)

I believe it's worth switching to SVG icons in one of the next minor releases as it will make the icons sharper and the library significantly easier to use off-line. Shall we try?

**Comment by yesmeck** [comment]
@tibdex Could you create a separator issue?

**Comment by felops** [comment]
Could anyone change the "@icon-url" following the documentation? I am following the step-by-step guide for create-react-app (https://ant.design/docs/react/use-with-create-react-app#Customize-Theme) and all my less modifications was working well, but I am not able to set "@icon-url". Is that an issue?
