### ISSUE TITLE
form表单提交后，服务器返回的错误信息怎么在validator的错误提示框中显示？

### ISSUE THREAD

**Issue by google88888888** [ant-design/ant-design#8005]
### Version
2.13.7

### Environment
chrome

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
form表单提交后，服务器返回的错误信息怎么在validator的错误提示框中显示？

### What is expected?
form表单提交后，服务器返回的错误信息怎么在validator的错误提示框中显示？

### What is actually happening?
form表单提交后，服务器返回的错误信息怎么在validator的错误提示框中显示？

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!

**Comment by warmhug** [comment]
这个也被问到了、感觉还是很常见的。使用 `setFields` 解决、感觉可以做个 demo。
