### ISSUE TITLE
Upload: list-type为picture-card时，beforeUpload返回false后，文件仍然为上传中的状态

### ISSUE THREAD

**Issue by elfman** [ant-design/ant-design#8020]
### Version
2.13.7

### Environment
Mac OSX 10.12.6, Chrome lastest

### Reproduction link
[https://codepen.io/HarlonLuo/pen/eGqrBb?editors=0010](https://codepen.io/HarlonLuo/pen/eGqrBb?editors=0010)

### Steps to reproduce
点击添加图片按钮，选择一个图片

### What is expected?
在beforeUpload返回false后，直接显示图片缩略图

### What is actually happening?
无缩略图，文字一直显示“文件上传中”

**Comment by nikogu** [comment]
参看文档：https://ant.design/components/upload-cn/#API

当 `beforeUpload` 返回 `false` 时停止上传。

**Comment by elfman** [comment]
是停止上传了，但是图片还是显示“文件上传中”，这不是bug吗？

**Comment by nikogu** [comment]
`Upload` 组件确实没有做 `local preview`，但是可以自行控制 `fileList`，参考：

```jsx
beforeUpload: (file) => {
  const reader = new FileReader();
  reader.readAsDataURL(file);
  reader.onload = function(e) {
    // this is local preview
    file.url = e.target.result;
    this.setState(({ fileList }) => ({
      fileList: [...fileList, file],
     }));
  }
   return false;
}
```

如果你觉得需要内置或者有更好的实现，欢迎提交 pr

**Comment by elfman** [comment]
现在的`Upload`在`type`为`picture-card`时，如果上传成功，显示的图片是`local preview`啊，查看元素可以看到`img`的`src`属性是`data:image/xxxxxx`，但用`beforeUpload`返回`false`不上传时这个图片并没有显示出来，应该是代码里没有将`uploading`这个状态修改回来

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design/blob/master/components/upload/UploadList.tsx#L77

应该是这段，但是这个地方交互上不太好处理，因为显示缩略图容易让别人以为已经上传了。所以其实 `uploading` 这个状态也是有道理的

**Comment by elfman** [comment]
应该是再上两行的判断，`beforeUpload`为`false`之后，为啥`file.status === uploading`仍然为`true`

**Comment by nikogu** [comment]
这块交互还需要再讨论下 @afc163

**Comment by YuArtian** [comment]
我也遇到这个问题了，所以怎么不显示上传中，而是显示缩略图呢？

**Comment by lehug** [comment]
我的期望是手动上传多张照片，点击上传只是选择照片执行预览，然后再通过一个特定的按钮，触发批量上传到后台，使得调用后台频率减少，数据有效性提高

**Comment by luyimei** [comment]
i think it's a bug.
don't use `return false` , use `Promise` and `reject` will avoid the unwanted loading file.

**Comment by CallMeXYZ** [comment]
@luyimei was right, `return false` still fires `onChange` while `promise` not

**Comment by littleLane** [comment]
I am not completely agree this `pr`!
There is a reason that when the selected file verification fails, 
some people want to show original button instead of thumbnail to `re-select` other photo!
And displaying a thumbnail will make the user `feel that the picture was uploaded successfully`!
Maybe, this should `be configurable`!
This is my idea！

**Comment by iiiok** [comment]
luyimei's solution solved my issue, filtering out the "file oversize" file in beforeUpload().
but for the file.type filtering, I guess we can just use "accept: fileType", a build-in option.

**Comment by jYh1014** [comment]
我也发现了，在beforeUpload钩子函数里面，return false并不能阻止文件的上传，但是可以用promise里面的reject(file)来阻止

**Comment by kennylbj** [comment]
+1

**Comment by mattcarlotta** [comment]
This component is probably one of the most finicky components I've ever had to work with. I wanted to validate the file **without** uploading to my API, and only after passing validation, can a user click an Upload button to initiate the upload. When using the @luyimei solution, the upload box border becomes red (as if it failed to upload and/or contains wrong file specifications) and ultimately looks incorrect. So... I had to basically write something like so:

Working example:
https://codesandbox.io/s/8zkz2vn4kj

Working example (red outline):
https://codesandbox.io/s/wo15m3qzz7

 ```
 beforeUpload = (file, fileList) => {
    const isJPG = file.type === "image/jpeg";
    const isPNG = file.type === "image/png";
    const isGIF = file.type === "image/gif";
    const isLt2MB = file.size / 2048000 <= 1;

    if ((isJPG || isPNG || isGIF) && isLt2MB) {
      this.getBase64(file, imageUrl => this.setState({ imageUrl }));
      return false;
    }

    return new Promise((resolve, reject) => {
      message.error(
        `Only 2MB jpg/png/gif files are accepted! Instead, received a ${(
          file.size / 1024000
        ).toFixed(1)}MB (${file.type})!`,
        5
      );
      reject(file);
    });
  };
```

I feel like uploading the image after pressing "OK" should be optional from the beginning, otherwise it makes validating an image before uploading pretty inflexible. It took me about 8 hours to realize I had to force `loading` to always be false and set `customRequest` to null before I finally had full control. Even then, this far from a best solution.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15561#issuecomment-475108235

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15561#issuecomment-475108235
