### ISSUE TITLE
style problem of Table component with fixed column and scroll attr

### ISSUE THREAD

**Issue by hirohe** [ant-design/ant-design#8079]
### Version
2.13.8

### Environment
mac and pc; chrome 61;

### Reproduction link
[https://codepen.io/anon/pen/ooXVNx?editors=0011](https://codepen.io/anon/pen/ooXVNx?editors=0011)

### Steps to reproduce
```js
const columns = [
  {
    title: 'col1',
    dataIndex: 'col1',
    key: 'col1',
    width: 100,
  },
  ...
  {
    title: 'action',
    key: 'action',
    width: 100,
    fixed: 'right',
    render: () => <a>click</a>,
  }
]

...

<div style={{width: 500}}>
    <Table rowKey={r=>r.id} columns={columns} dataSource={data} scroll={{ x: 400 }}/>
</div>
<div style={{width: 300}}>
    <Table rowKey={r=>r.id} columns={columns} dataSource={data} scroll={{ x: 400 }}/>
</div>
```

### What is expected?
.

### What is actually happening?
当表格的父元素宽度大于表格组件设置的scroll.x的值时，设置了固定表的一列会出现重复的问题；小于或等于scroll.x时正常
![image](https://user-images.githubusercontent.com/14357567/32257643-3f7b0f88-bef1-11e7-9358-dd03f1455331.png)

当不确定表格的父元素的宽度时，scroll.x不好确定，这样的情况是否有一些解决方法呢？

**Comment by afc163** [comment]
`scroll={{ x: '150% '}}` Try this.

**Comment by hirohe** [comment]
`scroll={{ x: '150% '}}` seems not work
codepen updated: [codepen](https://codepen.io/anon/pen/ooXVNx?editors=0011)
![image](https://user-images.githubusercontent.com/14357567/32258629-90456972-bef6-11e7-883f-35da8a194ca3.png)

**Comment by yesmeck** [comment]
1. Container width should not greater than table width;
2. Leave at least one column's width to auto, so that table can adjust it's width automatically.

**Comment by joshbenhamou** [comment]
@yesmeck Unfortunately, that's not really a workable solution because the column with an undefined width can get squashed. The solution I'm currently using is to define a min-width property on the column. It would be great if this was a property we could define on the column rather than in CSS though?

**Comment by CorkyMaigre** [comment]
Antd table writes the tags (i.e., `<th>` and `<td>`) of the fixed columns two times: once with the other columns and once in a specific table tag corresponding to the fixed elements.

What you need to do is to hide the one which is with the other ones and render only the fixed one.
You can do that by overwritting the CSS properties.

Use `visibility: hidden` instead of `display: none` otherwise the column next to the fixed one will go under it.

```css
.ant-table-body .ant-table-fixed .ant-table-thead tr th:last-child,
.ant-table-body .ant-table-fixed .ant-table-tbody tr td:last-child {
  visibility: hidden;
}```

**Comment by joshbenhamou** [comment]
Thanks @CorkyMaigre! That hides the issue from the user (had to make some tweaks for the header as it wasn't hiding). I'll leave this open since the root cause should probably be fixed

Thanks again!

**Comment by johannhuang** [comment]
> Specify the width of columns if header and cell do not align properly.

The way I figure out according to the above reference is to set `width` for the fixed column(s).

**Comment by Akash91** [comment]
The  width for columns under scrollable section can't be set, if using fixed columns in the table.

**Comment by AltRoot17** [comment]
try to use
`fixed: 'right' as const, `
