### ISSUE TITLE
Affix on table header

### ISSUE THREAD

**Issue by hermanfenderson** [ant-design/ant-design#8112]
### What problem does this feature solve?
Even if you can have scrollable tables with a fixed header a different scenario could be to leave the table at its actual size and fix the header somewhere in the viewport.
At present (at least this is my understanding) you can't affix only the header of a table and make all the rest scroll "under" it.
I think you could "emulate" this behavior by creating a header of a table and a table with same column widths but it seems quite a complicated "kludge"...

### What does the proposed API look like?
Add a affix property to table...

**Comment by hermanfenderson** [comment]
Just a quick extra comment. if I put a very high value in the scroll y and affix the table it should work. So it could be enough to have an "infinite" y scroll...

**Comment by allan2coder** [comment]
have u solve this problem?

**Comment by hermanfenderson** [comment]
No...

**Comment by allan2coder** [comment]
I have solved it by scroll event. The main code as following:

```
    componentDidMount() {
        window.addEventListener("scroll", this.handleScroll);
    }

    handleScroll = e => {
        let scroll = e.path[1].scrollY;
        let tableHead = document.getElementsByTagName("thead")[0];

        if (scroll > 193) {  // when the mouse scroll to this height
            let tableHead = document.getElementsByTagName("thead")[0];
            tableHead.setAttribute("id", "fixed");  // add a style to fixed the table header
        }

    };

    componentWillUnmount() {
        window.removeEventListener("scroll", this.handleScroll);
    }
``` 

try it.

**Comment by hosembafer** [comment]
@allan2coder thank you for a nice example, I'm starting to use this, but there are problems in some cases.

For example, if my window height is 1000px, and I want to load 10 items per page/scroll, and height of each item is 50px, your example will not be working. Because scrollbar of tbody will not be rendered, I will be not able to scroll more.

@afc163 this feature is very important, I think you need to implement it. I'm starting my third project with ant.design and have the same issue with this.

**Comment by hosembafer** [comment]
Sorry, I have chosen the wrong issue for my previous comment.

**Comment by afc163** [comment]
We won't support it which would make Table too complicated.
