### ISSUE TITLE
French Documentation

### ISSUE THREAD

**Issue by TheForgotten69** [ant-design/ant-design#8505]
### What problem does this feature solve?
We could create a french documentation, which will improve the audience of ant design and perhaps bring more volunteer to translate pages still untranslated in english.

### What does the proposed API look like?
Translate the documentation

**Comment by abenhamdine** [comment]
Hmm... Is it really needed ?
Not that I discourage contributions, but indeed, it would be far better first to translate to english remaining parts (eg : https://ant.design/docs/spec/data-entry, https://ant.design/docs/spec/data-entry).

Also I'm convinced that a French developer would rather to get used to read docs in English, since
English is the de facto language for software development.

For the nodejs project, some folks tried to maintain a french translation, but it was too time-consuming to maintain it in the long term.

**Comment by benjycui** [comment]
Nope, all of the maintainers don't know French, so it will be impossible to maintain.
