### ISSUE TITLE
tabs 组件 出现左右滑动的按钮的条件

### ISSUE THREAD

**Issue by wjtGitHub** [ant-design/ant-design#8516]
### Version
3.0.0

### Environment
react16.0

### Reproduction link
[http://none](http://none)

### Steps to reproduce
当add足够多的tab的时候

### What is expected?
出现左右切换页的按钮

### What is actually happening?
无限伸长

---
https://ant.design/components/tabs-cn/#components-tabs-demo-custom-add-trigger

就是想请教一下出现左右页按钮的条件是什么？

**Comment by wjtGitHub** [comment]
@yesmeck

**Comment by yesmeck** [comment]
自己看代码吧。

**Comment by wjtGitHub** [comment]
@yesmeck 唉···搞不清楚改了，我就用redux获取了tabs的数量，就变成了无限伸长。demo还是好的。所以，就像问一下

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!

**Comment by wjtGitHub** [comment]
@afc163 OK，朱偏右，麻烦了
