### ISSUE TITLE
React virtualized for Ant Table

### ISSUE THREAD

**Issue by patrickjtoy** [ant-design/ant-design#9176]
### What problem does this feature solve?
Allows for similar functionality to the List component for tabular data. This would give the option to have a non-paginated table for large data sets where a user could scroll through without caring what "page" some data is on.

### What does the proposed API look like?
```
<Table columns={[...]}>
  <ReactVirtualizedData />
</Table>
```

**Comment by yesmeck** [comment]
Track in #3789

**Comment by entrptaher** [comment]
Whoever coming from Google, here is an awesome library that solves the problem.

https://github.com/wubostc/virtualized-table-for-antd

**Comment by StallionV** [comment]
@entrptaher   With ant design 4 out and virtual table example show would you still suggest
`[https://github.com/wubostc/virtualized-table-for-antd](https://github.com/wubostc/virtualized-table-for-antd)`

or implement using 

`[https://ant.design/components/table/#components-table-demo-virtual-list](https://ant.design/components/table/#components-table-demo-virtual-list)`

We are also wanting ability to select rows along with infinite scroll.

**Comment by entrptaher** [comment]
The example provided by ant.design could be simplified even more. They put a lot of boilarplate while the example provided by wubostc focused on the data. 

If they can simplify the example even more with some props, or export it by default, I would suggest the example by ant.design because it's their own product, using their own api. Otherwise it's still the vt-d example for me.
