### ISSUE TITLE
Popover inside Table with Fixed Column closes on any click inside the Popover

### ISSUE THREAD

**Issue by simondiep** [ant-design/ant-design#9262]
### Version
3.2.0

### Environment
OSX El Capitan, Chrome 63

### Reproduction link
[https://codesandbox.io/s/ovojjom279](https://codesandbox.io/s/ovojjom279)

### Steps to reproduce
Create a Table and put a button in a column header that is `fixed: left` to open a Popover.  Now open the Popover and click inside it.

### What is expected?
The Popover should remain open.  This is what currently happens if you remove `fixed: left` from the column

### What is actually happening?
The Popover closes

**Comment by fayhy** [comment]
We have encounted the same issue, here is what I tested.

There are actually two popovers exists because the fixed column is rendering as two columns (.ant-table-fixed-right and .ant-table-scroll) internally.

When "visible" is not been set, or "onVisibleChange" is disabled, it works well.

But if "visible" is controlled by some logic, when click inside one popover, another popover's "onVisibleChange" is triggered,  "visible" is set to false, so the popover is closed.

Related with #9217

**Comment by Shenenkaka** [comment]
The same issue.
Actually a bug ?
Does someone has solution?

**Comment by Shenenkaka** [comment]
sorry for my thought～
i have fixed my issue。just wrapped a component for popover。component inside use visible state and isCurrentRow property to control popover visible 。

**Comment by omaji7** [comment]
Hello Shenenkaka,

Can you please paste the solution here that how did you managed the visible state and isCurrentRow proprty to handle the multiple popover?

Thanks in advance

**Comment by patientayo** [comment]
Any progress ?

**Comment by afc163** [comment]
This issue has been resolved in [antd v4](https://github.com/ant-design/ant-design/issues/21656) due to Table component refactor, please try it.

**Comment by SmaileLee** [comment]
ant-design-vue
version：1.5.0
popover 组件在 table column 设置了 fixed 属性并且使用 v-model 控制卡片显隐时，打开卡片后，点击卡片任意位置卡片会被关闭

**Comment by yoyo837** [comment]
@SmaileLee 请到 https://github.com/vueComponent/ant-design-vue 这里提交问题。
