### ISSUE TITLE
Is there any way to disable all animations?

### ISSUE THREAD

**Issue by supnate** [ant-design/ant-design#951]
Such as when hover on a table row we don't want the transition of background color, for dropdown list we don't want the popup animation, etc. We'd like a quick response system.

**Comment by afc163** [comment]
```css
* {
    animation-duration: 0s !important;
}
```

Quick way to do that but aggressive.

**Comment by supnate** [comment]
Thank you very much @afc163 for the prompt reply. It works for dropdown list but not for the background colour transition.

**Comment by afc163** [comment]
Just Override the transition style.

**Comment by hustcer** [comment]
Nice

**Comment by N00nDay** [comment]
If anyone comes across this and is looking to disable button animation I accomplished it with the following css override:

.ant-btn.ant-btn-background-ghost::after {
  border: none !important;
}

**Comment by jddunn** [comment]
This is one of the top results in Google when searching for customizing Antd's button animations.

Instead of putting this info in the official docs, it's here and it doesn't even work? @mattcarlotta 's response doesn't have any effects with the current version of Antd. 

Going into the lib and into the CSS for the button component, I see this, which is what dictates the button transition on click:

` .ant-btn:focus {
  color: #40a9ff;
  background-color: #fff;
  border-color: #40a9ff;
}
`

First of all, it's bizarre to me that a UI framework would use hardcoded values for styles instead of referencing global theme vars or being able to pass in custom props via the API. From what I can tell, the button animations / transitions are not customizable at all, without overriding the properties with new styles.

To remove the color transition effect when selecting a button, this works (background-color is whatever the original button color is):

`.ant-btn:focus,
.ant-btn.focus {
    background-color: red !important;
}`

And on:hover is the same, but with 'hover' instead of 'focus'. 

But something like, changing the color of the button on selection (initial click) and then immediately reverting the color of the button back after the click, would take a lot more digging and overriding, which is way too much effort for a library that's supposed to streamline writing UI components.

True to its description, Antd really is an "enterprise-class" system by being exceptionally inaccessible to customize with hacky and out-of-date solutions for common design requirements.

**Comment by mattcarlotta** [comment]
@jddunn Please produce a reproducible example. The class selectors provided in my answer still work for the most current Antd version, as demonstrated here: https://codesandbox.io/s/l760xw47lz

You can also use ` border-color: transparent !important;` instead of `animation: 0s !important;`.

**Comment by sheerun** [comment]
Especially annoying are animations that happen upon page load. I think there should be at least less option to disable them. `* { animation-duration: 0s !important; }` is leaving unused css and disables all animations not only ones that happen upon page load

**Comment by ivanhoe-dev** [comment]
I faced the same situation of modal's transition effect and finally found a cure.
For those who would like to disable the default modal transition effect, simply add the followings:
<Modal
transitionName="none"
maskTransitionName="none"
...
/>

**Comment by AndrejGajdos** [comment]
I have never used ant.design, but it would be really nice to have more options like changing animations to [customize theme](https://ant.design/docs/react/customize-theme).

**Comment by thiennhank9** [comment]
> transitionName



> I faced the same situation of modal's transition effect and finally found a cure.
> For those who would like to disable the default modal transition effect, simply add the followings:
> 
> ```
> <Modal
> transitionName="none"
> maskTransitionName="none"
> ...
> />
> ```
This works, but these 2 props are missing in antd documentation for Modal.

**Comment by ivanhoe-dev** [comment]
> > transitionName
> 
> > I faced the same situation of modal's transition effect and finally found a cure.
> > For those who would like to disable the default modal transition effect, simply add the followings:
> > ```
> > <Modal
> > transitionName="none"
> > maskTransitionName="none"
> > ...
> > />
> > ```
> 
> This works, but these 2 props are missing in antd documentation for Modal.

Yes, it's not official config, I found this props from ant design's source code. As there is no existing official solution for this, anyone who wanna fix it could try my solution.

**Comment by DobrinGanev** [comment]
There is a `Wave` component that renders the button as a child component. IMO it will be best to have this optional(a prop).
in the Button component:

```javascript
return isNeedWave ? <Wave>{buttonNode}</Wave> : buttonNode;
```
where the prop `isNeedWave` by default is true

**Comment by elbasan** [comment]
If you want to disable or make the animation slower you can actually just change these `vars` in your webpack config override:
```
@animation-duration-slow: 0.3s; // Modal
@animation-duration-base: 0.2s;
@animation-duration-fast: 0.1s; // Tooltip
```

**Comment by SamanthaGeorges** [comment]
> @mattcarlotta 's response doesn't have any effects with the current version of Antd.

It has, if you put your button inside a div and add this class to the div it's working (as it is in the @mattcarlotta 's codesandbox example)
```
& [ant-click-animating-without-extra-node]:after {
    animation: 0s !important;
    // border-color: transparent !important;
 }
```

**Comment by mattcarlotta** [comment]
@SamanthaGeorges Just a heads up: Wrapping the `Button` within a `div` isn't a requirement unless you want to **conditionally** disable the animation. Alternatively, you can use the CSS selector below within a global stylesheet to affect any Antd buttons that use the fade-out animation:

```css
[ant-click-animating-without-extra-node]:after {
    animation: 0s !important;
    //  border-color: transparent !important;
 }
```

**Comment by rsweetland** [comment]
For those looking to remove animation from antd Popover component, adding `transitionName="none"` worked for me. Thanks @ivanhoe-dev

**Comment by butters16** [comment]
At least for the `TimePicker`, `transitionName="none"` did not work for me and I had to use `transitionName=""` to make it work.

Here is a sandbox https://codesandbox.io/s/basic-antd-4-20-7-forked-90lm5v?file=/demo.js that shows how the animation is disabled, but the picker does not actually function.

Couple this with the fact that I found a couple of places in the repository that reference `transitionName=""`, but none that reference `transitionName="none"` and I plan on using the former 🤞.

**Comment by WannapornNoicheen** [comment]
Instead of disable all animations like this
```
* {
    animation-duration: 0s !important;
}
```
which can affect other styles that are not connected to antd, we could go to `antd/lib/style/default.css` and disable them one by one. 

For example, we wanted to disable animation of select. So we went to `antd/lib/select/style/index.css` and checked which css classes were responsible for the animation. So we ended up overriding the following css classes by setting animation name to `none`:

```
.ant-select-dropdown.ant-slide-up-enter.ant-slide-up-enter-active.ant-select-dropdown-placement-bottomLeft,
.ant-select-dropdown.ant-slide-up-appear.ant-slide-up-appear-active.ant-select-dropdown-placement-bottomLeft {
    -webkit-animation-name: none;
    animation-name: none;
}
.ant-select-dropdown.ant-slide-up-enter.ant-slide-up-enter-active.ant-select-dropdown-placement-topLeft,
.ant-select-dropdown.ant-slide-up-appear.ant-slide-up-appear-active.ant-select-dropdown-placement-topLeft {
    -webkit-animation-name: none;
    animation-name: none;
}
.ant-select-dropdown.ant-slide-up-leave.ant-slide-up-leave-active.ant-select-dropdown-placement-bottomLeft {
    -webkit-animation-name: none;
    animation-name: none;
}
.ant-select-dropdown.ant-slide-up-leave.ant-slide-up-leave-active.ant-select-dropdown-placement-topLeft {
    -webkit-animation-name: none;
    animation-name: none;
}
```

**Comment by AlmazHecker** [comment]
In Antd V5 you can disable all animations using ConfigProvider

  <ConfigProvider
    theme={{
      token: {
        motion: false
      },
      },
    }}
  >
    {children}
  </ConfigProvider>
