### ISSUE TITLE
<Tag> Render error after close tags

### ISSUE THREAD

**Issue by UltimateRedx** [ant-design/ant-design#9758]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
Win10, chrome , React 15.4

### Reproduction link
[https://ant.design/components/tag-cn/](https://ant.design/components/tag-cn/)

### Steps to reproduce
1,Collect a list A containing 10 objects.
2, Render Tags from each object of A.
3, Splice the first object of A when call onClose.
4, Re-render  tags from A.

### What is expected?
When onClose is called, one element of the list is removed and the re-render  should be 9 Tags shown.

### What is actually happening?
The first and the second Tag is deleted from DOM, but list A is still contains 9 objects.

**Comment by UltimateRedx** [comment]
https://codesandbox.io/s/6x4kjxj2rw

**Comment by yutingzhao1991** [comment]
should add uniq `key` on each tag.

https://codesandbox.io/s/0x2nqkpw3w

**Comment by pbrink231** [comment]
i have a weird behavior with tags and you can see it even in your codepen you placed
https://codesandbox.io/s/0x2nqkpw3w

Close the second, and notice first and second go away even though in the array second still shows.

In my app I dont even modify the state on close but it still hides the object on press.  Is there anyway to make tags controlled so if you close them they will just rerender instead of some weird hiding thing they are doing.

You can see in this codepen when I ignore the onclose call back it just hides the tag even though it is still in the array.  Is there a setting to make it not close itself and always follow render.
https://codesandbox.io/s/nw5x6nqll4

**Comment by pbrink231** [comment]
NM I fixed it by adding visible={true}.  Also you used splice with was mutable and removed just the first element so updated it in this example.
https://codesandbox.io/s/nw5x6nqll4

**Comment by ztplz** [comment]
@pbrink231  
https://github.com/ant-design/ant-design/blob/master/components/tag/index.tsx#L82
In fact, if you click the closed icon, `Antd` will default to closing the tag.
https://github.com/ant-design/ant-design/blob/master/components/tag/index.tsx#L79
But if you set `visible`, `Antd` won't default to closing the tag.

**Comment by haracejacob** [comment]
I think It might needs `e.preventDefault();`

https://codesandbox.io/s/agitated-poitras-ilwb2

**Comment by arrt09** [comment]
> should add uniq `key` on each tag.
> 
> https://codesandbox.io/s/0x2nqkpw3w

**Comment by arrt09** [comment]
I had the same problem. But adding a key solves the problem. Thank @yutingzhao1991 for sharing. 
<Tag Mode="closeable" @key="item" OnClose="(e) => onClose(item)" >@item</Tag>
